### ISSUE TITLE
مشکل در لیست سفارشات

### ISSUE THREAD

**Issue by Padandish** [nobitex/docs-api#1]
با سلام
زمانیکه پارامترهای
{
    "order": "-price",
    "type": "buy",
    "srcCurrency": "rls",
    "dstCurrency": "btc"
}
ارسال می شود، لیست خالی برگردانده می شود.

**Comment by mmmce1994** [comment]
ارز مبدا و مقصد جابجا مقداردهی شده ‌اند
"srcCurrency": "btc",
"dstCurrency": "rls"

**Comment by MohammadHasani** [comment]
مثال:
`{
	"srcCurrency":"btc",
	"dstCurrency":"rls",
	"type":"buy",
	"orde":"-price"
}`

**Comment by MohammadHasani** [comment]
من issue رو میبندم.
اگه موردی بود باز باز کنید issue رو 
@Padandish

**Comment by amiradib** [comment]
با سلام

API لیست سفارشات، ظاهرا عمومی است اما به توکن نیاز داره!
POST /market/orders/list

بنده انتظار اطلاعات OrderBook را از این API داشتم اما ظاهرا سفارشات یوزر را برمیگردونه
API برای orderbook ندارین؟
