### ISSUE TITLE
برداشت رمزارز از طریق ای پی آی

### ISSUE THREAD

**Issue by Rezaaaagg05** [nobitex/docs-api#100]
با سلام 
تشکر می کنم از داکیومنت خوبتون برای انجام معاملات از طریق ای پی آی اما اگر امکان برداشت رمزارز از طریق ای پی آی رو اضافه کنید بسیار عالی می شود. لطفا در صورت امکان نتیجه درخواست رو به ایمیل بنده به آدرس زیر ارسال کنید 
Reza.ghorbani273@gmail.com
> 

> 

>

**Comment by z-amini** [comment]
با سلام.

📢 افزوده شدن مستندات برداشت به API نوبیتکس

توضیحات مرتبط با کار با درخواست‌های برداشت به سایت مستندات API نوبیتکس اضافه شده است. با استفاده از Endpoint های زیر می‌توانید اقدامات مربوطه را به صورت خودکار انجام دهید:

✅ مشاهده فهرست درخواست‌های برداشت حساب خود
✅ پیگیری وضعیت یک درخواست برداشت
✅ ثبت و تایید درخواست برداشت جدید
⚡️ پشتیبانی از شبکه لایتنینگ

➡️ https://apidocs.nobitex.ir/#withdraw

🔶 لازم به توضیح است که برای تایید درخواست برداشت‌های ثبت شده از سمت API باید کد تایید ارسال شده به ایمیل خود را داشته باشید. برای مثال می‌توانید کد تایید را با اتصال برنامه خود به ایمیل حساب‌تان با پروتکل IMAP دریافت کنید. به زودی امکاناتی مانند آدرس‌بوک و لیست سفید آی‌پی از سمت نوبیتکس برای تسهیل فرآیند ثبت برداشت از طریق API فراهم خواهد شد.

**Comment by Rezaaaagg05** [comment]
سلام مجدد
 ممنون از پیگیری سریعتون و اضافه کردن این امکان به ای پی آی! 
 لطف می کنید زمان تقریبی اضافه شدن امکانات بیشتر نظیر آدرس بوک و لیست سفید رو اعلام کنید تا ببینم نیاز به کار روی پروتکل آی مپ هست یا نه؟
 اگر زمان نسبتا طولانی است که روی این پروتکل کار کنم.

**Comment by z-amini** [comment]
با سلام و عرض احترام.

 .برای امکان‌هایی که فرمودید، نمیشه زمان مشخصی تعیین و اعلام کرد. تعیین برنامه دقیق انتشار امکانات به اولویت های فنی نوبیتکس بستگی داره
اما میزان تقاضای کاربران در تسریع اون‌ها تاثیر مهمی داره. ما پیشنهاداتتون رو به تیم فنی انتقال میدیم.

ممنون که با ما همراه هستید.
