### ISSUE TITLE
اررور کپچا

### ISSUE THREAD

**Issue by sina8013** [nobitex/docs-api#101]
داخل مقدار capcha رو چی باید بزارم؟؟

من نمیدونم چی باید بزارم ئ اررور زیر رو میده:

{
    "non_field_errors": [
        "Invalid Captcha"
    ],
    "code": "InvalidCaptcha"
}

**Comment by masoudelahi** [comment]
captcha: 'api'

**Comment by z-amini** [comment]
با سلام.

@sina8013 
اگر جواب سوالتون رو گرفتید، این مورد رو می‌بندم.

توضیحات دقیق این فیلد رو می‌تونید توی [مستندات ورود](https://apidocs.nobitex.ir/#login) مشاهده کنید.

با تشکر.

**Comment by z-amini** [comment]
Duplicate of #73 
Duplicate of #92

**Comment by z-amini** [comment]
Duplicate of #92

**Comment by z-amini** [comment]
با سلام و احترام.

جهت جمع بندی نهایی: مقدار captcha طبق مستندات باید برابر api باشه.

با آرزوی موفقیت
