### ISSUE TITLE
پیشنهاد جهت اضافه شدن قابلیت جدید

### ISSUE THREAD

**Issue by powerd3v** [nobitex/docs-api#102]
سلام خدمت شما
من یک ایده ای برای استفاده بهتر از وبسرویس دارم
به نظرم بر روی هر ریکوست یک **هدر بولین** از نوع **تست نت** هم بگیرین
که برنامه نویسان بتونن توی فضای تستی وبسرویس رو اجرا کنن و نتایج رو ببینند.
اینجوری در صورت مشکلات کد نویسی در اول راه برنامه نویس ها ضرر نخواهند کرد
و میتونن کامل همه چیز رو به صورت کاملا تست شده در فضای سند باکسی انجام بدن
و در آخر برای انجام روی معاملات واقعی حالت سند باکس رو غیر فعال کنن
با تشکر فراوان از شما

**Comment by z-amini** [comment]
با سلام و عرض ادب.

آیا شما [مستندات نحوه فعالسازی تست‌نت نوبیتکس](https://apidocs.nobitex.ir/#api-2 "آیا نوبیتکس محیط آزمایشی (Test) دارد؟") را مطالعه کرده‌اید؟

شما می‌توانید با آدرس تست‌نت نوبیتکس معاملات خود را در فضای آزمایشی انجام دهید.

با احترام

**Comment by powerd3v** [comment]
منظورتون اینه که یک هدر pro بزارم و مقدارش رو برابر با yes قرار بدم مانند
عکس پیوست شده؟!

در تاریخ شنبه ۱۸ دسامبر ۲۰۲۱،‏ ۱۴:۰۴ Zeynab Amini ***@***.***>
نوشت:

**Comment by z-amini** [comment]
خیر. نحوه استفاده تست‌نت به این صورت است که شما در آدرس testnet.nobitex.ir حساب کاربری ایجاد می‌نمایید و با درگاه غیرواقعی بانکی در آن واریز به حساب کاذب انجام می‌دهید و سپس با testnetapi.nobitex.ir همان فراخوانی‌هایی را که به سرور اصلی نوبیتکس ممکن است، در سرور آزمایشی انجام می‌دهید.
در پایان با تغییر آدرس‌ها به سرور اصلی کد شما در سرور اصلی اجرا خواهد شد.

لطفا مستندات مربوط به [استفاده از تست‌نت نوبیتکس](https://apidocs.nobitex.ir/#api-2 "آیا نوبیتکس محیط آزمایشی (Test) دارد؟") را در بخش سوالات متداول مطالعه فرمایید.

**Comment by powerd3v** [comment]
متوجه شدم درواقع base url تغییر میکند
از شما متچکرم

در تاریخ یکشنبه ۱۹ دسامبر ۲۰۲۱،‏ ۹:۳۲ Zeynab Amini ***@***.***>
نوشت:
