### ISSUE TITLE
تولید لایبرری سی شارپ از api نوبیتکس

### ISSUE THREAD

**Issue by powerd3v** [nobitex/docs-api#104]
سلام و درود خدمت شما
من امیرحسین نورزی هستم و با استفاده از داکیومنت های شما و خدمات وبسرویس نوبیتکس یک لایبرری برای زبان سی شارپ ساختم.
خوشحال میشم برسی کنید و در صورت صلاح دید با هم یک مکالمه داشته باشیم این یک پیشنهاد برای api اوپن سورس سی شارپ هست 

لینک پروژه:
https://github.com/powerd3v/NobitexAPI.Sharp
پکیج ناگت:
https://www.nuget.org/packages/NobitexAPI.Sharp/1.0.0
نمونه نرم افزار آزمایشی ساخته شده توسط این لایبرری:
https://www.aparat.com/v/kxyYa/

**Comment by z-amini** [comment]
با سلام و ادب.

آشنایی با شما مایه خوش‌وقتی ما بوده.
از تلاش شما بسیار متشکریم. اما نوبیتکس در مقطع فعلی برنامه‌ای برای ارائه کتابخانه استفاده از APIها مبتنی بر stack های به خصوص رو نداره و بنا داره به طور متمرکز بر ارائه API وب قابل استفاده در انواع پلتفرم‌ها و ارتقاء اون API فعالیت کنه.
اما شما می‌تونید به طور داوطلبانه این کتابخونه رو در دسترس علاقه‌مندانش قرار بدید.

از این که همراه ما هستنید متشکریم.

روزتون بخیر.
