### ISSUE TITLE
[پشتیبانی]: انتقال به ولت دیگری

### ISSUE THREAD

**Issue by vahidalvandi** [nobitex/docs-api#106]
### هدف

من میخوام از طرف سایت شخصیم با کمک ای پی ای نوبیتکس مقداری تتر از ولت خودم به ولت شخص دیگری انتفال دهم لطفا راهنمایی بفرمایید

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

Php

### پاسخ دریافتی

..

### اطلاعات تکمیلی

سلام 
ما میتونیم    عملیات انتقال ولت به ولت را با api انجام دهیم ؟

**Comment by z-amini** [comment]
سلام و عرض ادب.

شما می‌تونین از [API برداشت](https://apidocs.nobitex.ir/#withdraw) برای منظور خودتون استفاده بکنین.
برای برداشت باید درخواستتون احراز هویت شده باشه. پس همچنین بخش [احراز هویت](https://apidocs.nobitex.ir/#auth) و سایر بخش‌های پیش‌نیاز و مشترک مستندات رو حتما بخونید.

نمونه کدهای نحوه ارسال درخواست از طریق Php رو می تونید از [کالکشن postman](https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest) نوبیتکس پیدا کنید. کافیه توی بخش language زبان Php و کتابخونه مدنظر خودتون رو انتخاب کنید.

اگر کمک دیگه‌ای از دستمون برمیاد، خوشحال می‌شیم انجام بدیم.
روزتون بخیر.

**Comment by vahidalvandi** [comment]
برای برداشت گفتید ؛برای برداشت باید درخواستتون احراز هویت شده باشه؛
منظورتون چیه ؟ من میخوام به یک آدرس ولت مثلا ۱۰۰ تتر در شبکه ترون انتقال
بدم آیا بعد از ارسال api برداشت باید کار دیگه ای هم بکنم ؟

**Comment by z-amini** [comment]
سلام مجدد.

برای نحوه احراز هویت لینک مستندات در جواب قبلی ضمیمه شده. اون رو مطالعه بفرمایید.
به صورت کلی شما باید از طریق api «ورود - دریافت توکن» یک توکن دریافت کنید و در هدر درخواست‌های بعدی تون اون توکن رو ضمیمه کنید.
سپس برای برداشت باید ابتدا api «ثبت درخواست برداشت» رو فراخوانی کنید و اطلاعات انتقال موجودی مد نظرتون رو مطابق مستندات ارسال کنید.
پس از ثبت درخواست یه کد یکبار مصرف بهتون ایمیل میشه که باید با api «تایید درخواست برداشت» اون رو وارد کنید تا برداشتتون وارد وضعیت تایید شده بشه و آماده انتقال توسط نوبیتکس.
در اینجا باید صبر کنین تا انتقال کامل بشه. می‌تونین حین انتظار، وضعیت درخواستتون رو از طریق api «مشاهده برداشت» رصد کنید.
لطفا مستندات این بخش ها رو دقیق بخونید و برای هر بخش مطابق توضیحات عمل کنید.

 سپاس.
