### ISSUE TITLE
[خطا]: مشکل در ارائه داده های دقیق برای تاریخهای مورد نظر و همینطور مشکل به  روز نبودن تعداد ارزها در api 

### ISSUE THREAD

**Issue by hossain93** [nobitex/docs-api#107]
### شرح خطا

سلام 
من داده ها را بین دو تاریخ

fromdate  =  '20/01/2021'
todate    =  '18/02/2022'
از طریق api و با ohlc میخوام بگیرم  اما تاریخ شروع دو روز عقب برام میده و همین طور تاریخ پایان یک روز عقبتر داده ها شو میده.
اینو برای سه روز من امتحان کردم و این مشکل داشت
برای یک روز هم همینطوره و داده های امروز اصلا نمیده

در زمینه گرفتن ارزهایی که داخل صرافی معامله میشه هم کار کنید چون همون ارزها رو با api نشون نمیده

همچنین گاهی اوقات که میخوام بین دو تاریخ داده هاشو بدست بیارم فقط 30 تا کندل بهم میده. مثل تاریخ زیر
fromdate  =  '1/01/2022'
todate    =  '19/02/2022'
### جزئیات درخواست

1. آدرس:
. url = "https://api.nobitex.ir/market/udf/history?symbol
. url = "https://api.nobitex.ir/v2/orderbook/all"
2. داده:
    - key1: value1
    - key2: value2
    - ...
3. هدر:
    - Authorization: yes
    - ...
4. محیط:

    - اصلی

### پاسخ دریافتی

پاسخی دریافت نشده

### پاسخ مورد انتظار

باید داده های امروز داده بشه

تعداد ارزها در api و خود سایت همگام سازی بشه

**Comment by z-amini** [comment]
سلام.

گزارش خطای شما بررسی و تایید شد. به دلیل تغییراتی که به زودی در بخش نمودار خواهیم داشت، اصلاح این خطا  در برنامه بهار ۱۴۰۱ قرار گرفته.
تغییرات صورت گرفته در نمودار OHLC در کنار انتشار درصفحه مستندات، ذیل همین مورد هم به شما اطلاع رسانی خواهد شد.

برای مورد دوم سوال شده، یعنی دریافت ارزهای صرافی، بفرمایید از چه endpoint ای استفاده می‌کنید؟ چه جوابی دریافت می‌کنید و جواب دریافتی تون چه کاستی‌هایی داره؟ (سعی کنید مطابق قالب تهیه شده اطلاعات رو بهمون بدید و موارد جدا از هم رو جداگانه issue کنید تا بشه بهتر بهشون رسیدگی کرد.)

از همراهی شما سپاس‌گزاریم.

**Comment by z-amini** [comment]
سلام.
نسخه جدید نمودار OHCL نوبیتکس با پشتیبانی از کندل‌های دقیقه‌ای و رفع خطاهای گزارش شده مدتی‌ست که منتشر شده و در اختیار کاربران قرار گرفته.
می‌تونید رفع شدن موارد گزارش شده تون رو شخصا بررسی بفرمایید.

با تشکر
