### ISSUE TITLE
خروج از "Crypto Technology Holdings Limited"

### ISSUE THREAD

**Issue by fatemehramezanli** [nobitex/docs-api#108]
https://play.google.com/store/apps/dev?id=7437982941245696477

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.

متوجه مشکل شما نشدیم.
ممکنه بیشتر توضیح بدید چه مشکلی براتون پیش اومده؟

با سپاس.

**Comment by z-amini** [comment]
با سلام.

چون مورد گزارش شده توضیحات لازم رو نداره و تکمیل نشده، مورد رو می‌بندم.
هر زمان تمایل داشتید پیگیری بیشتری روش انجام بشه، توضیحات لازمش رو درج بفرمایید و دوباره بازش کنید.

خیلی ممنون.
