### ISSUE TITLE
[پیشنهاد]: اضافه شدن پارامترهای شروع و پایان بازه زمانی به لیست واریز و برداشت

### ISSUE THREAD

**Issue by armin-mohammadi** [nobitex/docs-api#110]
### نیازمندی

برای دریافت گزارش واریزها و برداشت‌های گذشته نیاز به وجود این پارامترها وجود دارد

### راه‌حل

با اضافه کردن این پارامترها می‌توان هر بازه‌ای از گزارش را دریافت کرد

### امکانات مشابه

https://binance-docs.github.io/apidocs/spot/en/#deposit-history-supporting-network-user_data

**Comment by mheidarian** [comment]
سلام و احترام
این امکان به هر دو api مربوطه ( فهرست [برداشت](https://apidocs.nobitex.ir/#withdraw-list) و [واریز](https://apidocs.nobitex.ir/#18a62645f3)) افزوده شده است. 
اطلاعات مربوط به نحوه تعیین بازه زمانی را نیز از [اینجا](https://apidocs.nobitex.ir/#date-filter) میتوانید مطالعه فرمایید.
