### ISSUE TITLE
 websocket [پیشنهاد]: 

### ISSUE THREAD

**Issue by iuwa** [nobitex/docs-api#111]
### نیازمندی

جهت دریافت پیوسته اطلاعات مثل اردر بوک .

### راه‌حل

طراحی وب سوکت برای اردر هایی مثل اردربوک 

### امکانات مشابه

صرافی های دیگر این امکان را دارن

### توضیح تکمیلی

من وب سوکت رو در مستندات پیدا نکردم. اگر وجود دارد راهنمایی کنید.

**Comment by z-amini** [comment]
Duplicate of #91

**Comment by z-amini** [comment]
با سلام و ادب و احترام.

ارائه وب سوکت با توجه به حجم کاربران نوبیتکس، ملاحظات فنی زیادی داره که موازی با سایر فیچرهای در دست توسعه ما در حال بررسی و پیگیریه.
به همین دلیل در حال حاضراین کار _در برنامه آینده نزدیک نوبیتکس نیست._
شما برای حفظ پیوستگی می‌تونین از API call های منظم با فواصل معقول استفاده کنین.
پیشنهاد می‌کنیم برای محاسبه فاصله ها از پارامتر lastUpdate هر بازار و محدودیت درخواست هر بات متصل شونده استفاده کنین.

از صبر و همراهی شما متشکریم.

**Comment by shakibaei65** [comment]
سلام مگه امکان داره که نوبیتیکس بزاره که یه هموطنش از این برنامها به بازارش وصل شه که بتونیم منابع و کدهای منبع بازو ازشون استفاده کنیم نه نمیزارن اوایل که با پستچی ایپی هاشو تنظیم میکردیم همه چنان مسایلو در هم و پیچیده کردن که  ادم از ایرانی بودنش شرمش میاد

**Comment by itismoej** [comment]
سلام و وقت‌بخیر؛
اخیراً زیرساخت وب‌سوکت رو اضافه کردیم و فعلاً لیست اردربوک رو می‌تونید از وب‌سوکت دریافت کنید: https://apidocs.nobitex.ir/#websocket

**Comment by itismoej** [comment]
سلام و وقت‌بخیر؛
اخیراً زیرساخت وب‌سوکت رو اضافه کردیم و فعلاً لیست اردربوک رو می‌تونید از وب‌سوکت دریافت کنید: https://apidocs.nobitex.ir/#websocket
