### ISSUE TITLE
[پشتیبانی]: خطای InvalidOTP در هنگام لاگین

### ISSUE THREAD

**Issue by eisensteinb** [nobitex/docs-api#135]
### هدف

امکانش هست توضیح بدید چجوری میتونیم به صورت خودکار X_TOTP تولید کنیم؟ تو مستنداتون هیچ توضیحی ندادین فقط نوشتین امکان تولیدش «با استفاده از فرمول استانداردی در کد» امکان‌پذیره. ممنون میشم در این مورد توضیحات بدید. هر چی تلاش میکنم نمیتونم لاگین کنم از طریق بات. 

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

```
url = 'https://api.nobitex.ir/auth/login/'
headers = {
    'Content-Type': 'application/json',
    'User-Agent': 'TraderBot/Testing2234',
    'X-TOTP': 'code'
}
body = {
    'username': "username",
    'password': "password",
    'remember': 'yes',
    'captcha': 'api'
}
response = requests.post(url, headers=headers, data=body)

### پاسخ دریافتی

```
{
    "non_field_errors": [
        "Invalid OTP"
    ],
    "code": "InvalidOTP"
}

**Comment by mheidarian** [comment]
سلام 
برای تولید کد otp شما باید با استفاده از استاندارد RFC 6238 برنامه تولید این کد رو بسازید و ازش استفاده کنید. 
در واقع برنامه Google Authenticator هم از همین الگوریتم به اضافه اون Secret Key داره استفاده میکنه و براتون کد تولید میکنه.
شاید [این جواب](https://stackoverflow.com/a/7990725/2762153) بتونه بیشتر کمکتون کنه.

این هم یک [کد ساده جاوااسکریپتی](http://blog.tinisles.com/2011/10/google-authenticator-one-time-password-algorithm-in-javascript/) هست که اینکارو کرده

**Comment by eisensteinb** [comment]
ممونم.
