### ISSUE TITLE
CSRF Error

### ISSUE THREAD

**Issue by HamidBaghernia** [nobitex/docs-api#15]
Hi.
I'm encountering the following error when sending login request:

"detail": "CSRF Failed: Referer checking failed - no Referer."

Can you please examine the issue or suggest how to deal with it?
Thank you?

**Comment by moeinkarimi1984** [comment]
Hi
one solution is clear cookie
more description [here ](https://stackoverflow.com/questions/26639169/csrf-failed-csrf-token-missing-or-incorrect)

**Comment by Nilufargh** [comment]
I used postman!and I get the same error!could you please guide me more clearly.

**Comment by mheidarian** [comment]
Hello. 
Note, you must send your request with Iranian IPs. 
This may be the cause of your problem. I tried and there is no problem.
You can also use Nobitex postman collection from [here](https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest).

**Comment by arashaliloo** [comment]
curl 'https://api.nobitex.ir/market/orders/add' \ -X POST \ -H "Authorization: 4df218de04ed952934cda6e28d3034db7cbc74bb" \ -H "content-type: application/json" \ --data '{"type":"buy","srcCurrency":"btc","dstCurrency":"rls","amount":"0.6","price":520000000}'60","isWatchingDisabled":true,"watching":[],"watchingChannels":[],"createdTime":1658390679254,"updatedTime":1659483927584}]},"userInfo":{},"userTxs":{"items":[]}}
