### ISSUE TITLE
[پیشنهاد]: تصحیح تابع orderbook

### ISSUE THREAD

**Issue by moradi2021** [nobitex/docs-api#150]
### نیازمندی

متاسفانه در خروجی تابع v2/orderbook/SYMBOL پیشنهادهای صف خرید با عنوان asks نامگذاری شده است و پیشنهادهای صف فروش با نام bids در حالی که این نامگذاری دقیقا برعکس تعاریف بازارهای مالی است. چنین اشتباه فاحشی در شان نوبیتکس نیست.

### راه‌حل

درتابع v2/orderbook/SYMBOL انتساب صف پیشنهادهای خرید به عنوان bids و انتساب صف پیشنهادهای فروش به عنوان asks صورت گیرد.

### امکانات مشابه

در تمامی صرافی های معتبر در orderbook ، صف پیشنهادهای خرید با عنوان bids و صف پیشنهادهای فروش با عنوان asks مطرح میشود.

### توضیح تکمیلی

با تشکر از شما

**Comment by mheidarian** [comment]
سلام

جابجایی دو کلمه bids و asks در API اردربوک سهوی رخ داده و اصلاحش در برنامه ما هست، اما به دلایل compatibility با تعویق روبرو شده. در صورت رفع بهتون اطلاع میدیم.

Duplicate of #22
