### ISSUE TITLE
API Limitations

### ISSUE THREAD

**Issue by babakgholamirad** [nobitex/docs-api#16]
Hello I wanted to start making an app based on your API's to handle my transactions in nobitex. but i didn't find API limitation in the docs.is there any?

**Comment by mheidarian** [comment]
Hello
Yes, there are restrictions that you can read about it in the General notes section (ملاحظات عمومی > محدودیت ها) from [here](https://apidocs.nobitex.ir/)
Some limitations are also mentioned in the description of that api.
