### ISSUE TITLE
[پشتیبانی]: اضافه کردن سفارش سریع

### ISSUE THREAD

**Issue by SajjadNaghshineh** [nobitex/docs-api#161]
### نیازمندی

من برای ایجاد سفارش سریع نیاز به API دارم ولی هرچی داخل مستندات API هاتون گشتم موردی در ارتباط با سفارش سریع پیدا نکردم.
ممنون میشم اگر این مورد هم اضافه کنید.

### راه‌حل

اضافه کردن یک API جهت خرید یا فروش .

**Comment by z-amini** [comment]
سلام.
وقت شما بخیر.

سفارش سریع همون سفارش با قیمت بازار یا Market Order هست که توی مستندات منوی [معامله در بازار > ثبت سفارش جدید](https://apidocs.nobitex.ir/#e12b63a512) با نوع اجرای سفارش execution=market معرفی شده.
مثال‌های بیشتر از انواع اجرای سفارش توی[ کالکشن Postman](https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest#e28bf59d-c89b-4e83-adf7-3646b55366ed) نوبیتکس قابل مشاهده است.
