### ISSUE TITLE
[پیشنهاد]: دریافت لیست معاملات عمومی همه بازارها

### ISSUE THREAD

**Issue by IYP-Programer-Yeah** [nobitex/docs-api#164]
### نیازمندی

دریافت public trade برای همه‌ی book ها. در صورت دریافت تک به تک به محدودیت تعداد درخواست برخورد می‌کنیم.

### راه‌حل

ایجاد امکان استفاده از all به جای اسم symbol ها در API مربوط به trades/.

### امکانات مشابه

استفاده از all در API دریافت order book.

### توضیح تکمیلی

در حال حاضر برای دریافت لیست عمومی معاملات در تمامی symbolها باید برای هر symbol یک در خواست فرستاده شود که با توجه به محدودیت درخواست راه حل مناسبی نیست.

**Comment by z-amini** [comment]
سلام.
وقت شما بخیر.

چنین چیزی توی API نوبیتکس خیلی وقته که وجود داشته.
https://api.nobitex.ir/v2/orderbook/all
توی مستندات عمومی API هم می‌تونید در [منوی اطلاعات بازار (عمومی) > لیست سفارش‌ها: اردربوک](https://apidocs.nobitex.ir/#orderbook) جزئیات بیشتری ببینید.

**Comment by IYP-Programer-Yeah** [comment]
نوضیحات به تکمیل و دقیق‌تر شد.

**Comment by z-amini** [comment]
بله، متوجه پیشنهاد شما شدیم.
منتقل می‌کنم که مورد بررسی تیم فنی قرار بگیره.
خیلی از پیشنهاد شما ممنونیم.
