### ISSUE TITLE
[پشتیبانی]: دریافت خطای ConnectTimeoutError در اردربوک

### ISSUE THREAD

**Issue by msourani** [nobitex/docs-api#172]
### هدف

دریافت لیست سفارش‌ها یا همان اردربوک

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...
Python

### نحوه درخواست

import requests

url = "https://api.nobitex.ir/v2/orderbook"
symbol = "BTCIRT"
response = requests.get(f"{url}/{symbol}", timeout=100)
data = response.json()
print(data)

### پاسخ دریافتی

HTTPSConnectionPool(host='api.nobitex.ir', port=443): Max retries exceeded with url: /v2/orderbook/BTCIRT (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7d42f41a1450>, 'Connection to api.nobitex.ir timed out. (connect timeout=100)'))

**Comment by rbabaee** [comment]
سلام. اگر هنوز این مورد رو دریافت میکنید، لطفا curl درخواست رو بفرستید.

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.

خطاهای ConnectTimeoutError گاهی به خاطر مشکلات زیرساختی اینترنت به وجود میان. می‌تونید زمان دقیق دریافت این خطا رو بدید ما توی لاگ‌هامون بررسی کنیم.
ولی این امکان هم هست که سرویس دهنده اینترنت شما تو اون بازه دچار اختلال لحظه‌ای شده باشه.
الان که مشکلی در اتصال ندارید؟
https://api.nobitex.ir/v2/orderbook/BTCIRT
