### ISSUE TITLE
[پشتیبانی]: راهنمایی در خصوص withdraw

### ISSUE THREAD

**Issue by navid-ahrary** [nobitex/docs-api#175]
### هدف

برای برداشت از حساب،‌چه بصورت ریالی و چه ارزی از طریق API  نیاز به راهنمایی داریم

### محیط درخواست

- ابزار درخواست POSTMAN
- زبان برنامه CURL
- محل درخواست local محیط توسعه
- درخواست IP داخلی

### نحوه درخواست

```
curl --location --request GET 'https://api.nobitex.ir/users/wallets/withdraw' \
--header 'X-TOTP: 417326' \
--header 'Authorization: Token 2daa..........' \
--header 'Cookie: csrftoken=OvePA5UGTxJZYQ97F7bwnx6Xegb8P2x0H3hZMYd0WivXAZa5IxPo3sYVDWufKvNa; sessionid=un9uwvrp0ghd8vqaugvu722ytfor27bf' \
--form 'wallet="99260538"' \
--form 'amount="1000000"' \
--form 'address="4021325"'
```

### پاسخ دریافتی

```
{
"message": "No Wallet matches the given query.",
"error": "NotFound"
}

```

### اطلاعات تکمیلی

برای برداشت withdraw نیاز به راهنمایی داریم. ما wallet_id رو از /v2/wallets?currencies دریافت کردیم و همراه با withdraw api در پارامتر wallet ارسال کردیم اما خطای NotFound برمیگرده. ممنونم میشم راهنمایی بفرمایید

ضمنن قبلن این درخواست رو بصورت تیکیت از طریق وبسایت نوبیتکس ثبت کردیم. پشتیانی گفتند که برای چنین مشکلاتی اینجا محل مناسبتریه.

سپاسگذارم

**Comment by rbabaee** [comment]
سلام. 
لطفا به جای استفاده از --form
با raw_data دیتا رو ارسال کنید. 

```bash
--data-raw '{"wallet":99260538,"address":4021325,"amount":1000000}'
```

**Comment by rbabaee** [comment]
کوکی و سشن آی دی رو چرا پاس میدید ؟

**Comment by navid-ahrary** [comment]
> کوکی و سشن آی دی رو چرا پاس میدید ؟
> 
> البته به ایشویی که گزارش کردید مرتبط نیست، ولی نیازی به پاس دادنشون نیست.

من از این داکیومنت استفاده میکنم که خودش این اطلاعات رو گذاشته.
https://documenter.getpostman.com/view/5722122/Szmcayjw#8f23dbb6-4899-4b64-9ee1-ac7024e7944d
واسه خود postman ه که فک نمیکنم فرستادن یا نفرستادنش مهم باشه .
درنهایت توی پیاده سازی سمت backend حذفشون

**Comment by navid-ahrary** [comment]
> سلام. لطفا به جای استفاده از --form با raw_data دیتا رو ارسال کنید.
> 
> ```shell
> --data-raw '{"wallet":99260538,"address":4021325,"amount":1000000}'
> ```

بقیه دیتا رو هم بصورت raw ارسال کنم؟

**Comment by navid-ahrary** [comment]
> --data-raw '{"wallet":99260538,"address":4021325,"amount":

تو داکیومنت [postman](https://documenter.getpostman.com/view/5722122/Szmcayjw#8f23dbb6-4899-4b64-9ee1-ac7024e7944d) دیتا رو بصورت param ارسال کرده.
اگه نیاز هست اونجا رو هم اصلاح کنید

**Comment by navid-ahrary** [comment]
> سلام. لطفا به جای استفاده از --form با raw_data دیتا رو ارسال کنید.
> 
> ```shell
> --data-raw '{"wallet":99260538,"address":4021325,"amount":1000000}'
> ```
عزیزم، --data-raw اصن سوییچی نیست که curl پشتیبانی کنه!
با این حال زدم همچنان مشکل داره


curl --location --request GET 'https://api.nobitex.ir/users/wallets/withdraw' \
--header 'X-TOTP;' \
--header 'Authorization: Token 2daa........' \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=HHChbsv1jRhGVRa85fIZvrNL1pUWNXO0SADCGXdZivEsUsBABVGYPyS7chlMkMcy; sessionid=6jr5n7l17aqs78geriw0ixp6w5o2tdx5' \
--data-raw '{"wallet":99260538,"address":4021325,"amount":1000000}
'
`{"message": "No Wallet matches the given query.", "error": "NotFound"}`

شما فرض کن من میخام با axios این درخواست رو بزنم اونجا چیکار کنم؟

**Comment by rbabaee** [comment]
این ارور رو وقتی میگیرید که آی دی ولت ، اشتباه باشه یا به هر صورتی، آی دی ولت درست ارسال نشه. 
آی دی ولتتون رو چک میکنید که مال همون کاربر توکنتون باشه؟ 
https://api.nobitex.ir/users/wallets/list?type=spot
[لیست ولت](https://apidocs.nobitex.ir/#e2ecdd60d4:~:text=%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA%20%D9%85%D8%A7%D9%84%DB%8C%20%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1-,%D9%84%DB%8C%D8%B3%D8%AA%20%DA%A9%DB%8C%D9%81%20%D9%BE%D9%88%D9%84%20%D9%87%D8%A7,-curl%20%27https%3A//api) رو بگیرید و چک کنید. 

برای ای پی آی برداشت هم این لینک رو چک کنید 
https://apidocs.nobitex.ir/#withdraw

**Comment by navid-ahrary** [comment]
> این ارور رو وقتی میگیرید که آی دی ولت ، اشتباه باشه یا به هر صورتی، آی دی ولت درست ارسال نشه. آی دی ولتتون رو چک میکنید که مال همون کاربر توکنتون باشه؟ https://api.nobitex.ir/users/wallets/list?type=spot [لیست ولت](https://apidocs.nobitex.ir/#e2ecdd60d4:~:text=%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA%20%D9%85%D8%A7%D9%84%DB%8C%20%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1-,%D9%84%DB%8C%D8%B3%D8%AA%20%DA%A9%DB%8C%D9%81%20%D9%BE%D9%88%D9%84%20%D9%87%D8%A7,-curl%20%27https%3A//api) رو بگیرید و چک کنید.
> 
> برای ای پی آی برداشت هم این لینک رو چک کنید https://apidocs.nobitex.ir/#withdraw

این walletId رو از ای پی آي گرفتم، همچنان خطا وجود داره.
درخواست مد نظرم برای برداشت ریالی ه. آیا چیزی رو دارم جا میندازم؟

**Comment by mheidarian** [comment]
> > این ارور رو وقتی میگیرید که آی دی ولت ، اشتباه باشه یا به هر صورتی، آی دی ولت درست ارسال نشه. آی دی ولتتون رو چک میکنید که مال همون کاربر توکنتون باشه؟ https://api.nobitex.ir/users/wallets/list?type=spot [لیست ولت](https://apidocs.nobitex.ir/#e2ecdd60d4:~:text=%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA%20%D9%85%D8%A7%D9%84%DB%8C%20%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1-,%D9%84%DB%8C%D8%B3%D8%AA%20%DA%A9%DB%8C%D9%81%20%D9%BE%D9%88%D9%84%20%D9%87%D8%A7,-curl%20%27https%3A//api) رو بگیرید و چک کنید.
> > برای ای پی آی برداشت هم این لینک رو چک کنید https://apidocs.nobitex.ir/#withdraw
> 
> اون walletId رو از ای پی آي گرفته بودم و همچنان خطا وجود داره. درخواست مد نظرم برای برداشت ریالی به حساب جیبیته. آیا چیزی رو دارم جا میندازم؟ حتا network رو هم گذاشتم بی تاثیر بود
> 
> body:
> 
> ```
> {
>     "network": "FIAT_MONEY",
>     "wallet": 99260538,
>     "address": "9900080546020153",
>     "amount": 100000
> }
> ```

سلام . امکانش هست جزئیات درخواستی رو که ولت ها رو گرفتید هم بفرستید؟

**Comment by navid-ahrary** [comment]
```
{
    "status": "ok",
    "wallets": [
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "FIAT_MONEY": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260538,
            "currency": "rls",
            "balance": "2417.87002456",
            "blockedBalance": "0",
            "activeBalance": "2417.87002456",
            "rialBalance": 2417,
            "rialBalanceSell": 2417
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "BTC-LEGACY": {
                    "address": null,
                    "tag": null
                },
                "BTC": {
                    "address": null,
                    "tag": null
                },
                "BTCLN": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260539,
            "currency": "btc",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
            "depositTag": null,
            "depositInfo": {
                "WETH-ETH": {
                    "address": null,
                    "tag": null
                },
                "ETH": {
                    "address": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
                    "tag": null
                },
                "WETH-ARB": {
                    "address": null,
                    "tag": null
                },
                "ARB": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260540,
            "currency": "eth",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "LTC": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260541,
            "currency": "ltc",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
            "depositTag": null,
            "depositInfo": {
                "TRX": {
                    "address": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
                    "tag": null
                },
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "MATIC": {
                    "address": null,
                    "tag": null
                },
                "ARB": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
                    "tag": null
                }
            },
            "id": 99260542,
            "currency": "usdt",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "XRP": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260543,
            "currency": "xrp",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "BCH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260544,
            "currency": "bch",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "BNB": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260545,
            "currency": "bnb",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "EOS": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260546,
            "currency": "eos",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "XLM": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260547,
            "currency": "xlm",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETC": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260548,
            "currency": "etc",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
            "depositTag": null,
            "depositInfo": {
                "TRX": {
                    "address": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260549,
            "currency": "trx",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "PMN": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260550,
            "currency": "pmn",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "DOGE": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260551,
            "currency": "doge",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260552,
            "currency": "uni",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "MATIC": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260553,
            "currency": "dai",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260554,
            "currency": "link",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "DOT": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260555,
            "currency": "dot",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260556,
            "currency": "aave",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ADA": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260557,
            "currency": "ada",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260558,
            "currency": "shib",
            "balance": "50",
            "blockedBalance": "0",
            "activeBalance": "50",
            "rialBalance": 183050,
            "rialBalanceSell": 183500
        },
        {
            "depositAddress": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
                    "tag": null
                }
            },
            "id": 101381854,
            "currency": "wld",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        }
    ]
}
```

**Comment by navid-ahrary** [comment]
> > > این ارور رو وقتی میگیرید که آی دی ولت ، اشتباه باشه یا به هر صورتی، آی دی ولت درست ارسال نشه. آی دی ولتتون رو چک میکنید که مال همون کاربر توکنتون باشه؟ https://api.nobitex.ir/users/wallets/list?type=spot [لیست ولت](https://apidocs.nobitex.ir/#e2ecdd60d4:~:text=%D8%A7%D8%B7%D9%84%D8%A7%D8%B9%D8%A7%D8%AA%20%D9%85%D8%A7%D9%84%DB%8C%20%DA%A9%D8%A7%D8%B1%D8%A8%D8%B1-,%D9%84%DB%8C%D8%B3%D8%AA%20%DA%A9%DB%8C%D9%81%20%D9%BE%D9%88%D9%84%20%D9%87%D8%A7,-curl%20%27https%3A//api) رو بگیرید و چک کنید.
> > > برای ای پی آی برداشت هم این لینک رو چک کنید https://apidocs.nobitex.ir/#withdraw
> > 
> > 
> > اون walletId رو از ای پی آي گرفته بودم و همچنان خطا وجود داره. درخواست مد نظرم برای برداشت ریالی به حساب جیبیته. آیا چیزی رو دارم جا میندازم؟ حتا network رو هم گذاشتم بی تاثیر بود
> > body:
> > ```
> > {
> >     "network": "FIAT_MONEY",
> >     "wallet": 99260538,
> >     "address": "9900080546020153",
> >     "amount": 100000
> > }
> > ```
> 
> سلام . امکانش هست جزئیات درخواستی رو که ولت ها رو گرفتید هم بفرستید؟

{
    "status": "ok",
    "wallets": [
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "FIAT_MONEY": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260538,
            "currency": "rls",
            "balance": "2417.87002456",
            "blockedBalance": "0",
            "activeBalance": "2417.87002456",
            "rialBalance": 2417,
            "rialBalanceSell": 2417
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "BTC-LEGACY": {
                    "address": null,
                    "tag": null
                },
                "BTC": {
                    "address": null,
                    "tag": null
                },
                "BTCLN": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260539,
            "currency": "btc",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
            "depositTag": null,
            "depositInfo": {
                "WETH-ETH": {
                    "address": null,
                    "tag": null
                },
                "ETH": {
                    "address": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
                    "tag": null
                },
                "WETH-ARB": {
                    "address": null,
                    "tag": null
                },
                "ARB": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260540,
            "currency": "eth",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "LTC": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260541,
            "currency": "ltc",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
            "depositTag": null,
            "depositInfo": {
                "TRX": {
                    "address": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
                    "tag": null
                },
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "MATIC": {
                    "address": null,
                    "tag": null
                },
                "ARB": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
                    "tag": null
                }
            },
            "id": 99260542,
            "currency": "usdt",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "XRP": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260543,
            "currency": "xrp",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "BCH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260544,
            "currency": "bch",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "BNB": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260545,
            "currency": "bnb",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "EOS": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260546,
            "currency": "eos",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "XLM": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260547,
            "currency": "xlm",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETC": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260548,
            "currency": "etc",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
            "depositTag": null,
            "depositInfo": {
                "TRX": {
                    "address": "TBcMrcX23cAdmpp9VmP5thR4NxZjrcPQ39",
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260549,
            "currency": "trx",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "PMN": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260550,
            "currency": "pmn",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "DOGE": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260551,
            "currency": "doge",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260552,
            "currency": "uni",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "MATIC": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260553,
            "currency": "dai",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260554,
            "currency": "link",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "DOT": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260555,
            "currency": "dot",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260556,
            "currency": "aave",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ADA": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260557,
            "currency": "ada",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        },
        {
            "depositAddress": null,
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": null,
                    "tag": null
                },
                "BSC": {
                    "address": null,
                    "tag": null
                }
            },
            "id": 99260558,
            "currency": "shib",
            "balance": "50",
            "blockedBalance": "0",
            "activeBalance": "50",
            "rialBalance": 183050,
            "rialBalanceSell": 183500
        },
        {
            "depositAddress": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
            "depositTag": null,
            "depositInfo": {
                "ETH": {
                    "address": "0x109579fb5ad3ded5cecb56aa15ee24813c41c2f2",
                    "tag": null
                }
            },
            "id": 101381854,
            "currency": "wld",
            "balance": "0",
            "blockedBalance": "0",
            "activeBalance": "0",
            "rialBalance": 0,
            "rialBalanceSell": 0
        }
    ]
}

**Comment by navid-ahrary** [comment]
و این هم درخواست profile

```
curl --location 'https://api.nobitex.ir/users/profile' \
--header 'Authorization: Token 2daa...' \
--header 'Cookie: csrftoken=HHChbsv1jRhGVRa85fIZvrNL1pUWNXO0SADCGXdZivEsUsBABVGYPyS7chlMkMcy; sessionid=6jr5n7l17aqs78geriw0ixp6w5o2tdx5'

```

```
...
bankCards": [
            {
                "id": 5028267,
                "number": "6104-3388-0007-8293",
                "bank": "بانک ملت",
                "owner": "xxx",
                "confirmed": true,
                "status": "confirmed"
            }
        ],
        "bankAccounts": [
            {
                "id": 4012444,
                "number": "0",
                "shaba": "IR300120000000009444178837",
                "bank": "ملت",
                "owner": "xxx",
                "confirmed": true,
                "status": "confirmed"
            },
            {
                "id": 4021325,
                "number": "9900080546020153",
                "shaba": "9900080546020153",
                "bank": "جیبیت",
                "owner": "xxxx",
                "confirmed": true,
                "status": "confirmed"
            }
        ]
...
```

**Comment by mheidarian** [comment]
> و این هم درخواست profile
> 
> ```
> curl --location 'https://api.nobitex.ir/users/profile' \
> --header 'Authorization: Token 2daa...' \
> --header 'Cookie: csrftoken=HHChbsv1jRhGVRa85fIZvrNL1pUWNXO0SADCGXdZivEsUsBABVGYPyS7chlMkMcy; sessionid=6jr5n7l17aqs78geriw0ixp6w5o2tdx5'
> ```
> 
> ```
> ...
> bankCards": [
>             {
>                 "id": 5028267,
>                 "number": "6104-3388-0007-8293",
>                 "bank": "بانک ملت",
>                 "owner": "xxx",
>                 "confirmed": true,
>                 "status": "confirmed"
>             }
>         ],
>         "bankAccounts": [
>             {
>                 "id": 4012444,
>                 "number": "0",
>                 "shaba": "IR300120000000009444178837",
>                 "bank": "ملت",
>                 "owner": "xxx",
>                 "confirmed": true,
>                 "status": "confirmed"
>             },
>             {
>                 "id": 4021325,
>                 "number": "9900080546020153",
>                 "shaba": "9900080546020153",
>                 "bank": "جیبیت",
>                 "owner": "xxxx",
>                 "confirmed": true,
>                 "status": "confirmed"
>             }
>         ]
> ...
> ```

ممنون

این مدلی تست کنید. من در اینحالت جواب گرفتم. بازم اگه مشکلی بود بفرمایید تا بررسی کنیم
`curl --location 'https://testnetapi.nobitex.ir/users/wallets/withdraw' \
--header 'Authorization: Token 1fc6******' \
--header 'X-TOTP: 604349' \
--header 'Content-Type: application/json' \
--header 'Cookie: csrftoken=TUkCJ7kEqWzuhfYqokhLmQxrr6ROsBI5D1bgOsR6QAxeXu0oEjl4J4duIjTiTQM0; sessionid=nk5t2ywgukke8tfivp9dk5f1gdeowptx' \
--data '{"wallet": "2693280", "address": "36465", "amount": "5000000"}'`



و البته یه چیز دیگه
با یکی دیگه از حساب های بانکی هم امتحان کنید ببینید تفاوتی داره. 

البته که باید مطمئنا در این حالت نتیجه بگیرید و مشکلی نداشته باشید

**Comment by navid-ahrary** [comment]
متشکرم حل شد
