### ISSUE TITLE
[خطا]: درخواست بالانس  کیف پول تعهدی منجر به بازگرداندن بالانس محتویات کیف پول اسپات می گردد .

### ISSUE THREAD

**Issue by hadi-azad** [nobitex/docs-api#179]
### شرح خطا

قبل از باز کردن موقعیت لازم است که از محتویات و مقادیر ریال و دلار موجود در کیف تعهدی اطلاع حاصل گردد تا صدور فرمان .
منجر به خطای عدم موجودی نگردد
  از سمت دیگر برای انتقال بین کیف پول های تعهدی و اسپات 
 دانستن میزان موجودی کیف ضروری می باشد  .
وقتی که مقدار ریال یا دلار انتقال یافته یا ذخیره شده در کیف پول مورد سوال قرار می گیرد در هر دو صورت type = margin  یا  type = spot   خروجی یکسان برگردانده می شود که معادل کیف های پولی اسپات می باشد .
در نتیجه امکان مشخص کردن مقادیر اعتباری موجود ریالی و دلاری به وجود نمی آید .

### جزئیات درخواست

1. آدرس: "curl = "https://api.nobitex.ir/v2/wallets"

response = requests.request("GET", curl, headers=headers, data=payload)

3. داده:
        payload=
          {
            "type" : "margin"
            }
        
4. هدر:
        
        headers = {
          'Authorization': myToken
        }
5. محیط:
    - اصلی

### پاسخ دریافتی

AAVE
dict
3
{'id': 82665081, 'balance': '0', 'blocked': '0'}
ADA
dict
3
{'id': 82665082, 'balance': '0', 'blocked': '0'}
BCH
dict
3
{'id': 82665069, 'balance': '0', 'blocked': '0'}
BNB
dict
3
{'id': 82665070, 'balance': '0', 'blocked': '0'}
BTC
dict
3
{'id': 82665064, 'balance': '0.0144128973', 'blocked': '0'}
DAI
dict
3
{'id': 82665078, 'balance': '0', 'blocked': '0'}
DOGE
dict
3
{'id': 82665076, 'balance': '0', 'blocked': '0'}
DOT
dict
3
{'id': 82665080, 'balance': '0', 'blocked': '0'}
EOS
dict
3
{'id': 82665071, 'balance': '0', 'blocked': '0'}
ETC
dict
3
{'id': 82665073, 'balance': '0', 'blocked': '0'}
ETH
dict
3
{'id': 82665065, 'balance': '0', 'blocked': '0'}
LINK
dict
3
{'id': 82665079, 'balance': '0', 'blocked': '0'}
LTC
dict
3
{'id': 82665066, 'balance': '0', 'blocked': '0'}
PMN
dict
3
{'id': 82665075, 'balance': '0', 'blocked': '0'}
RLS
dict
3
{'id': 82665063, 'balance': '10687.3464186461', 'blocked': '0'}
SHIB
dict
3
{'id': 82665083, 'balance': '0', 'blocked': '0'}
TRX
dict
3
{'id': 82665074, 'balance': '0', 'blocked': '0'}
UNI
dict
3
{'id': 82665077, 'balance': '0', 'blocked': '0'}
USDT
dict
3
{'id': 82665067, 'balance': '0.002065', 'blocked': '0'}
XLM
dict
3
{'id': 82665072, 'balance': '0', 'blocked': '0'}
XRP
dict
3
{'id': 82665068, 'balance': '0', 'blocked': '0'}

### پاسخ مورد انتظار

وقتی type درخواست  margin  می باشد منتظر کیف پول های مارجین هستیم ولی پاسخ اسپات دریافت می گرد

### اطلاعات تکمیلی

اگر روش دیگری برای مشخص کردن محتویات کیف مارجین وجود دارد لطفا به صورت مشخص توضیح دهید   .
با تشکر

**Comment by z-amini** [comment]
با سلام و درود.
برای پاس دادن پارامترهای درخواست GET باید از کلیدواژه params استفاده نمایید.
به این صورت:
```python
response = requests.request("GET", curl, headers=headers, params=payload)
```

**Comment by hadi-azad** [comment]
ممنون 
استفاده نادرست من از api منجر به خطا شده بود .
تست شد . نتیجه صحیح بود .
با تشکر
