### ISSUE TITLE
[پشتیبانی]: نحوه ارسال توکن

### ISSUE THREAD

**Issue by sabzmakan** [nobitex/docs-api#183]
### هدف

کال کردن api با استفاده از توکن 

### محیط درخواست

- ابزار درخواست postman
- زبان برنامه python
- محل درخواست local

- ...

### نحوه درخواست

کالکشن پستمن نوبیتکس را دانلود و api های عمومی را ران کردم، و به درستی جواب برگرداندند
اما وقتی api های نیازمند توکن را ران میکنم، خطای زیر رو نشون میده
در حالیکه توکن خودم را از سایت نوبیتکس برداشتم و در قسمت توکن کالکشن پستمن جایگزین کردم 

### پاسخ دریافتی

{
"detail": "اطلاعات برای اعتبارسنجی ارسال نشده است."
}

**Comment by mohsenjfar** [comment]
من از ریکوئست پایتون ارسال درخواست کردم و دقیقا با همین خطا مواجه شدم، توی توضیحات API یه بخش وجود داره (اعتبارسنجی دو عاملی) که اونجا توضیح داده که اگر از اعتبارسنجی دوعاملی استفاده می کنید باید کد گوگل اوتنتیکیتور رو هم ارسال کنید، من ارسال کردم ولی کماکان این پیام خطا بازگشت می شه.

**Comment by z-amini** [comment]
سلام.
وقت شما به خیر.

به نظر می‌رسه این مسئله رو در ادامه مسئله #182 مطرح کردید. برای این که بحث‌ها یک جا جمع باشه، روی همون مورد صحبت‌ها مون رو ادامه بدیم.

خیلی ممنونم.
