### ISSUE TITLE
[پشتیبانی]: ثبت برداشت و تایید برداشت

### ISSUE THREAD

**Issue by hamidrezasaki** [nobitex/docs-api#184]
### هدف

در مورد سرویس های برداشت و تایید برداشت
اگر شناسایی دو عاملی روی اکانت فعال نباشه نیازی به ارسال توی این درخواست ها نیست؟
همینطور کد otp که پیامک میشه باید کجا توی کدوم سرویس ارسال کنیم؟
امکان داره که صرفا برای api کد پیامکی توی سرویس تایید برداشت و کد دو عاملی برای سرویس های مربوط به برداشت غیرفعال بشه؟

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

POST 'https://api.nobitex.ir/users/wallets/withdraw'
POST 'https://api.nobitex.ir/users/wallets/withdraw-confirm'

### پاسخ دریافتی

خطا نیست

**Comment by iRhonin** [comment]
> اگر شناسایی دو عاملی روی اکانت فعال نباشه نیازی به ارسال توی این درخواست ها نیست؟

بله اگر دوعاملی فعال نباشه نیازی نیست که ارسال بشه. در صورت فعال بودن فقط نیازه که در [سرویس برداشت](https://apidocs.nobitex.ir/#withdraw) ارسال بشه.  


> همینطور کد otp که پیامک میشه باید کجا توی کدوم سرویس ارسال کنیم؟

داخل payload سرویس [تایید برداشت](https://apidocs.nobitex.ir/#withdraw-confirm)، پارامتر `otp`.


> امکان داره که صرفا برای api کد پیامکی توی سرویس تایید برداشت و کد دو عاملی برای سرویس های مربوط به برداشت غیرفعال بشه؟

اگر از [دفتر آدرس و حالت برداشت امن](https://apidocs.nobitex.ir/#0622709577) استفاده کنید، برای ادرس هایی که ثبت کردید نیازی به وارد کردن این دو پارامتر نیست توی این دوتا سرویس.

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.

فعال کردن شناسایی دوعاملی کاربران سطح ۲ به بالا برای برداشت رمزارزی ضروری هست. اگر سطحتون کمتر از ۲ هست یا فقط برداشت ریالی دارید، لزومی به داشتن شناسایی دوعاملی نیست.
رمز یکبارمصرف پیامکی رو باید در اندپوینت تایید درخواست برداشت (withdraw-confirm) استفاده بکنید. این رمز همزمان به ایمیل شما هم ارسال می‌شه. کتابخونه‌هایی هستند که بهتون کمک کنن ایمیل تون رو چک کنید.
یه راه دیگه برای اجتناب از نیاز به استفاده از شناسایی دوعاملی و رمز یکبارمصرف در فرآیند برداشت رمزارزی، استفاده از فیچر دفترآدرس نوبیتکس هست. به این صورت که آدرس‌های مورد استفاده بات تون رو توی این دفترآدرس ثبت می‌کنید و بعد از اون به این مقصدها می‌تونید بدون 2fa و otp درخواست برداشت ثبت کنید و درخواست برداشتتون رو تایید هم بکنید.

امیدواریم که تونسته باشیم سوال شما رو جواب بدیم.

**Comment by newtrader1371** [comment]
برای درخواست ثبت برداشت wallet_id می خواد که برای کوین های مختلف مشخص نیست چیه.....
بهتر نبود به جای این مورد اسم کوین رو می گرفتین؟
در هر صورت اگر لیستی هست که wallet_id رو توش می تونید به من بدید بفرستید ممنون

**Comment by z-amini** [comment]
@newtrader1371 

سلام.
وقتتون بخیر.
شما برای ثبت درخواست برداشت نیاز دارید از موجودی کیف‌پول تون اطلاع داشته باشید. در نتیجه بایستی از طریق API دریافت کیف‌پول‌ها اقدام به دریافت شناسه و مقدار موجودی و مقدار موجودی در سفارش کیف‌پول خودتون اقدام کنید. نحوه درخواست این اطلاعات در «منوی اطلاعات کاربر > [لیست کیف پول ها (انتخابی)](https://apidocs.nobitex.ir/#55645b2c6d)» شرح داده شده.

به طور ساده می‌تونید با درخواست `GET /v2/wallets?currencies=btc` همراه با توکن تون، شناسه و موجودی کیف‌پول رمزارز مورد نظر خودتون (اینجا بیت‌کوین) رو دریافت کنید.

**Comment by z-amini** [comment]
سلام.
وقت بخیر.

چون پیامی در مورد استمرار مشکل دریافت نشد و به جهات امنیتی حذف otp در آدرس‌های تایید نشده کاربر، ممکنه برای خود کاربر مخاطره‌بار باشه، من فرض رو بر رفع مشکل شما کاربر گرامی می‌گذارم.
در صورت نیاز می‌تونید وضعیت این درخواست رو مجددا به حالت باز تغییر بدید و دغدغه تون رو مطرح کنید.

با تشکر.
