### ISSUE TITLE
[پشتیبانی]: توکن

### ISSUE THREAD

**Issue by AbdolkarimHaddadi** [nobitex/docs-api#186]
### هدف

سلام وقت بخیر
در روز توکن من ۵ الی ۶ بار از کار میفته و باید توکن جدید بگیرم و در باتم آپدیت کنم. جالب توجه این است که من هیچ گونه ایمیل یا خطایی دریافت نمیکنم.  این بسیار آزار دهنده است که نوبیتکس بدون هیچ پیغام و ایمیلی توکن رو غیر مجاز میکنه. لطفا بفرمایید چرا اینگونه هست؟ من از ورود با اکانت گوگل استفاده میکنم. آیا این میتونه باعت این مشکل بشه؟ هدف از گرفتن توکن اتومات کردن فرآیند ترید هست نه اینکه یک نفر بشینه پای سیستم هر لحظه چک کن که آیا توکن کار میکنه یا نه؟ اکانت من در سطح تریدر و VIP 3  است. البته اگر این باگ وجود نداشت الان اکانتم آخرین سطح VIP رو رد کرده بود.

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

به صورت کاملا نرمال بدون  و مطابق با مستندات سایت

### پاسخ دریافتی

خطای خاصی دریافت نمیشه

**Comment by rbabaee** [comment]
سلام و وقت به خیر. لطفا توضیح میدید که منظور از این که توکن از کار میفته چیه؟ چه اروری دریافت میکنید؟

**Comment by AbdolkarimHaddadi** [comment]
وقتی میخوام اوردر بفرستم یا موجودی بگیرم. API میگه توکن غیر مجاز است. من اکانتم با گوگل هست. چیزی که متوجه شدام. من وقتی با اکانت گوگلم وارد سایت میشم تا زمانی که از سایت نوبیتکس لاگ اوت نکردم توکنم کار میکنه به محض اینکه از سایت نوبیتکس لاگ اوت میکنم یا سشنم قطع میشه توکن منم غیر فعال میشه. به زبان ساده توکن تا زمانی کار میکنه و معتبر است که منم با اکانت گوگلم لاگین باشم. که متاسفانه هیچ معانی نداره.  وقتی توکن من به هر دلیلی غیر مجاز میشه من هیچ ایمیلی یا اس ام اسی دریافت نمیکنم. لطفا مد نظر داشته باشید توکن برای فردی کاربرد داره که نمیخواد پای سیستم باشه تمام مدت و میخواد رباتش براش ترید کنه. پس وقتی توکن رو غیر مجاز میکنید حداقل اطلاع بدید. با این شیوه ی شما من باید تمام مدت پای سیستم باشم تا ببینم توکنم غیر مجاز شده یا نه!!!

**Comment by rbabaee** [comment]
توکن هامون در حال حاضر به این صورته که هر کاربر در آن واحد یک توکن میتونه داشته باشه. در صورتی که جایی لاگ اوت بکنید، توکنتون نامعتبر میشه.
