### ISSUE TITLE
[پشتیبانی]: بستن موقعیت پس از درج سفارش فروش تعهدی

### ISSUE THREAD

**Issue by AlirezaShaygan** [nobitex/docs-api#187]
### شرح خطا

عرض درود و ارادت
مشکلی که بنده دارم در مورد بستن سفارش فروش تعهدی می باشد. بنده یک موقعیت فروش تعهدی باز کردم و با موفقیت باز شد و سپس استعلام گرفتم و بدرستی مقادیر سفارش (موقعیت) نمایش داده شد. ولی زمانی که متد بستن سفارش رو فراخوانی میکنم  پیغام یافت نشد میدهد:
{"detail":"یافت نشد."}

ممنون میشم مشکل بنده رو راهنمایی بفرمایید. بنظر میاد که شناسه سفارش یافت نشده است ولی بنده با همین شناسه استعلام موفق گرفتم.

### جزئیات درخواست

1. آدرس: POST (https://api.nobitex.ir/positions/1061002814/close)
2. داده:
{"amount": "0.035", "price": "143.35", "execution": limit}
3. هدر:
    - Authorization: Token

4. محیط:
    - تست‌نت
    - اصلی

### پاسخ دریافتی

{"detail":"یافت نشد."}

### پاسخ مورد انتظار

طبق مثال :
{
  "status": "ok",
  "order": {
    "id": 28,
    "type": "buy",
    "execution": "Limit",
    "tradeType": "Margin",
    "srcCurrency": "btc",
    "dstCurrency": "rls",
    "price": "6200000000",
    "amount": "0.0100150225",
    "status": "Active",
    "totalPrice": "0",
    "totalOrderPrice": "62093139",
    "matchedAmount": 0,
    "unmatchedAmount": "0.0100150225",
    "partial": false,
    "fee": 0,
    "created_at": "2022-10-25T09:57:38.560820+00:00",
    "averagePrice": "0"
  }
}

**Comment by z-amini** [comment]
سلام.
وقت شما بخیر.

سفارش شما هنوز پر نشده. تا زمانی که سفارشتون با سفارش دیگری مچ نشه، هنوز موقعیتی برای سفارش شما باز نمیشه.
با اولین معامله‌ای که انجام بشه (مقدار matched_amount در سفارشتون غیر ۰ باشه)، موقعیتی برای شما باز میشه که توی لیست موقعیت‌ها تون می‌تونید ببینیدش:
GET /positions/list
شناسه موقعیت تون رو از اونجا می‌تونید بردارید و برای بستنش اقدام کنید.
شناسه سفارش شما فقط برای مشاهده وضعیت سفارش شما قابل استفاده هست و نه موقعیت شما.

اگر سوال بیشتری هست، در خدمت هستیم.
