### ISSUE TITLE
[پشتیبانی]: خطا در وب سرویس لاگین

### ISSUE THREAD

**Issue by ehsan-zarei** [nobitex/docs-api#188]
### هدف

سلام در فراخوانی وب سرویس لاگین با وجود اینکه کد دوعاملی فعال نیست خطای {
    "non_field_errors": [
        "OTP not provided"
    ],
    "code": "MissingOTP"
}
می دهد

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

curl --location 'https://api.nobitex.ir/auth/login/' \
--header 'Content-Type: application/json' \
--form 'username="xxxxxxxx"' \
--form 'password="xxxxxxxx"' \
--form 'captcha="api"'

### پاسخ دریافتی

 {
    "non_field_errors": [
        "OTP not provided"
    ],
    "code": "MissingOTP"
}

**Comment by SepidehM** [comment]
سلام وقتتون بخیر
ممنون از گزارشی که عنوان کردین، برای امنیت بیشتر در زمان لاگین، شما تنها در زمانی می‌تونید که از captcha="api" استفاده کنید که دوعاملی برای شما فعال باشه و مقدار دوعاملی رو در زمان لاگین برامون ارسال کنید. برای ارسال otp در زمان صدا کردن api لاگین، باید مقدار X-TOTP کامل کنید.
این مورد رو به زودی در داک به روز رسانی می‌کنیم :)
