### ISSUE TITLE
اطلاعات بازار (عمومی) The symbol \"\" is not a valid market pair.

### ISSUE THREAD

**Issue by husen-hn** [nobitex/docs-api#19]
http POST https://api.nobitex.ir/v2/orderbook \
  symbol=USDTIRT

https
https://api.nobitex.ir/v2/orderbook?symbol=USDTIRT
{
    "status": "failed",
    "code": "InvalidSymbol",
    "message": "The symbol \"\" is not a valid market pair."
}
 
http
http://api.nobitex.ir/v2/orderbook?symbol=USDTIRT
api.nobitex.ir | 522: Connection timed out

**Comment by mmmce1994** [comment]
نحوه فراخونی درست نیست. نوع بازار باید در بادی درخواست ارسال بشه نه به صورت کوئری استرینگ
https://apidocs.nobitex.ir/#a283f9354b
