### ISSUE TITLE
[پیشنهاد]: گرفتن قیمت به صورت سوکت

### ISSUE THREAD

**Issue by ipharkat** [nobitex/docs-api#190]
### نیازمندی

قیمت رو به صورت httpگرفتن خیلی بده . به سورت ریلتایم بزنید که بتونیم بگیریم قیمت رو دیگه. 
django, django channels

### راه‌حل

create app websocekt , signal , channels

**Comment by rbabaee** [comment]
با سلام و احترام. 
کاربر گرامی، ارائه‌ی وب سوکت در برنامه‌ی شرکت هست و به زودی، امکان اتصاب با وب سوکت هم فراهم میشه.

**Comment by rbabaee** [comment]
سلام. در حال حاضر امکان اتصال با وب سوکت نداریم.

**Comment by itismoej** [comment]
سلام و وقت‌بخیر؛
اخیراً زیرساخت وب‌سوکت رو اضافه کردیم و فعلاً لیست اردربوک رو می‌تونید از وب‌سوکت دریافت کنید: https://apidocs.nobitex.ir/#websocket
