### ISSUE TITLE
سوال در خصوص استفاده از api معاملات تعهدی[پشتیبانی]: 

### ISSUE THREAD

**Issue by hoseinras** [nobitex/docs-api#194]
### هدف

معاملات تعهدی توسط API

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

با سلام برای استفاده از api معاملات تعهدی دو تا سوال دارم:
اول اینکه تو دایکیومنتتون چیزی راجع به استفاده از تعریف ضریب معاملات در API پیدا نکردم ممنون میشم راهنمایی کنید و دیگری اینکه فقط معاملات فروش رو میشه توسط API انجام داد اما داخل سایت خرید تعهدی هم پشتیبانی میشه درسته؟
ممنون میشم در خصوص دو سوال بالا کمک کنید

### پاسخ دریافتی

{"status": "failed", "code": "InvalidMarketPair", "message": "Market Validation Failed"}

### اطلاعات تکمیلی

با سلام برای استفاده از api معاملات تعهدی دو تا سوال دارم:
اول اینکه تو دایکیومنتتون چیزی راجع به استفاده از تعریف ضریب معاملات در API پیدا نکردم ممنون میشم راهنمایی کنید و دیگری اینکه فقط معاملات فروش رو میشه توسط API انجام داد اما داخل سایت خرید تعهدی هم پشتیبانی میشه درسته؟
ممنون میشم در خصوص دو سوال بالا کمک کنید

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.
خیلی ممنون که مطرح کردید.
در اسرع وقت به روز رسانی مستندات رو انجام می‌دیم و بهتون اطلاع رسانی می‌کنیم.

**Comment by z-amini** [comment]
با سلام مجدد.

جزئیات نحوه استفاده از ضریب در معاملات تعهدی و تعیین جهت خرید و فروش در مستندات عمومی API نوبیتکس به روز رسانی شده و شما می‌تونید توی منوی [معامله در بازار تعهدی](https://apidocs.nobitex.ir/#a876cd1a69) توضیحات لازم رو پیدا کنید.

با تشکر از صبر و همراهی شما.
