### ISSUE TITLE
[پشتیبانی]: درخواست درگاه پرداخت تتری

### ISSUE THREAD

**Issue by parsdaric** [nobitex/docs-api#195]
### هدف

عرض ادب و احترام
از آن رو که ما در حال جذب سرمایه گذار از کشور های همسایه میباشیم، لذا تقاضای ایجاد یک درگاه پرداخت تتری را داریم تا در وب سایتمان پیاده سازی کنیم. در واقع قصد داریم این درگاه به مانند درگاه پرداخت های ایرانی بعد از انجام واریز وجه که پیغام success میدهد، این درگاه نیز میبایست بعد از تایید تراکنش و تایید در بلاکچین تتر، به صورت اتومات پیغام دیپوزیت موفقیت آمیز را به کاربر  بدهد.
همچنین از شما تقاضا داریم که راهنمایی ها، مراحل و مستندات لازم را اعلام بفرمایید.

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

.

### پاسخ دریافتی

.

**Comment by rbabaee** [comment]
با سلام و احترام
کاربر گرامی، پیشنهاد شما دریافت شد ولی اعمال آن نیاز به بررسی بیشتر دارد و در کوتاه مدت میسر نیست.
