### ISSUE TITLE
[خطا]: (پاسخ باینری به فراخوای ای پی آی (لیست سفارش‌ها: اردربوک

### ISSUE THREAD

**Issue by MhRasouli** [nobitex/docs-api#196]
### شرح خطا

سلام و خسته نباشید
من ای پی آی که داخل داکیومنت مروبط به  ای پی آی لیست سفارش‌ها: اردربوک هست را درون ترمینال فراخانی می کنم:
curl 'https://api.nobitex.ir/v2/orderbook/BTCIRT'
اما پاسخی که برای من نمایش می دهد این است:
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
یعنی یا دیتایی که می آید صحیح نیست و یا به صورت باینری می باشد. تا ۱۰ روز پیش همین ای پی آی بدون هیچ مشکلی کار می کرد ولی الان حدود ۱۰ روز است که مشکل پیدا کرده است.

### جزئیات درخواست

1. آدرس: curl 'https://api.nobitex.ir/v2/orderbook/BTCIRT'
2. داده:
3. هدر:
4. محیط:

    - اصلی

### پاسخ دریافتی

پاسخ باینری است:

Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.

### پاسخ مورد انتظار

{"status":"ok","lastUpdate":1698737853266,"lastTradePrice":"556190","bids":[["556190","5477.95"],["556200","269.7"],["556800","269.4"],["564600","449.5"],["565100","449"],["570100","179.8"],["570700","184.6"],["650000","15048.58"],["500000000","0.99"],["789500000","0.19"],["900000000","0.01"],["566333226550","30"],["1000000000000","1052.9"]],"asks":[["553200","271.1"],["552700","271.4"],["544900","451.9"],["544400","452.3"],["539400","180.8"],["538900","180.9"],["515000","1"],["512000","506.61"],["510000","98"],["500000","496.07"],["311800","30"],["310000","100"],["306600","9.65"],["303000","165"],["302000","10"],["301000","26.61"],["300000","316.33"],["299000","10"],["298000","10"],["297600","20.09"],["297400","110.09"],["297000","10"],["296000","168.91"],["295800","16.9"]]}

### پیوند مراجع

https://apidocs.nobitex.ir/#6528ce0c42

**Comment by rbabaee** [comment]
سلام. ما این مورد رو نمیتونیم دوباره تولید کنیم. 
هنوز این مشکل رو دارید؟ 
یه فلگ --compressed هم بهش پاس بدید و مجدد امتحان کنید.
