### ISSUE TITLE
[خطا]: اختلال در دریافت اطلاعات از سرور خارج از کشور

### ISSUE THREAD

**Issue by armin-mohammadi** [nobitex/docs-api#198]
### شرح خطا

سلام

از تقریبا دو روز قبل، درخواست‌ها از خارج از ایران به دامنه‌های nobitex.ir و nobitex.net به صورت پراکنده و با نرخ بالا با مشکل مواجه می‌شوند.

به نظر می‌رسد دلیلی شبیه به اختلال شبکه داشته باشد که فرایند ارتباط از همان ابتدای ssl handshake با کندی و مشکل مواجه می‌شود، ارتباط با دیگر دامنه‌ها بدون مشکل اتفاق می‌افتد ولی با دامنه‌های نوبیتکس این مشکل وجود دارد

### جزئیات درخواست

1. آدرس: `GET /v2/orderbook/USDTIRT`
2. داده:

3. هدر:

4. محیط:
    - اصلی

### پاسخ دریافتی

*   Trying 185.166.104.3:443...
* TCP_NODELAY set
* Connected to api.nobitex.ir (185.166.104.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: Connection reset by peer in connection to api.nobitex.ir:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to api.nobitex.ir:443 

### پاسخ مورد انتظار

{"status":"ok","lastUpdate":1699083475909,"lastTradePrice":"517870","bids":[["517870","294.14"],["517980","5215.36"],["517990","55.89"],["518000","8102.94"],["518180","31.47"],["518190","556.78"],["518200","155.83"],["518210","40"],["518350","797.36"],["518390","479.33"],["518400","277.95"],["518450","40.01"],["518490","896.75"],["518500","7064.38"],["518600","294.41"],["519000","1002"],["519100","76.08"],["519200","1009.26"],["519290","200.99"],["519300","13111.33"],["519350","1107.86"],["519370","3361.83"],["519400","108.71"],["519490","455.25"]],"asks":[["517860","70"],["517810","4"],["517800","1815.48"],["517790","28.98"],["517770","2495.07"],["517750","100"],["517720","2"],["517710","101"],["517700","1642.35"],["517690","1000"],["517670","482.86"],["517650","94.69"],["517630","3594.25"],["517610","101"],["517600","78.24"],["517590","14.77"],["517560","200"],["517520","30"],["517510","8101.72"],["517500","6285.18"],["517430","28.35"],["517420","5.7"],["517410","101"],["517400","225.75"]]}

### پیوند مراجع

https://apidocs.nobitex.ir/#6528ce0c42

### اطلاعات تکمیلی

- vps
- ovh  سرور خارجی

**Comment by amiraliakbari** [comment]
با سلام
این مشکل در لایه CDN ستون است. موضوع با این تیم مطرح و نتیجه اعلام خواهد شد. با توجه به این که مشکلی در صفحه وضعیت این سرویس ثبت نشده (status.sotoon.ir) ممکن است بررسی موضوع کمی زمان نیاز داشته باشد.

**Comment by ya3er** [comment]
با سلام
متاسفانه این مشکل همچنان ادامه داشته و شدت اختلال بسیار شدید است به حدی که تمامی عملیات ما را متوقف کرده است.  لازم بذکر است پینگ بر روی دامنه اصلی و دامنه api از خارج از کشور مناسب است ولی تمامی ریسپانس ها از طریق api دچار اختلال هستند.

![TimeOut](https://github.com/nobitex/docs-api/assets/23307823/90d38f25-ec22-46c7-87d9-0b0399ccd049)

**Comment by mostafa2msh** [comment]
سلام الان بیش از دو هفته است این مشکل وجود دازد چرا رسیدگی نمیکنید؟ @amiraliakbari

**Comment by armin-mohammadi** [comment]
سلام مجدد

به نظر میرسد که دوباره این مشکل به شکل متفاوتی ایجاد شده که از سرور داخل، سریعتر جواب داده می‌شود ولی از سرور خارج در مرحله tls handshake تاخیر نسبتا زیاد ایجاد می‌شود که عملیات دریافت قیمت و سفارش گذاری را با مشکل شدید مواجه کرده است

لاگ curl از داخل:

➜  ~ curl https://api.nobitex.ir/v2/orderbook/USDTIRT -vvv
*   Trying 185.166.104.4:443...
* Connected to api.nobitex.ir (185.166.104.4) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api.nobitex.ir
*  start date: Oct 31 18:59:14 2023 GMT
*  expire date: Jan 29 18:59:13 2024 GMT
*  subjectAltName: host "api.nobitex.ir" matched cert's "api.nobitex.ir"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fc460009600)
> GET /v2/orderbook/USDTIRT HTTP/2
> Host: api.nobitex.ir
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Sat, 18 Nov 2023 16:22:14 GMT
< content-type: application/json
< content-length: 1013
< vary: Accept-Encoding
< cache-control: max-age=1,public,stale-if-error=60
< access-control-allow-credentials: true
< access-control-allow-origin: *
< x-zrk-us: 200
< strict-transport-security: max-age=31536000
< server: Delivery
< x-zrk-cs: EXPIRED
< x-zrk-sn: 1011
< accept-ranges: bytes
< accept-ranges: bytes
< 
* Connection #0 to host api.nobitex.ir left intact
{"status":"ok","lastUpdate":1700324533377,"lastTradePrice":"513650","bids":[["513650","0.85"],["513660","1033.73"],["513670","455.35"],["513690","1881.14"],["513700","3029.84"],["513750","452.51"],["513780","2021.35"],["513800","627.14"],["513830","140"],["513840","20"],["513890","9"],["513900","500"],["513910","52"],["513920","2529.86"],["513930","1127.71"],["513940","1676.85"],["513950","1521.52"],["513960","1036.44"],["513970","15"],["513980","3796.2"],["513990","7328.41"],["514000","2443.85"],["514180","1000"],["514250","5000"]],"asks":[["513600","799.93"],["513400","82.02"],["513180","194.82"],["513160","2999.44"],["513150","2699.28"],["513120","194.83"],["513090","430.86"],["513020","20"],["513010","162.83"],["513000","6397.01"],["512900","943.2"],["512820","488.02"],["512800","10"],["512500","202.64"],["512490","1.94"],["512450","371.25"],["512400","5.85"],["512230","92.19"],["512220","363.55"],["512200","1053.73"],["512180","58.61"],["512170","21.41"],["512110","56.86"],["512040","494.1"]]}


لاگ curl برای سرور خارج از کشور:
➜  ~ curl https://api.nobitex.ir/v2/orderbook/USDTIRT -vvv
*   Trying 185.166.104.3:443...
* TCP_NODELAY set
* Connected to api.nobitex.ir (185.166.104.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):



* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=api.nobitex.ir
*  start date: Oct 31 18:59:14 2023 GMT
*  expire date: Jan 29 18:59:13 2024 GMT
*  subjectAltName: host "api.nobitex.ir" matched cert's "api.nobitex.ir"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b919d850c0)
> GET /v2/orderbook/USDTIRT HTTP/2
> Host: api.nobitex.ir
> user-agent: curl/7.68.0
> accept: */*
> 


* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< date: Sat, 18 Nov 2023 16:19:35 GMT
< content-type: application/json
< content-length: 1008
< vary: Accept-Encoding
< cache-control: max-age=1,public,stale-if-error=60
< access-control-allow-credentials: true
< access-control-allow-origin: *
< x-zrk-us: 200
< strict-transport-security: max-age=31536000
< server: Delivery
< x-zrk-cs: EXPIRED
< x-zrk-sn: 2001
< accept-ranges: bytes
< accept-ranges: bytes
< 
* Connection #0 to host api.nobitex.ir left intact
{"status":"ok","lastUpdate":1700324373320,"lastTradePrice":"513680","bids":[["513680","384.74"],["513700","4895.1"],["513740","11.2"],["513750","452.51"],["513780","2021.35"],["513800","627.14"],["513830","140"],["513840","20"],["513890","9"],["513900","500"],["513910","52"],["513920","2529.86"],["513930","1127.71"],["513940","1676.85"],["513950","1521.52"],["513960","1036.44"],["513970","15"],["513980","3796.2"],["513990","7350.41"],["514000","2443.85"],["514180","1000"],["514250","5000"],["514280","123.19"],["514330","100"]],"asks":[["513450","447.83"],["513400","141.87"],["513300","486.59"],["513200","947.16"],["513160","20"],["513150","285.61"],["513100","3544.66"],["513090","430.86"],["513010","2637.68"],["513000","6218.57"],["512900","943.2"],["512820","975.74"],["512800","10"],["512500","196.84"],["512490","1.94"],["512450","371.25"],["512400","5.85"],["512230","92.19"],["512220","363.55"],["512200","1053.73"],["512180","58.61"],["512170","21.41"],["512130","15.61"],["512040","494.1"]]}


که سه خط زیر در لاگ curl دوم، قسمتی‌ است که باعث کندی پاسخ‌دهی API است:
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing

**Comment by amiraliakbari** [comment]
با سلام
به دلیل عدم رضایت کاربران نهایی از CDN ستون، سرویس CDN به ابر آروان تغییر یافت. در صورت بروز مجدد مشکل لطفاً اطلاع بدهید.

**Comment by armin-mohammadi** [comment]
با سلام مجدد
از حوالی ساعت ۹ صبح امروز مجددا این اختلالات مشاهده می‌شود

لطفا بررسی شود

**Comment by armin-mohammadi** [comment]
با سلام این مشکل از حدود ساعت ۱۸ امروز دوباره دیده شده به شکلی که API orderbook تایم‌اوت میشه

➜  ~ curl https://api.nobitex.ir/v2/orderbook/USDTIRT --connect-timeout 5  
curl: (28) Connection timed out after 5001 milliseconds
➜  ~ curl https://api.nobitex.net/v2/orderbook/USDTIRT --connect-timeout 5
curl: (28) Resolving timed out after 5000 milliseconds

@amiraliakbari
