### ISSUE TITLE
[خطا]

### ISSUE THREAD

**Issue by aarreess00** [nobitex/docs-api#199]
### هدف

خطای missing otp هنگام درخواست توکن

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...
python

### نحوه درخواست

import requests

url = "https://testnetapi.nobitex.ir/auth/login/"

payload = {
    "username": "****",
    "password": "****",
    "captcha": "api"
}
headers = {
    "Content-Type": "application/json",
    "User-Agent": "insomnia/8.3.0"
}

response = requests.request("POST", url, json=payload, headers=headers)

print(response.text)

### پاسخ دریافتی

{
	"non_field_errors": [
		"OTP not provided"
	],
	"code": "MissingOTP"
}

**Comment by rbabaee** [comment]
سلام و وقت به خیر .
برای لاگین با بات، باید otp اکانتتون رو فعال کنید و حتما  otp رو هم پاس
بدید. برای اطلاع از نحوه‌ی پاس دادن otp ، به داکیومنتیشن رجوع کنید.
