### ISSUE TITLE
[پیشنهاد]: اندپوینت برای گرفتن لیست مارکت ها

### ISSUE THREAD

**Issue by Mostafa-Abbasinejad** [nobitex/docs-api#201]
### نیازمندی

سلام و وقت بخیر؛
عجیب به نظر میرسه، اما API نوبیتکس هیچ اندپوینتی برای گرفتن لیست مارکت ها (اعم از مارکت های ریالی/تتری) نداره! 
الان من میخوام مارکت های موجود در نوبیتکس رو بگیریم، متأسفانه از طریق API امکان گرفتن لیست مارکت های نوبیتکس نیست ظاهراً...
اگر اشتباه میکنم بنده رو تصحیح بفرمائید.
با تشکر 

### راه‌حل

ایجاد یک اندپوینت برای گرفتن لیست کلیه مارکت های ریالی و تتری در بازارهای اسپات و مارجین

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.

همه ارزهای فعال در نوبیتکس در [API تنظیمات نوبیتکس](https://apidocs.nobitex.ir/#options) قابل دریافت هست. (کلید activeCurrencies)
 https://api.nobitex.ir/v2/options
این رمزارزها در دو بازار ریالی و تتری در نوبیتکس فعال هستن.
با دادن زوج ارزها به عنوان ورودی در [API آمار بازار نوبیتکس](https://apidocs.nobitex.ir/#6ae2dae4a2) می‌تونید بازار مورد نظر رو از نظر باز یا بسته بودن، بررسی کنید.
https://api.nobitex.ir/market/stats?srcCurrency=btc,ltc,bnb&dstCurrency=rls,usdt

برای بازار تعهدی نوبیتکس نیز [API مشاهده بازارهای تعهدی](https://apidocs.nobitex.ir/#3f2eb2d88c) ارائه شده که فعال بودن جهت خرید و فروش و سایر اطلاعات بازار رو بهتون میده.
https://api.nobitex.ir/margin/markets/list

با آرزوی موفقیت
