### ISSUE TITLE
[خطا]:لغو ثبت سفارش مارکت

### ISSUE THREAD

**Issue by aarreess00** [nobitex/docs-api#202]
### شرح خطا

سلام وقت بخیر من از  ای پی ای ثبت سفارش مارکت استفاده میکنم ولی خود به خود سفارش رو لغو می کنه ممنون میشم راهنمایی کنید

### جزئیات درخواست

https://testnetapi.nobitex.ir/market/orders/add

{"type":"buy","srcCurrency":"btc","dstCurrency":"rls","amount":"0.001","price":2000000000,"clientOrderId":"order10017", "execution":"market"}

### پاسخ دریافتی

![image](https://github.com/nobitex/docs-api/assets/148704771/afb5b2da-f64c-4934-9f98-193ce55b252d)

### پاسخ مورد انتظار

ثبت صحیح سفارش

**Comment by rbabaee** [comment]
سلام. اگر سفارش مارکت مچ نشه، کنسل میشه . شما براش price هم ست کردید که ممکنه به خاطر قیمت در اون تایمی که داشتید تست میکردید بوده. 

> در سفارش‌های مارکت به شدت توصیه می‌شود که پارامتر price را نیز مشخص نمایید. این پارامتر در سفارش مارکت تخمین شما از قیمت بازار را نمایش می‌دهد و باعث می‌شود سفارش شما تنها تا جایی پر شود که قیمت معامله در بازه‌ی قیمتی مشخص شده باشد. برای نمونه اگر نوع سفارش خرید مارکت باشد و قیمت ۱۰۰ میلیون تومان تعیین شود، تنها تا جایی در بازار range کشیده می‌شود که قیمت زیر ۱۰۱ میلیون تومان باشد. برای پیش‌گیری از معاملات با قیمت ناخواسته به علت نوسانات دفعی بازار، پیشنهاد می‌شود که حتماً قیمت تقریبی مد نظر خود را در سفارش‌های مارکت نیز ارسال کنید. با این حال اگر اطمینان به کد خود و تبعات احتمالی این موضوع دارید، می‌توانید پارامتر price را اصلاً ارسال ننمایید که در این شرایط معامله با قیمت لحظه‌ای بازار جهانی، به هر میزان که باشد تا بازه نوسان ۱٪، انجام خواهد شد.
