### ISSUE TITLE
[خطا]:  جا به جا بودن ask و bid

### ISSUE THREAD

**Issue by EmiroDeve** [nobitex/docs-api#203]
### شرح خطا

https://api.nobitex.ir/v2/orderbook/BTCUSDT

قیمت خرید باید قیمت ask باشه و قیمت فروش قیمت bid
و قاعدتا ask از bid گرون تره
اما تو این API این قضیه برعکسه و قیمت ask ارزون تره از bid و باید به قیمت bid خرید کنیم و به قیمت ask بفروشیم
من با صرافیای زیادی کار کردم اونا رو این روال بودن

### جزئیات درخواست

1. آدرس: `GET https://api.nobitex.ir/v2/orderbook/XLMIRT`

### پاسخ دریافتی

{"status":"ok","lastUpdate":1700297087802,"lastTradePrice":"59800","bids":[["60000","55.1"],["60440","79621.9"],["60480","96.5"],["60500","9029"],["60730","1649.7"],["60830","25597.3"],["60870","5195.5"],["60890","185.3"],["60940","164"],["60950","1619.6"],["60990","974.5"],["61000","3170.9"],["61200","215.2"],["61600","200"],["61640","400"],["61650","300"],["61700","750"],["61750","647.1"],["61790","200"],["61800","81"],["61900","639"],["61960","2381.1"],["62000","10462.3"],["62040","150.6"]],"asks":[["59800","885.4"],["59700","85.2"],["59620","161.9"],["59600","25619.1"],["59130","102"],["59110","804.3"],["59100","2809.8"],["59050","785.1"],["59020","8.7"],["59010","412.9"],["59000","3117.7"],["58630","32.5"],["58600","20"],["58590","2620.8"],["58580","119.4"],["58240","137.5"],["58210","146"],["58200","1465.9"],["58100","172.1"],["58080","23.7"],["58020","10700"],["58010","11"],["58000","3843.4"],["57800","8.7"]]}

### پاسخ مورد انتظار

این فقط یه فیدبکه من روی این قضیه کارمو انجام میدم

**Comment by armin-mohammadi** [comment]
همزمان که این مشکل وجود دارد، هر گونه تغییر در ریسپانس این API، نیاز به backward compatibility و اطلاع‌رسانی دارد که مشکلی برای سیستم‌های فعلی به وجود نیاید.

**Comment by rbabaee** [comment]
سلام. 
تغییر این مورد فعلا ممکن نیست و این مورد توی مستندات هم ذکر شده که به خاطر backward compatibility ، فعلا قصدی برای تغییرش نداریم. 
https://apidocs.nobitex.ir/#orderbook:~:text=symbol%20%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87%20%D9%86%D9%85%D8%A7%DB%8C%DB%8C%D8%AF.-,%D9%BE%D8%A7%D8%B1%D8%A7%D9%85%D8%AA%D8%B1%D9%87%D8%A7%DB%8C%20%D9%BE%D8%A7%D8%B3%D8%AE,-%D8%AE%D8%B1%D9%88%D8%AC%DB%8C%20%D8%B4%D8%A7%D9%85%D9%84%20%D8%AF%D9%88
