### ISSUE TITLE
Inquiry regarding Cryptocurrency price API and Documentation

### ISSUE THREAD

**Issue by Azura-lee-code** [nobitex/docs-api#204]
### هدف

Dear Nobitex Team,

I contacted you through your chat bot on your website several minutes ago. Could you please provide us with the following details regarding your cryptocurrency API:

1. **Availability**: Do you offer an API that provides real-time or near-real-time cryptocurrency prices? If yes, could you provide a brief overview of its capabilities?
2. **Pricing**: If such an API is available, what would be the cost to access this service? Are there different pricing tiers based on usage or data volume?
3. **Documentation**: Is there English documentation available for this API? It would be helpful for our development team to have clear and comprehensive documentation in English to facilitate seamless integration.
4. **Support and Reliability**: What kind of technical support do you offer for API users? Also, can you provide any uptime statistics or reliability guarantees for the API service?
5. **Trial Access**: Do you offer a trial period for new users to test the API before committing to a subscription? This would be highly beneficial for our assessment and decision-making process.

We are eager to explore how your API service can complement our existing and future projects. We believe that having accurate and timely cryptocurrency data is crucial for our business objectives.

Thank you in advance for your attention to this inquiry. We look forward to your prompt response and hope to establish a mutually beneficial partnership.

Best regards,

Azura

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

skip

### پاسخ دریافتی

skip

**Comment by delafrouz** [comment]
Hi @Azura-lee-code 

Thank you for your message and inquiry. Currently, we are focused on providing exchange services, and what you ask for is more of a pricing service. Unfortunately, at the moment we are not focused on that and don't provide a pricing service.

Best of luck with your endeavors,
Nobitex team
