### ISSUE TITLE
[پشتیبانی]: 

### ISSUE THREAD

**Issue by adeliiman** [nobitex/docs-api#206]
### هدف

توکن API گرفتم ولی در پاسخ اولین درخواستم، ریسپانس زیر گرفتم: 
**اطلاعات برای اعتبارسنجی ارسال نشده است.**

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

token = "token"
url = 'https://api.nobitex.ir/users/profile'
headers = {"Authorization" : token}
res = requests.get(url, headers)
print(res.json())

### پاسخ دریافتی

اطلاعات برای اعتبارسنجی ارسال نشده است.

**Comment by rbabaee** [comment]
سلام. کلمه‌ی Token رو اولش گذاشتید؟
`Authorization: Token yourTOKENhereHEX0000000000`
