### ISSUE TITLE
خطای #CORS 

### ISSUE THREAD

**Issue by NavidAzhirak7s** [nobitex/docs-api#207]
### شرح خطا

با توجه به مستنداتی که ارائه دادین برای دریافت api که عمومی هستن نیازی نیس در هدر پارامتری ارسال شود

بازم هم در هنگام درخواست  CORS بر میخوره میخواستم ببینم آیا سمت سرور این مورد هندل شده است؟ که این خطا نمایش داده نشود

من افزونه که برای گول کروم وجود دارد تونستم این مشکل خطا رو رفع کنم اما اگر از این افزونه استفاده نشود خطا Cors مجدد نمایش داده میشود

#extension Unblock CORS for chrome

### جزئیات درخواست

1. آدرس: `GET  https://api.nobitex.ir/market/stats?srcCurrency=usdt&dstCurrency=rls`

### پاسخ دریافتی

Access to fetch at 'https://api.nobitex.ir/market/stats?srcCurrency=usdt&dstCurrency=rls' from origin 'http://localhost:5173' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://nobitex.ir' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

### پاسخ مورد انتظار

.

### پیوند مراجع

1.  header('Access-Control-Allow-Origin: https://###.ir');
2.  header('Access-Control-Allow-Origin: *');

**Comment by rbabaee** [comment]
سلام. اگر ای پی آی رو، مستقیم صدا بکنید ( یعنی با کد صدا بکنید و نه با بروزر ) این مشکل پیش نمیاد. 
ولی  نمیتونیم cors رو کلا غیر فعال کنیم.
