### ISSUE TITLE
[پشتیبانی]: گرفتن لحظه ای قیمت تتر

### ISSUE THREAD

**Issue by Programmer-cs** [nobitex/docs-api#212]
### هدف

سلام میخواستم بدونم چطور میتونم با استفاده از api سایت بیام قیمت ریالی تتر رو بگیرم بعد آیا محدودیت تعداد درخواست داره یا نه 

### محیط درخواست

پایتون

### نحوه درخواست

```
requests
```

### پاسخ دریافتی

قیمت تتر به ریال

**Comment by rbabaee** [comment]
سلام. 
لیست ای پی آي ها رو میتونید از اینجا مشاهده کنید:
https://apidocs.nobitex.ir/
ریت لیمیت هر کدومشون هم توی داک نوشته شده. با توجه به موردی که میخواید پیاده سازی کنید، میتونید ای پی آی مناسب رو انتخاب کنید.
