### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by siavashrostami** [nobitex/docs-api#214]
### هدف

در قسمت پروفایل تنظیمات (api) فقط یکبار نمایش داده شد میخوام دوباره نمایش داده بشه که بتونم کپی کنم.

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

محیط

### پاسخ دریافتی

عدم‌ نمایش api key

**Comment by z-amini** [comment]
با سلام و وقت بخیر.

شما هر زمان که به بخش[ تنظیمات پروفایل](https://nobitex.ir/panel/profile/settings/) تون مراجعه کنید، کلید API شما قابل کپی هست. کافیه روی دکمه «نمایش توکن :eye:» بزنید.
اگر این بخش رو به هر دلیلی مشاهده نمی‌کنید، تصویری از صفحه فوق برای ما بفرستید. (مراقب باشید که اطلاعات شخصی و محرمانه تون توی تصویر نباشه و اگر هست، مخدوش بشه.)

با تشکر
