### ISSUE TITLE
[پشتیبانی]: چگونگی درخواست لاگین

### ISSUE THREAD

**Issue by waybroke** [nobitex/docs-api#215]
### هدف

دریافت API key

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

curl 'https://api.nobitex.ir/auth/login/' \
  -X POST \
  -H "Content-Type: application/json" \
  --data $'{"username":"name@example.com","password":"secret-password-1234","captcha":"api"}'

### پاسخ دریافتی

{"non_field_errors":["OTP not provided"],"code":"MissingOTP"}

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.

برای لاگین اگر دوعاملی رو روی حساب تون فعال کردید، باید حتما در هدر درخواست با عنوان X-TOTP بیاریدش.
در کنار این باید برای درخواست لاگین User-Agent رو با اسم بات تون به فرمت TraderBot/my-bot-name مقدار دهی کنید.
 نمونه درخواست رو می‌تونید توی [کالکشن پستمن نوبیتکس](https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest#8f23dbb6-4899-4b64-9ee1-ac7024e7944d) هم ببینید.

امیدواریم مشکل تون با این جواب برطرف بشه.
