### ISSUE TITLE
[پشتیبانی]: از چه url ای برای گرفتن قیمت یک رمزارز به تومان و تتر در خود نوبیتکس باید استفاده کنم

### ISSUE THREAD

**Issue by arshiahaeri89** [nobitex/docs-api#217]
### هدف

میخواهم قیمت ارزی برای مثال atom رو در بازار نوبیتکس در همان لحظه به تومان و تتر داشته باشم

### محیط درخواست

- ابزار درخواست (برنامه python)
- زبان برنامه (Python)
- محل درخواست (local)
- درخواست IP (داخلی)
- ...

### نحوه درخواست

```python
import requests

url = '???'
res = requests.get(url)

print(res.json())
```

### پاسخ دریافتی

خطا نداشتم کلا نمیدونم چکار باید بکنم

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر باشه.

ما مجموعه‌ای از API های پرکاربردمون رو در [کالکشن Postman](https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest) قرار دادیم تا بتونید نحوه درخواست زدن در اکثر زبان‌های رایج برنامه‌نویسی رو راحت در اختیار داشته باشید.

برای مثال این داده مورد تقاضای شما از طریق API های آمار بازار نوبیتکس قابل دسترسی هست.
```python
import requests

url = 'https://api.nobitex.ir/market/stats'
payload={'srcCurrency': 'atom', 'dstCurrency': 'usdt,rls'}
res = requests.get(url, payload)

print(res.json())
```

**Comment by arshiahaeri89** [comment]
ممنون خیلی کمک کرد لطف فرمودید
