### ISSUE TITLE
[خطا]: nobitex / docs-api Public

### ISSUE THREAD

**Issue by asaeb1480** [nobitex/docs-api#219]
### شرح خطا

با درج کد زیر خطای
{"detail":"اطلاعات برای اعتبارسنجی ارسال نشده است."}

صادر شده است.

  curl 'https://api.nobitex.ir/users/wallets/balance' \
  -X POST \
  --header "Authorization:xxxxxxx" \
  --data '{"currency":"btc"}'

### جزئیات درخواست

  curl 'https://api.nobitex.ir/users/wallets/balance' \
  -X POST \
  --header "Authorization:xxxxxxx" \
  --data '{"currency":"btc"}'

### پاسخ دریافتی

اطلاعات برای اعتبارسنجی ارسال نشده است.

### پاسخ مورد انتظار

مقدار موجودی نمایش داده شود!

### پیوند مراجع

https://apidocs.nobitex.ir/?shell#55645b2c6d

**Comment by z-amini** [comment]
سلام.
وقتتون بخیر.
از فرمت ارسال توکن مطمئن بشید. برای مثال فرض کنید که توکنی که دریافت کردید این مقداره: `db20***dd46f`
در درخواست شما این مقدار باید به شکل زیر ارسال بشه:

`--header "Authorization: Token db20***dd46f"`

قبل توکن تون باید کلمه Token به یک فاصله بیاد.
امیدوارم که مشکل تون رفع شده باشه.

**Comment by asaeb1480** [comment]
با سلام و تشکر مشکل حل شدآ ممنون
