### ISSUE TITLE
A bunch of issues and required methods

### ISSUE THREAD

**Issue by mhrj94** [nobitex/docs-api#22]
Dear development  team,
I've been using this API to create a trader bot for some time and here is a list of missing needed functionalities and issues:

- User needs to get a list of their own active orders. There is no such thing
- For critical and sensitive functions (e.g. "market/orders/add") there must be a field of expiry for the request in a way that if the request reaches the API core too late, it won't  be processed and be ignored. Trading bots need to make sure that if they didn't receive the response in a due time (i.e the expiry time) the request has been failed for sure and they send it again with confidence.
- Many APIs provide a life-time "API key" and "API secret". That is a better approach than logging in regularly.
- At the moment of writing this, after activating two-factor authentication it's impossible to log in via the API.
- There must be an API for withdrawal.
- Buyers' offers must be called "bids" and sellers' offers must be called "asks" in order books. You are using these terms the other way around!!
- Fetching order books of each market requires an individual request. For example if I need order books of "USDTIRT", "BTCIRT" and "ETHIRT" markets I have to make 3 requests. Being able to fetch them all together would be an ease of access for both the user and the server.
- Order books get updated not fast enough and sometimes according to the order book, buyers are offering a higher price than sellers; which is impossible and they should make the deal happen in real-time and get out of the list immediately (the attached photo).
![nobitex bug](https://user-images.githubusercontent.com/31111663/91655422-9f486480-eac5-11ea-86f4-dbf29f688db9.jpg)

Best regards, MHRJ

**Comment by z-amini** [comment]
با سلام و عرض ادب.

برخی از مواردی که گزارش کرده بودید طی یک سال گذشته رفع شده یا به عنوان فیچر اضافه شده. به طور تک به تک مواردی که رفع شدن رو خدمتتون اطلاع میدم:

- دریافت لیست سفارشات فعال کاربر: این API در بخش معامله در بازار > [فهرست سفارش‌های کاربر](https://apidocs.nobitex.ir/#a2ce8ff7e3) مستند شده. به طور کلی نوبیتکس API های زیادی داره که به طور عمومی ارائه نمیده، بدین منظور که بنای پشتیبانی بلندمدت از اون API ها رو در قبال کاربران عمومی و آزاد API نداره. در نتیجه بسیاری از ویژگی هایی که در اپ و سایت مشاهده می‌کنید رو ممکنه در صفحه [مستندات API](https://apidocs.nobitex.ir) پیدا نکنید. هر زمان تصمیم بر ارائه عمومی اون API شد، اون رو برای کاربران در صفحه مستندات قرار می‌دیم. در غیر این صورت می‌تونید به طور غیر رسمی با مسئولیت خودتون از اون APIها استفاده کنید.
- در زمینه زمان انقضای درخواست، پیشنهاد شما رو منتقل می‌کنم.
- برای توکن مادام‌العمر، در حال حاضر تصمیم تیم نوبیتکس به جهات امنیتی بر تعویض حداکثر ماهیانه توکن هست. با وجود امکان افزایش این زمان از نظر فنی (از ابتدا)، هنوز تصمیمی برای ارائه این ویژگی اتخاذ نشده. از منظر برنامه‌نویسان، فی نفسه استفاده از توکن منقضی شونده که از طریق API دریافت می‌شه، دشواری چندانی نداره.
- مستندات ورود در زمان فعال‌سازی دوعاملی به روز شده و در بخش احراز هویت > [سوالات متداول دریافت توکن](https://apidocs.nobitex.ir/#login-faq) و ملاحظات عمومی > [اعتبارسنجی دوعاملی](https://apidocs.nobitex.ir/#dbf936619c) می‌تونید ملاحظه کنید.
- برای برداشت، مستندات API نوبیتکس در بخش [برداشت](https://apidocs.nobitex.ir/#withdraw) ارائه شده. مجددا تاکید می‌کنم که عدم ارائه API لزوما به معنی عدم وجود اون نیست، بلکه برای پشتیبانی عمومی اون قصدی انجام نگرفته.
- جابجایی دو کلمه bids و asks در API اردربوک سهوی رخ داده و اصلاحش در برنامه ما هست، اما به دلایل compatibility با تعویق روبرو شده. در صورت رفع بهتون اطلاع میدیم.
- امکان دریافت یکجای همه اردربوک‌ها در نوبیتکس فراهم شده. برای این کار به مستندات بخش اطلاعات بازار (عمومی) > [لیست سفارش‌ها: اردربوک](https://apidocs.nobitex.ir/#orderbook) مراجعه بفرمایید. دقت کنید مجموعه اولیه APIهای نوبیتکس مطابق نیازهای اپ و سایت طراحی شده که شامل خیلی از موارد پیشنهادی مثل این مورد پیشنهادی شما نمی‌شده. ما به تدریج در حال تکمیل و ارائه نیازهای سایر کاربران مثل بات-نویسان نوبیتکس هستیم. پیشنهادات شما دریافت، بررسی و اولویت بندی می‌شن و در برنامه اجرایی قرار می‌گیرند. برای رسیدن به راه‌حل برای همه نیازها اندکی صبور باشید و در ارائه پیشنهادات با ما همکاری کنید.
- مورد گذارش شده درباره real-time بودن منطق معاملات، طی بهبودهای سال گذشته برطرف شده. در صورت مشاهده مجدد در یک ترد جداگانه بهمون گزارش کنید. (تفکیک به رسیدگی ما خیلی کمک می‌کنه.)

می تونید [کانال تلگرام نوبیتکس](https://t.me/nobitexmarket) رو برای دنبال کردن تغییرات API و فیچرهای جدید نوبیتکس دنبال کنید.

با تشکر از وقت و توجهی که در اختیار ما قرار دادید.
