### ISSUE TITLE
[درخواست]: وب سوکت

### ISSUE THREAD

**Issue by imankhorshidi** [nobitex/docs-api#232]
### نیازمندی

سلام
تیم برنامه نویسی نوبیتکس اگه وب سوکت بازار رو ارائه بدین عالی میشه.
بنده این مورد رو خیلی نیاز دارم.
همه دارن بجز نوبیتکس

### راه‌حل

ایجاد وب سوکت

**Comment by Mostafa-Abbasinejad** [comment]
سلام و وقت بخیر؛

ظاهراً وب سوکت نوبیتکس راه افتاده و میشه ازش استفاده کرد، البته چون هنوز داکیومنت مناسبی در دسترس نیست، پیشنهاد میکنم هنوز ازش استفاده نکنید.

آدرس وب سوکت نوبیتکس: 
wss://ws.nobitex.ir/connection/websocket

ظاهراً فرایند "پینگ پنگ" به صورت ارسال آبجکت خالی انجام میشه. یعنی هر وقت پیام {} رو برای شما ارسال شد. شما هم پیام {} رو ارسال بفرمائید تا سوکت باز بمونه.

برای سابسکرایب کردن روی اردربوک یک بازار خاص  میتونین آبجکت زیر رو به سوکت ارسال کنید:

`{"subscribe":{"channel":"public:orderbook-USDTIRT","delta":"fossil"},"id":2}
`
ولی فعلاً داکیومنتی برای مدیریت پاسخ های ارسالی از سمت سرور در اختیار نیست. اجازه بدین داکیومنت بشه تا بهتر بشه ازش استفاده کرد.

موفق باشید.

**Comment by z-amini** [comment]
سلام و وقت بخیر.
نسخه آزمایشی وب‌سوکت نوبیتکس در [مستندات](https://apidocs.nobitex.ir/#websocket) آورده شده است.
امیدواریم به خوبی استفاده کنید. اگر مشکلی در اتصال داشتید، با ما در میان بگذارید.

از شکیبایی و همراهی شما متشکریم.

**Comment by Mostafa-Abbasinejad** [comment]
> سلام و وقت بخیر. نسخه آزمایشی وب‌سوکت نوبیتکس در [مستندات](https://apidocs.nobitex.ir/#websocket) آورده شده است. امیدواریم به خوبی استفاده کنید. اگر مشکلی در اتصال داشتید، با ما در میان بگذارید.
> 
> از شکیبایی و همراهی شما متشکریم.

سلام خانم امینی

بله الان دیدم داکیومنت اضافه شده، تشکر بابت توضیحاتتون،
