### ISSUE TITLE
رمز یکبارمصرف شناسایی دوعاملی [پشتیبانی]: 

### ISSUE THREAD

**Issue by hassanzadeh20** [nobitex/docs-api#234]
### هدف

در خواست توکن از طریق API

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

import requests

url = "https://api.nobitex.ir/auth/login/"

payload={'username': 'your_email@mail.com',
'password': 'your_password',
'remember': 'yes',
'captcha': 'api',
'useragent': 'TraderBot/your_bot'}
files=[

]
headers = {
  'X-TOTP': '707912'
}

response = requests.request("POST", url, headers=headers, data=payload, files=files)

print(response.text)

### پاسخ دریافتی

خطای درخواست TOTP

### اطلاعات تکمیلی

برای دریافت توکن از طریق API از کد پایتون شما استفاده کردم ولی برای TOTP مقدار صحیح را نیاز دارم. در حالی که من رمز یکبارمصرف شناسایی دوعاملی را فعال نکردم. ممنون می شم راهنمایی کنید. داخل لینک زیر در مورد مقدار TOTP  صحبتی نشده متاسفانه:
https://documenter.getpostman.com/view/5722122/Szmcayjw#8f23dbb6-4899-4b64-9ee1-ac7024e7944d

**Comment by Mostafa-Abbasinejad** [comment]
> ### هدف
> در خواست توکن از طریق API
> 
> ### محیط درخواست
> * ابزار درخواست (مرورگر/ابزار/برنامه/...)
> * زبان برنامه (cURL/Python/PHP/...)
> * محل درخواست (local/VPS/...)
> * درخواست IP (داخلی/خارجی)
> * ...
> 
> ### نحوه درخواست
> import requests
> 
> url = "https://api.nobitex.ir/auth/login/"
> 
> payload={'username': '[your_email@mail.com](mailto:your_email@mail.com)', 'password': 'your_password', 'remember': 'yes', 'captcha': 'api', 'useragent': 'TraderBot/your_bot'} files=[
> 
> ] headers = { 'X-TOTP': '707912' }
> 
> response = requests.request("POST", url, headers=headers, data=payload, files=files)
> 
> print(response.text)
> 
> ### پاسخ دریافتی
> خطای درخواست TOTP
> 
> ### اطلاعات تکمیلی
> برای دریافت توکن از طریق API از کد پایتون شما استفاده کردم ولی برای TOTP مقدار صحیح را نیاز دارم. در حالی که من رمز یکبارمصرف شناسایی دوعاملی را فعال نکردم. ممنون می شم راهنمایی کنید. داخل لینک زیر در مورد مقدار TOTP صحبتی نشده متاسفانه: https://documenter.getpostman.com/view/5722122/Szmcayjw#8f23dbb6-4899-4b64-9ee1-ac7024e7944d

این کد رو خودتون میتونین با کتابخونه های مرتبط تولید کنین، مثلاً در nodejs کتابخونه totp-generator به سادگی میتونه کد رو براتون تولید کنه:
const totp = require("totp-generator");
let code = totp("x654xdf4dx45fd564xf56d4xf56d4x6");

توی پایتون هم حتماً کتابخونه مشابهی وجود داره. سرچ کنید، گوگل بهتر و سریع تر از من یا دیگران شما رو به نتیجه میرسونه!

**Comment by z-amini** [comment]
با سلام و احترام.

برای لاگین وجود captcha یا دوعاملی جهت تامین امنیت حساب ضروریه. در استفاده مستقیم از API کپچا وجود نداره و به همین دلیل، فعال‌سازی شناسایی دوعاملی برای لاگین با API اجباری هست.

همین طور که دوست مون هم اشاره کردن، کتابخونه‌های زیادی هستن که این امکان رو براتون فراهم می‌کنن.
مثل https://pyauth.github.io/pyotp/

در زمان فعال کردن دوعاملی یه رشته به شما داده میشه که باید ورودی این کتابخونه، قرار بگیره.

امیدوارم مشکل تون برطرف شده باشه.
