### ISSUE TITLE
[پشتیبانی]: ایجاد امکان تبدیل ریال به سایر ارزها 

### ISSUE THREAD

**Issue by drwatson878** [nobitex/docs-api#235]
### نیازمندی

متاسفانه در معاملات اسپات و در لیست ارزهای مبدا گزینه ریال وجود ندارد که محدودیت زیادی در کار با api ایجاد میکند لطفا ارز ریال رو به ارزهای مبدا  اضافه بفرمایید باتشکر

### راه‌حل

اضافه کردن ارز ریال به ارزهای مبدا  درمعاملات

**Comment by z-amini** [comment]
با سلام و احترام.
روز شما بخیر.

در یک بازار، برای مثال، بازار دوج-ریال، شما امکان تبدیل دوج به ریال و ریال به دوج رو خواهید داشت. به این صورت که کاربرهایی که می‌خوان دوج دریافت کنن، در این بازار سفارش خرید دوج ثبت می‌کنند و کاربرهایی که می‌خوان دوج رو به ریال تبدیل کنن، سفارش فروش دوج ثبت می‌کنند.
معامله بین این دو جهت مخالف سفارش گذاری یعنی تقاضای خرید و فروش انجام میشه.

دقت کنید توی هر بازار، بخش اول ارز مبدا و بخش دوم ارز دوم هست. شما با کمک ریال می‌تونید رمزارزهای زیادی رو در بازارهای ریالی نوبیتکس خریداری کنید.
کافیه در [API ثبت سفارش نوبیتکس](https://apidocs.nobitex.ir/#e12b63a512)، پارامتر ورودی type سفارش رو sell قرار بدید.

امیدوارم سوال تون برطرف شده باشه.
