### ISSUE TITLE
عدم دسترسی هاست به api [پشتیبانی]: 

### ISSUE THREAD

**Issue by amintjf1** [nobitex/docs-api#237]
### هدف

حقیقت من برنامه نویس هستم و میخواستم از api نوبیتکس استفاده کنم تمام کار ها رو انجام دادم به درستی اما هاست مشکل داشت به مدیریت هاست تیکت دادم جواب دادن: از پشتیبان نوبیتکس درخواست نمایید دسترسی از مبدا آی پی 81.171.18.78 و 81.171.18.89 را مجاز نمایند. در حال حاضر دسترسی ping و همچنین برقراری ارتباط با پورت 80 و 443 از سرور و به این آدرس وجود ندارد.
ممنون میشم این مورد رو پیگیری کنید!

### محیط درخواست

- ابزار درخواست (مرورگر/ابزار/برنامه/...)
- زبان برنامه (cURL/Python/PHP/...)
- محل درخواست (local/VPS/...)
- درخواست IP (داخلی/خارجی)
- ...

### نحوه درخواست

 $arz = json_decode(file_get_contents("https://api.nobitex.ir/v2/orderbook/TONUSDT"),true);
   $name= $arz['lastTradePrice'];
  print_r("arz :  $name");

### پاسخ دریافتی

هاست اصلا بالا نمیاره

**Comment by amiraliakbari** [comment]
سلام، برای بررسی دقیق‌تر لازم است که شرح دقیق خطای دریافتی (مثلاً خروجی دستور curl -v یا ...) ارائه شود. گزارش فعلی شامل جزئیات لازم برای بررسی موضوع نیست. پس از ارائه توضیحات و مستندات کافی، مورد شما به پروایدر CDN (ابرآروان) ارجاع می‌شود و جواب پروایدر برای شما ارسال خواهد شد.
