### ISSUE TITLE
[خطا]: 

### ISSUE THREAD

**Issue by validkhalafy** [nobitex/docs-api#239]
### شرح خطا

socket.create_connection(("nobitex.ir", 80))
   در پایتون             
با این کد کانکشن نوبیتکس رو بررسی میکردم همیشه ، ولی امروز کانکشن قطع بود کاملا ، یکبار همچین مشکلی قبلا برام پیش اومد که متوجه شدم لینک تغییر پیدا کرده 
فرم لینک هایی که ارسال میشدند ، به این شکل هستند . 
 link = "https://api.nobitex.ir/market/orders/status/....
به مدت چند ماهه که این ها جوابگوی من بودند ، آیا لینک ها تغییر کردند ؟

### جزئیات درخواست

1. آدرس: `POST /sample/url`
2. داده:
    - key1: value1
    - key2: value2
    - ...
3. هدر:
    - Authorization: yes
    - ...
4. محیط:
    - تست‌نت
    - اصلی

### پاسخ دریافتی

.

### پاسخ مورد انتظار

.

### پیوند مراجع

.

### اطلاعات تکمیلی

.

**Comment by rbabaee** [comment]
سلام. لطفا توضیحاتتون رو در مورد مشکلی که پیدا شده کامل تر کنید و کد رو کامل ارسال کنید (مواظب باشید که کلید ای پی آی و ... توش نباشه). و لطفا، بگید که چه اروری دارید دریافت میکنید.
