### ISSUE TITLE
دیتا

### ISSUE THREAD

**Issue by faxrali** [nobitex/docs-api#24]
سلام 
آیا کد جداگانه ای برای دیتا های صفحه اول سایت که فقط قیمت های best buy  و best sell رو نشون میده دارید؟
در حال حاضر api موجود برای هر رمزارز پارامتر های خیلی زیادی رو ارایه میده که البته کاربردهای خودشو داره اما زمانبر هستش
و همچنین برنامه هایی مثل متلب برای استفاده از دیتای جاوای سایت دارای مشکل هستن و پس از باز کردن فرمت جاوای صفحه اصلی با عنوان آزمایشی نمایش داده میشه و تمام فیلدهای جدول خالی نمایش داده میشن
یه سوال دیگه هم اینکه آیا کدهای سایت به جز در فرمت جاوا در فرمت های https و css و php و غیره در دسترس هست یا نه
ممنون میشم راهنمایی کنید

**Comment by mheidarian** [comment]
سلام @faxrali عزیز
خیر، فرمت های مورد نظر موجود نمی  باشد.
شما میتوانید از سرویس های موجود در [این آدرس](https://apidocs.nobitex.ir/) برای پیاده سازی صفحات خود استفاده نمائید
