### ISSUE TITLE
مشکل لاگین با ای‌پی‌آی بعد از فعال کردن احراز هویت دو مرحله ای

### ISSUE THREAD

**Issue by mhrj94** [nobitex/docs-api#25]
با سلام. ورود دومرحله ای مشکلی دارد. بعد از فعال کردن این ویژگی دیگر نمی توان با ای‌پی‌آی لاگین کرد زیرا امکان فرستادن رمز یکبار مصرف از این طریق وجود ندارد. لاگین با خطای 400 مواجه می شود و این خروجی را دارد:
array (size=2)
  'non_field_errors' => 
    array (size=1)
      0 => string 'OTP not provided' (length=16)
  'code' => string 'MissingOTP' (length=10)

تلاش کردم که رمز یکبار مصرف را از طریق ای‌پی‌آی هم بفرستم اما به هیچ شکلی مورد قبول واقع نشد. در آینده که احراز هویت دو مرحله‌ای «اجباری» خواهد شد این مشکل باعث عدم دسترسی به پلتفرم از طریق ای‌پی‌آی خواهد شد

**Comment by mheidarian** [comment]
نکته به جایی بود. انجام شد
https://github.com/nobitex/docs-api/commit/1b45f20b8849079687ba417087b21ba6968b6ad3
ممنون
