### ISSUE TITLE
[خطا]: جابجا بودن مقادیر bids و asks در سرویس orderbook

### ISSUE THREAD

**Issue by aminte** [nobitex/docs-api#254]
### شرح خطا

سلام وقت بخیر
مطابق تعریف bid عبارت است از بیشترین قیمتی که خریداران برای خرید اعلام میکند و ask عبارت است از کمترین قیمتی که فروشندگان اعلام می کنند. یعنی bids لیست خریداران هستند و asks لیست فروشندگان ولی در سرویس orderbook این دو جا بجا ارسال می شود.
معمولا قیمت خرید کمتر از قیمت فروش است و با مشاهده جواب سرویس جا به جا بودن این دو قابل تشخیص است.

### جزئیات درخواست

https://api.nobitex.ir/v2/orderbook/BTCUSDT

### پاسخ دریافتی

{"status":"ok","lastUpdate":1726645109635,"lastTradePrice":"60175","**asks**":[["60002","0.020644"],["60001","0.008403"],["59965.98","0.00105"],["59965.97","0.013091"],["59965.58","0.085015"],["59915","0.000083"],["59909.71","0.002969"],["59909.29","0.000083"],["59909","0.050824"],["59900.91","0.00073"],["59900.01","0.003005"],["59895","0.000086"],["59862","0.000083"],["59802","0.02517"],["59800","0.017049"],["59765","0.000083"],["59702.78","0.000784"],["59702.77","0.010489"],["59701.77","0.003349"],["59700","0.002988"],["59650","0.000124"],["59639.99","0.003077"],["59605","0.000084"],["59568","0.000217"]],"**bids**":[["60175","0.053272"],["60189.99","0.00044"],["60190","0.000111"],["60195","0.00902"],["60196","0.000191"],["60199","0.001656"],["60200","0.018076"],["60215","0.000083"],["60247.99","0.00032"],["60250","0.002149"],["60293.98","0.0003"],["60295","0.000083"],["60299.99","0.046993"],["60300","0.004283"],["60315","0.000207"],["60343","0.002051"],["60343.83","0.000253"],["60348.99","0.19"],["60349","0.010779"],["60355","0.000083"],["60387.78","0.009335"],["60395","0.000082"],["60400","0.000213"],["60415","0.000082"]]}

### پاسخ مورد انتظار

{"status":"ok","lastUpdate":1726645109635,"lastTradePrice":"60175","**bids**":[["60002","0.020644"],["60001","0.008403"],["59965.98","0.00105"],["59965.97","0.013091"],["59965.58","0.085015"],["59915","0.000083"],["59909.71","0.002969"],["59909.29","0.000083"],["59909","0.050824"],["59900.91","0.00073"],["59900.01","0.003005"],["59895","0.000086"],["59862","0.000083"],["59802","0.02517"],["59800","0.017049"],["59765","0.000083"],["59702.78","0.000784"],["59702.77","0.010489"],["59701.77","0.003349"],["59700","0.002988"],["59650","0.000124"],["59639.99","0.003077"],["59605","0.000084"],["59568","0.000217"]],"**asks**":[["60175","0.053272"],["60189.99","0.00044"],["60190","0.000111"],["60195","0.00902"],["60196","0.000191"],["60199","0.001656"],["60200","0.018076"],["60215","0.000083"],["60247.99","0.00032"],["60250","0.002149"],["60293.98","0.0003"],["60295","0.000083"],["60299.99","0.046993"],["60300","0.004283"],["60315","0.000207"],["60343","0.002051"],["60343.83","0.000253"],["60348.99","0.19"],["60349","0.010779"],["60355","0.000083"],["60387.78","0.009335"],["60395","0.000082"],["60400","0.000213"],["60415","0.000082"]]}

### پیوند مراجع

The term "bid" refers to the highest price a buyer will pay to buy a specified number of shares of a stock at any given time.  The term "ask"  refers to the lowest price at which a seller will sell the stock.

The bid price will almost always be lower than the ask or “offer,” price.  The difference between the bid price and the ask price is called the "spread."

**Comment by itismoej** [comment]
سلام؛ از ورژن v3 استفاده کنید. این ورژن به‌دلیل backward compatibility به همین شکل باقی خواهد ماند. نمونه درخواست:

```shell
curl https://api.nobitex.ir/v3/orderbook/BTCUSDT
```
