### ISSUE TITLE
[خطا]: مشکل در اتصال به وب سوکت

### ISSUE THREAD

**Issue by Mostafa-Abbasinejad** [nobitex/docs-api#259]
### شرح خطا

پس از نصب پکیج centrifuge (NodeJS) و تلاش برای اتصال به وب سوکت، خطای زیر مشاهده میشه:
```
Error: WebSocket not available
    at Centrifuge._initializeTransport (\node_modules\centrifuge\build\index.js:2552:27)
```
با نصب پکیج های websocket یا ws هم مشکل برطرف نمیشه، آیا برای استفاده از این پکیج، ملزومات خاص یا نسخه خاصی (غیر از 5.2.2) مد نظر هست؟ 
کسی به این مشکل برخورد نکرده؟
![cent _err](https://github.com/user-attachments/assets/7aaecee6-4eae-4fbf-aa55-03d589732c70)

### جزئیات درخواست

```javascript
const { Centrifuge } = require('centrifuge');

const client = new Centrifuge('wss://ws.nobitex.ir/connection/websocket', {});
client.on('connected', (ctx) => {
    console.log('connected', ctx);
});
client.connect();
``` 
4. محیط:
    - تست‌نت
    - اصلی

### پاسخ دریافتی

throw new Error('WebSocket not available');
                    ^

Error: WebSocket not available
    at Centrifuge._initializeTransport (\node_modules\centrifuge\build\index.js:2552:27)

### پاسخ مورد انتظار

اتصال سوکت

**Comment by Mostafa-Abbasinejad** [comment]
متأسفانه در داکیومنت api نوبیتکس ذکر نشده که باید آبجکت websocket به صورت دستی به centrifuge پاس داده بشه، یا به صورت گلوبال تعریف بشه، 
چون راه حل رو پیدا کردم، اینجا میذارم شاید به درد بقیه دوستان هم بخوره:
روش صحیح استفاده از وب سوکت نوبیتکس: 

```javascript
const { Centrifuge } = require('centrifuge');
const WebSocket = require('ws'); // or define WebSocket in global scope using global.WebSocket = require('ws');

const client = new Centrifuge('wss://ws.nobitex.ir/connection/websocket', {
    debug: true,
    websocket: WebSocket // pass custom WebSocket implementation
});

client.on('connected', (ctx) => {
    console.log('connected', ctx);
});

client.connect();
```  
![image](https://github.com/user-attachments/assets/b74800fe-3693-4289-b82b-cf19054fb91b)

**Comment by itismoej** [comment]
مصطفی جان ممنون از اینکه اطلاع دادی؛
در مستندات نوبیتکس علاوه‌بر **nodejs**، مثال‌هایی برای استفاده از SDK در بقیه‌ی زبان‌ها (مثل پایتون، جاوا و...) هم تدارک دیده نشده و فرض بر مطالعه‌ی مستندات خود SDK هست. به‌طور خاص در این مورد، [این قسمت از مستندات](https://github.com/centrifugal/centrifuge-js?tab=readme-ov-file#using-with-nodejs) به استفاده از SDK در محیط **nodejs** اشاره کرده.

حتماً سعی می‌کنیم مستندات رو واضح‌تر و کامل‌تر کنیم.
موفق باشید.
