### ISSUE TITLE
[خطا]: مشکل در مستندات مربوط به وبسوکت

### ISSUE THREAD

**Issue by mrk24251** [nobitex/docs-api#263]
### شرح خطا

سلام و عرض ادب
برای اتصال به وبسوکت نوبیتکس از کتابخانه Websockets ( کتابخانه پایه ای Centrifugo) و خود Centrifugo استفاده کردم.
در قسمت وبسکوت داکیومنت، دو قسمت وجود دارد. قسمت مربوط به کاربران Centrifugo و قسمت مربوط به کابران سایر کتابخانه ها:
در اتصال ping/pong، برای هر دو دسته کاربر، اتصال به راحتی برقرار می گردد.
اما برای کانال orderbook، تنها با استفاده از Centrifugo اتصال برقرار می گردد و هنگامی که اطلاعات 
 

```
>          {
>             "id": 2,
>             "subscribe": {
>               "channel": "public:orderbooks-USDTIRT"
>             }
>           }
```

با استفاده از کتابخانه Websockets ارسال می گردد، با خطای bad request مواجه می شویم.
به نظر می آید که داده های درج شده در مستندات برای اتصال با سایر کتابخانه ها درست نیست.
میشه بررسی بفرمایید؟

### جزئیات درخواست

1. آدرس: 
  ```
    async with websockets.connect("wss://ws.nobitex.ir/connection/websocket", ssl=ssl_context) as websocket:
        await websocket.send(json.dumps(
          {
            "id": 2,
            "subscribe": {
              "channel": "public:orderbooks-USDTIRT"
            }
          }
        ))
        j = 1
        while True:
          message = await websocket.recv()
          results = json.loads(message)
          print("rrrrrrrrrr", results)
```

2. داده:

```
>           {
>             "id": 2,
>             "subscribe": {
>               "channel": "public:orderbooks-USDTIRT"
>             }
>           }
```

3. هدر:
No
4. محیط:
    - اصلی

### پاسخ دریافتی

3501 (registered) bad request; then sent 3501 (registered) bad request

### پاسخ مورد انتظار

با استفاده از Centrifugo، این داده ها بدست می آید.
`{"push":{"channel":"public:orderbook-BTCIRT","pub":{"data":{"asks":[["39575653000","0.107876"],["39599999990","0.000054"],["39600000000","0.044219"],["39609880000","0.010503"],["39609889990","0.003795"],["39610000000","0.001238"],["39620000000","0.01062"],["39632408090","0.00009"],["39632408100","0.002775"],["39634203400","0.0005"],["39657085150","0.00088"],["39659999950","0.17"],["39660000000","0.000176"],["39663999620","0.005033"],["39663999630","0.012605"],["39665000000","0.001348"],["39669999880","0.006983"],["39669999980","0.000802"],["39670000000","0.005805"],["39679999990","0.000205"],["39680000000","0.011404"],["39687240000","0.000628"],["39700000000","0.015069"],["39707589270","0.0005"]],"bids":[["39511124010","0.002285"],["39511124000","0.00859"],["39511024000","0.005892"],["39510011110","0.000175"],["39510008880","0.000253"],["39510001160","0.006654"],["39510000160","0.003007"],["39510000110","0.009028"],["39510000020","0.009578"],["39510000000","0.073402"],["39509140050","0.000579"],["39509100000","0.000071"],["39509005740","0.030707"],["39500010000","0.000038"],["39500000220","0.007839"],["39500000000","0.028715"],["39499999000","0.006462"],["39499890770","0.00009"],["39490000000","0.000019"],["39485000010","0.001012"],["39480232390","0.00019"],["39480000000","0.006584"],["39477278050","0.012753"],["39470000270","0.00068"]],"lastTradePrice":"39575653000","lastUpdate":1727605432428},"offset":67431}}
`

### پیوند مراجع

https://apidocs.nobitex.ir/#websocket-orderbook

### اطلاعات تکمیلی

در تمامی موارد ذکر شده از پایتون استفاده شده است

**Comment by itismoej** [comment]
سلام؛ ابتدا باید از پیام `connect` استفاده کنید:

```python
import asyncio
import websockets
import json

async def websocket_client():
    uri = "wss://ws.nobitex.ir/connection/websocket"
    async with websockets.connect(uri) as websocket:
        # Send connection request
        connect_request = json.dumps({"connect": {"name": "py"}, "id": 1})
        await websocket.send(connect_request)
        print(f"Sent: {connect_request}")

        # Wait for and print the response
        response = await websocket.recv()
        print(f"Received: {response}")

        # Send subscription request
        subscribe_request = json.dumps({"subscribe": {"channel": "public:orderbook-USDTIRT"}, "id": 2})
        await websocket.send(subscribe_request)
        print(f"Sent: {subscribe_request}")

        # Continuously receive messages
        while True:
            message = await websocket.recv()
            print(f"Received: {message}")

async def main():
    await websocket_client()

if __name__ == "__main__":
    asyncio.run(main())
```

البته اجرای کد بالا به‌علت نبود مکانیزم ping pong بعد از ۲۵ ثانیه قطع خواهد شد. این مورد رو خودتون اضافه کنید.

ممنون از گزارش‌تون؛ این مورد رو حتماً در مستندات اضافه خواهیم کرد.

**Comment by itismoej** [comment]
سلام من چک کردم و از قبل در مستندات اشاره شده بود:

![image](https://github.com/user-attachments/assets/663c3336-3ef7-4fac-9530-837fab915324)
