### ISSUE TITLE
قیمت انجام معامله

### ISSUE THREAD

**Issue by mahdi124710** [nobitex/docs-api#28]
![nobitex](https://user-images.githubusercontent.com/36361539/102111603-ddd31680-3e4b-11eb-874c-5eecabd55207.png)

سلام
متن رو توی عکس ارسالی وارد کردم. انشالا که عکس به درست آپلود شده باشه:)
سپاس

**Comment by mheidarian** [comment]
سلام @mahdi124710  عزیز
این مساله را بررسی خواهیم کرد و در صورت نیاز، اصلاحات لازم انجام و اطلاع رسانی خواهد شد
با تشکر

**Comment by z-amini** [comment]
سلام مجدد و عرض ادب.

طی یک سال گذشته نحوه مچ شدن معاملات تغییرات و بهبودهایی داشته که گمان می‌کنیم موردی که بهمون گزارش کردید، به طور کلی رفع شده باشه.
در صورت مشاهده مجدد چنین مواردی خوشحال میشیم ما رو هم در جریان بگذارید.
از همراهی و دلسوزی تون سپاس‌گزاریم.
