### ISSUE TITLE
Order book مشکل در ریسپانس لیست سفارشات 

### ISSUE THREAD

**Issue by aminsoheyli** [nobitex/docs-api#29]
![nobi](https://user-images.githubusercontent.com/42641117/102532335-11ff3f00-40b9-11eb-9e65-01c1dd47b1cd.PNG)

[Binance API/order book](https://binance-docs.github.io/apidocs/spot/en/#order-book)
[Coinex API/market depth](https://github.com/coinexcom/coinex_exchange_api/wiki/022depth)

**Comment by mheidarian** [comment]
سلام @aminsoheyli عزیز
این مورد رو بررسی خواهیم کرد و اگر نیازی به اصلاحات داشت، انجام و اطلاع خواهیم داد
با تشکر
