### ISSUE TITLE
Wallets list endpoint returns status:failed error

### ISSUE THREAD

**Issue by sinarezaei** [nobitex/docs-api#30]
اندپوینت برای دریافت کیف پولها
https://api.nobitex.ir/users/wallets/list

تقریبا در نیمی از درخواست های ارسال شده خطای 
{"status":"failed"}
باز میگرداند. در بقیه موارد به درستی جواب می دهد

**Comment by mheidarian** [comment]
سلام @sinarezaei عزیز
در برخی از موارد به دلیل کنترل بار ترافیک ورودی این سرویس، ممکن است پاسخ مورد انتظار دریافت نگردد، در این حالت می بایست مجددا فراخوانی را انجام داد و یا اینکه از [این سرویس](https://apidocs.nobitex.ir/#1ff004071d) برای دریافت لیست کیف پول ها استفاده نمائید
