### ISSUE TITLE
حالت تست

### ISSUE THREAD

**Issue by mohammadyacn314** [nobitex/docs-api#31]
با سلام . برای بررسی استراتژی ها و روش های خرید و فروش نیاز به حالت تست می باشد که مثلا اگر اردر مارکتی با فیلد حالت تست ارسال شد  پاسخی بتوان دریافت کرد که فلان مقدار با فلان قیمت که میخواستید در همین لحظه به شما فروخته شد تا بشه . 
 درصورتی که اصلا خرید واقعی انجام نشد و سرور شما صرفا با فرض اینکه خرید انجام شد جوابی فرستاد

**Comment by mheidarian** [comment]
سلام @mohammadyacn314 عزیز 
برای اینکار میتوانید از شبکه ی تستی نوبیتکس از [این آدرس](https://testnet.nobitex.ir) و برای استفاده از سرویس های این شبکه از [این آدرس](http://testnetapi.nobitex.ir) استفاده نمائید.

**Comment by sirousjj** [comment]
> سلام @mohammadyacn314 عزیز
> برای اینکار میتوانید از شبکه ی تستی نوبیتکس از [این آدرس](https://testnet.nobitex.ir) و برای استفاده از سرویس های این شبکه از [این آدرس](http://testnetapi.nobitex.ir) استفاده نمائید.

آدرس مربوط به ای پی آی برای محیط تست نت هیچ محتوایی داخلش نیست.
لطفا بررسی کنید اگه مشکلی داره حل کنید.

**Comment by sirousjj** [comment]
برای استفاده از ای پی آی در محیط تست، چه توکنی رو باید پاس بدیم؟
داخل پنل محیط تست ، امکان ایجاد توکن نیست.
