### ISSUE TITLE
مشکل دریافت قیمت

### ISSUE THREAD

**Issue by sirmrm** [nobitex/docs-api#32]
من آدرس زیر فرآخوانی میکنم
https://api.nobitex.ir/v2/trades?symbol=USDTIRT
خروجی به صورت زیره
            "time": 1609495140580,
            "price": "7.72000000E+9",
            "volume": "0.000389",
            "type": "buy"
قیمت با چه فرمتی هستش؟؟؟؟

**Comment by mmmce1994** [comment]
فرمتی که دارید فراخوانی می کنید درست نیست.
نماد بازار نباید به صورت کوئری استرینگ ارسال بشه
https://apidocs.nobitex.ir/#3fe8d57657
با فرض اینکه درست فراخوانی کنید، قیمت به صورت ریالی خواهد بود
