### ISSUE TITLE
خطای Missing Captcha'

### ISSUE THREAD

**Issue by AmirAslanHaghrah** [nobitex/docs-api#33]
من به کمک پایتون قصد لاگین به کمک رابط نوبیتکس را داشتم که با خطای زیر مواجه شدم:

{'non_field_errors': ['Missing Captcha'], 'code': 'MissingCaptcha'}

کد مورد استفاده:

```
import requests 
  
# api-endpoint 
URL = 'https://api.nobitex.ir/auth/login/'
  
# location given here 
username = 'test@test.com'
password = 'test1234'
  
# defining a params dict for the parameters to be sent to the API 
data = {'username':username, 'password':password, 'remember':'no'} 

  
# sending get request and saving the response as response object 
r = requests.post(url=URL, json=data) 
print (r.request.headers)

# extracting data in json format 
data = r.json() 
print(data)
```

**Comment by shahrdoost** [comment]
من هم به همین مشکل برخوردم
و منتظر جوابم

**Comment by sarafth98** [comment]
بله منم با پستمن رکوئست فرستادم همین ارور رو گرفتم

**Comment by sarafth98** [comment]
دوستان اگر راه حل رو پیدا کردین، لطفا به اشتراک بذارید

**Comment by shahrdoost** [comment]
متاسفانه راه حل از طرف ما وجود نداره 
چون نوبیتکس تغییر داده بکندشو
چاره ای جز ایمیل زدن بهشون نیست

**Comment by sarafth98** [comment]
ممنون، چون در داکیومنت نوشته بود مشکلات اینجا مطرح بشه فکر میکردم این حساب دولوپر بکنده سایته

**Comment by aghapesar1374** [comment]
این طور که من سرچ کردم خطای کپچا مربوط میشه به نحوه ارسال  قرار گیری پسورد و یوزر هست https://stackoverflow.com/questions/52416002/recaptcha-error-codes-missing-input-response-missing-input-secret-when-v

**Comment by alizabetpoor** [comment]
وقتی header رو اضافه کنید این مشکل برطرف میشه ولی به این ارور بر میخورید
{"detail":"JSON parse error - Expecting value: line 1 column 1 (char 0)"}

**Comment by miladh9** [comment]
> این طور که من سرچ کردم خطای کپچا مربوط میشه به نحوه ارسال قرار گیری پسورد و یوزر https://stackoverflow.com/questions/52416002/recaptcha-error-codes-missing-input-response-missing-input-secret-when-v

چون صفحه رو مستقیم کرل نمیکنیم و ارتباط ما از طریق
api
هست در نتیجه نحوه قرار گیری آیتم ها و تعریف
nodevalue ها نیازی نیست.

دوستان اگر مشکلتون رو برطرف کردید یا پشتیبانی در جهت رفع این خطای جدید راهنماییتون کرده نتیجه رو به اشتراک بگذارید.

**Comment by shahrdoost** [comment]
دوستان پشتیبانی نوبیتکس در جواب ایمیل من که در رابطه با این مشکل بود این جواب رو دادن

![qwgqwgqwg](https://user-images.githubusercontent.com/77006690/104999956-f6ce7900-5a42-11eb-984f-2cb9246c652d.png)


اما متاسفانه من از روش اول جوابی نگرفتم و همون ارور قبلو میده ولی روش دوم عمل میکنه منتهی هر 2 ساعت تغییر میکنه

**Comment by sarafth98** [comment]
> دوستان پشتیبانی نوبیتکس در جواب ایمیل من که در رابطه با این مشکل بود این جواب رو دادن
> 
> ![qwgqwgqwg](https://user-images.githubusercontent.com/77006690/104999956-f6ce7900-5a42-11eb-984f-2cb9246c652d.png)
> 
> اما متاسفانه من از روش اول جوابی نگرفتم و همون ارور قبلو میده ولی روش دوم عمل میکنه منتهی هر 2 ساعت تغییر میکنه

خیلی ممنون . روش اول هم جواب داد

**Comment by shahrdoost** [comment]
من همین الان با پست من روش اول رو تست کردم ولی بازم این ارور رو بهم داد
{
    "non_field_errors": [
        "Missing Captcha"
    ],
    "code": "MissingCaptcha"
}
میشه با جزیات بفرمایید که چه جوری براتون جواب داد

**Comment by sarafth98** [comment]
> من همین الان با پست من روش اول رو تست کردم ولی بازم این ارور رو بهم داد
> {
> "non_field_errors": [
> "Missing Captcha"
> ],
> "code": "MissingCaptcha"
> }
> میشه با جزیات بفرمایید که چه جوری براتون جواب داد
من اول این درخواست رو تست کردم درست بود

```
{
    "username": "user@gmail.com",
    "password": "password1234",
    "captcha" : "api"
}
```

اما الان این ارور رو گرفتم
```
{
    "detail": "CSRF Failed: Referer checking failed - no Referer."
}
```

**Comment by sarafth98** [comment]
> > من همین الان با پست من روش اول رو تست کردم ولی بازم این ارور رو بهم داد
> > {
> > "non_field_errors": [
> > "Missing Captcha"
> > ],
> > "code": "MissingCaptcha"
> > }
> > میشه با جزیات بفرمایید که چه جوری براتون جواب داد
> 
> من اول درخواست رو با این بادی تست کردم درست بود
> 
> ```
> {
>     "username": "user@gmail.com",
>     "password": "password1234",
>     "captcha" : "api"
> }
> ```
> 
> اما الان این ارور رو گرفتم
> 
> ```
> {
>     "detail": "CSRF Failed: Referer checking failed - no Referer."
> }
> ```

البته این مشکلم با اضافه کردن کوکی زیر فعلا حل شده

`Cookie: __cfduid=ddf02; csrftoken=exbUjjT51K; sessionid=44dwmxpp`

**Comment by shahrdoost** [comment]
> 
> 
> > من همین الان با پست من روش اول رو تست کردم ولی بازم این ارور رو بهم داد
> > {
> > "non_field_errors": [
> > "Missing Captcha"
> > ],
> > "code": "MissingCaptcha"
> > }
> > میشه با جزیات بفرمایید که چه جوری براتون جواب داد
> 
> من اول درخواست رو با این بادی تست کردم درست بود
> 
> ```
> {
>     "username": "user@gmail.com",
>     "password": "password1234",
>     "captcha" : "api"
> }
> ```
> 
> اما الان این ارور رو گرفتم
> 
> ```
> {
>     "detail": "CSRF Failed: Referer checking failed - no Referer."
> }
> ```

شما با سرور داخل ایران تست کردید ؟

**Comment by sarafth98** [comment]
> > > من همین الان با پست من روش اول رو تست کردم ولی بازم این ارور رو بهم داد
> > > {
> > > "non_field_errors": [
> > > "Missing Captcha"
> > > ],
> > > "code": "MissingCaptcha"
> > > }
> > > میشه با جزیات بفرمایید که چه جوری براتون جواب داد
> > 
> > 
> > من اول درخواست رو با این بادی تست کردم درست بود
> > ```
> > {
> >     "username": "user@gmail.com",
> >     "password": "password1234",
> >     "captcha" : "api"
> > }
> > ```
> > 
> > 
> > اما الان این ارور رو گرفتم
> > ```
> > {
> >     "detail": "CSRF Failed: Referer checking failed - no Referer."
> > }
> > ```
> 
> شما با سرور داخل ایران تست کردید ؟

بله

**Comment by sbtunx** [comment]
کوکی csrftoken رو پاک کنید یا تو هدر بفرستید

**Comment by mahyarnzi** [comment]
> > > > من همین الان با پست من روش اول رو تست کردم ولی بازم این ارور رو بهم داد
> > > > {
> > > > "non_field_errors": [
> > > > "Missing Captcha"
> > > > ],
> > > > "code": "MissingCaptcha"
> > > > }
> > > > میشه با جزیات بفرمایید که چه جوری براتون جواب داد
> > > 
> > > 
> > > من اول درخواست رو با این بادی تست کردم درست بود
> > > ```
> > > {
> > >     "username": "user@gmail.com",
> > >     "password": "password1234",
> > >     "captcha" : "api"
> > > }
> > > ```
> > > 
> > > 
> > > اما الان این ارور رو گرفتم
> > > ```
> > > {
> > >     "detail": "CSRF Failed: Referer checking failed - no Referer."
> > > }
> > > ```
> > 
> > 
> > شما با سرور داخل ایران تست کردید ؟
> 
> بله

اگر cookieها رو پاک کنید این مشکل بوجود نمیاد و این روش فقط با ip های داخل کشور کار می کنه.

**Comment by mahyarnzi** [comment]
> دوستان پشتیبانی نوبیتکس در جواب ایمیل من که در رابطه با این مشکل بود این جواب رو دادن
> 
> ![qwgqwgqwg](https://user-images.githubusercontent.com/77006690/104999956-f6ce7900-5a42-11eb-984f-2cb9246c652d.png)
> 
> اما متاسفانه من از روش اول جوابی نگرفتم و همون ارور قبلو میده ولی روش دوم عمل میکنه منتهی هر 2 ساعت تغییر میکنه

هدرتون بدون کوکی باشه درست جواب میده

**Comment by rrbroe** [comment]
سلام یه من این خطا رو داد چیکار کنم
Login failed. Status code: 405
Error message: {'detail': 'متد GET مجاز نیست.'}
(.venv) PS C:\Users\reza\Desktop\p>
