### ISSUE TITLE
خطای کپچا برای لاگین

### ISSUE THREAD

**Issue by sajadhashemi** [nobitex/docs-api#35]
با سلام در زمان ارسال درخواست جهت لاگین  خطای کپچا برگشت داده میشه

**Comment by DelphiMan68** [comment]
آیا مشکلتون رو تونستید حل کنید؟ اگه موفق شدین میتونین توضیح بدین؟ منم دقیقاً همین مشکل رو دارم

**Comment by mheidarian** [comment]
سلام
میتونید از پنل کاربری نوبیتکس، بخش تنظیمات توکن را به صورت دستی دریافت کنید و یا اینکه
کافیه یک پارامتر دیگه به شکل زیر برای دریافت توکن ارسال کنید 
captcha=api
