### ISSUE TITLE
Candlestick Resolution

### ISSUE THREAD

**Issue by farahmand-m** [nobitex/docs-api#37]
<p dir=rtl>
وقتتون بخیر.
برای نوشتن بات‌های موثر در نوسان‌گیری به دقت بالاتری در تحلیل بازار نیازه. اگر امکان دریافت اطلاعات OHLC (Candleها) با Resolutionهای زیر فراهم بشه میشه بات‌هایی برای بازار نوبیتکس مثل بازار Binance آماده کرد:
</p>

`1m`, `3m`, `5m`, `15m`, `30m`

<p dir=rtl>
سعی داشتم با درخواست‌های مرتب و دریافت Tradeها این مقادیر رو خودم محاسبه کنم اما محدودیت‌های تعریف‌شده برای این API رسیدن به Resolutionهای بالا رو غیرممکن می‌کنه.
</p>

**Comment by mheidarian** [comment]
سلام و وقت بخیر
درخواست شما مورد بررسی قرار گرفت و در برنامه های آینده قرار گرفت.
