### ISSUE TITLE
missing captcha problem

### ISSUE THREAD

**Issue by bestheroforever** [nobitex/docs-api#38]
curl 'https://api.nobitex.ir/auth/login/'    -X POST    -H "Content-Type: application/json"    --data $'{"username":"name@example.com","password":"secret-password-1234"}'
{"non_field_errors":["Missing Captcha"],"code":"MissingCaptcha"}

**Comment by miadjalili** [comment]
<img width="814" alt="Screen Shot 2021-02-06 at 9 54 38 PM" src="https://user-images.githubusercontent.com/42786901/107126606-2516da00-68c6-11eb-9d33-cacba4718c00.png">
