### ISSUE TITLE
مشکل در دریافت قیمت ohlc

### ISSUE THREAD

**Issue by keloniton** [nobitex/docs-api#39]
سلام.مبنی بر داکیومنت من میخوام به صورت گت قیمت گشایش،بسته شدن بالا و پایین رو بگیرم اما ارور ۴۰۴ و بد ریکواست میده.کد مشخص و سادس.در ادامه میارم تا اگر ممکنه راهنمایی کنین.مرسی.
$url="https://api.nobitex.ir/market/udf/history/";
$ch = curl_init();
$data = array(
    'symbol' => 'BTCIRT',
    'resolution' => 60,
    'from' => 1562120967,
    'to' =>1562230967,
);
$data = http_build_query($data);
//dd($data);
//dd($params);
curl_setopt($ch, CURLOPT_URL,$url); //Url together with parameters
curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, 'GET' );
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); //Return data instead printing directly in Browser
curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 7); //Timeout after 7 seconds
curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1)");
curl_setopt($ch, CURLOPT_HEADER, 0);

$result = curl_exec($ch);

dd($result);

**Comment by keloniton** [comment]
دوستان کسی اطلاعات نداره که به اشتراک بگذاره؟

**Comment by farahmand-m** [comment]
<p dir=rtl>
Slash اضافه‌ای که انتهای آدرس گذاشتین علت خطای 404ـه.
</p>

**Comment by keloniton** [comment]
مهندس شمادتون رو میگذارین تا بنده بتوانم سوال کنم.بدون اسلش هم من تست کردم
