### ISSUE TITLE
400 Error in Market OHLC

### ISSUE THREAD

**Issue by farahmand-m** [nobitex/docs-api#40]
The following request returns with a 400 (Bad Request) error:

```
curl 'https://api.nobitex.ir/market/udf/history?symbol=BTCIRT&resolution=60&from=1611433800&to=1611477000'
```

The same error occurs with different resolutions, and ranges. Sending an `OPTIONS` request to the endpoint returns the same error! The same request to your internal API endpoints (`api-l.nobitex1.ir`) **did not** fail and returned the expected results.

**Comment by mheidarian** [comment]
Hello dear.
Please try again. This problem has been fixed.
