### ISSUE TITLE
تاریخ

### ISSUE THREAD

**Issue by bestheroforever** [nobitex/docs-api#42]
تاریخ ها چه مبنایی دارند؟

مثلا این عدد یعنی چی؟؟؟1560108600

من میخوام برای 60 روز اخیر رو بگیرم مثلا.نمیدونم چیه این روشش

**Comment by mheidarian** [comment]
ساعت یونیکس Unix Time
یا ساعت پازیکس Posix Time
یکی از مقیاس اندازه‌گیری زمان آنی است. این عدد که تعداد ثانیه‌ها از ساعت ۰۰:۰۰:۰۰ ساعت هماهنگ جهانی اول ژانویه ۱۹۷۰ است، شامل ثانیه‌های کبیسه نمی‌شود. برای زمان‌های قبل از اول ژانویه از اعداد منفی استفاده می‌شود.

به عنوان مثال [۰۱/۰۱/۱۹۷۰ ۰۰:۰۰:۰۰] برابر با صفر (۰) و [۰۱/۰۱/۱۹۷۰ ۰۰:۰۱:۰۰] برابر با شصت(۶۰) است.

فرمول اصلی آن به این صورت می‌باشد تعداد (روزهای گذشته از اول ژانویه ۱۹۷۰) × ۸۶۴۰۰(تعداد ثانیه‌های هر روز)

https://en.wikipedia.org/wiki/Unix_time
