### ISSUE TITLE
مشکل دریافت توکن در Api

### ISSUE THREAD

**Issue by rezazohdi** [nobitex/docs-api#44]
با سلام
در هنگام درخواست توکن پیغام Missing Captcha را بر می گرداند

**Comment by mheidarian** [comment]
سلام 
باید یک پارامتر دیگر به شکل زیر برای دریافت توکن ارسال کنید:
captcha=api

یا از پنل کاربری نوبیتکس، بخش تنظیمات توکن رو به صورت دستی دریافت واستفاده کنید

**Comment by rezazohdi** [comment]
با سلام و احترام
پارامتری که گفته بودین
من با پست من تست کردم خروجی زیر رو میده
{
    "non_field_errors": [
        "Missing Captcha"
    ],
    "code": "MissingCaptcha"
}

**Comment by rezazohdi** [comment]
> 
> 
> سلام
> باید یک پارامتر دیگر به شکل زیر برای دریافت توکن ارسال کنید:
> captcha=api
> 
> یا از پنل کاربری نوبیتکس، بخش تنظیمات توکن رو به صورت دستی دریافت واستفاده کنید

سلام
خیلی ممنون از شما
پارامتری که گفتین با سی شارپ کد زدم درست شد

**Comment by mheidarian** [comment]
> > سلام
> > باید یک پارامتر دیگر به شکل زیر برای دریافت توکن ارسال کنید:
> > captcha=api
> > یا از پنل کاربری نوبیتکس، بخش تنظیمات توکن رو به صورت دستی دریافت واستفاده کنید
> 
> سلام
> خیلی ممنون از شما
> پارامتری که گفتین با سی شارپ کد زدم درست شد

خواهش میکنم.  موفق باشید
