### ISSUE TITLE
Missing Captcha

### ISSUE THREAD

**Issue by iuwa** [nobitex/docs-api#45]
در 
"auth/login/" 
پیام 
'{"non_field_errors":["Missing Captcha"],"code":"MissingCaptcha"}'
دریافت میکنم

**Comment by SC-One** [comment]
دقیقا منم همین مشکلو دارم

**Comment by SC-One** [comment]
> در
> "auth/login/"
> پیام
> '{"non_field_errors":["Missing Captcha"],"code":"MissingCaptcha"}'
> دریافت میکنم

دقیقا همین مشکلو منم دارم
من امروز تصمیم گرفتم یه تست با api شما برم و خب از صبحه علافم کرده این ارور ! مشخصم نیست چرا توی داکیومنتونم چیزی نبود.

**Comment by mheidarian** [comment]
سلام 
برای رفع این مشکل کافیست که در هنگام ارسال درخواست برای گرفتن توکن پارامتری دیگر به شکل زیر ارسال نمائید: 
captcha=api

**Comment by SC-One** [comment]
مرسی بابت این

**Comment by SC-One** [comment]
> سلام
> برای رفع این مشکل کافیست که در هنگام ارسال درخواست برای گرفتن توکن پارامتری دیگر به شکل زیر ارسال نمائید:
> captcha=api

مرسی بابت این
اما مثه اینکه یکی دو تا نیستن مشکلات
فک میکنم یکم پارزرتون مشکل داره اذیت های الکی میکنه
یا داکیومنتتون از پارزر عقبه
:الان میگه
{"non_field_errors":["OTP not provided"],"code":"MissingOTP"}
درحالی که طبق داکیومنتتون من با کلید 
X-TOTP
میفرستم
کلهم که خود سی پلاس پلاس رو مخ هست کد زدنش اینا هم اذیت کنه ادم دیگه رمقی نمیمونه برا کد زدنش :/

**Comment by mheidarian** [comment]
سرویس مشکلی نداره و مجددا تست گردید. در صورتی که احراز هویت دو مرحله ای رو فعال کرده باشید و پارامتر 
X-TOTP
رو هم میفرستید باید به شما جواب بده.
کد زیر را میتوانید در
postman import
کرده و تست کنید
```
curl --location --request POST 'https://api.nobitex.ir/auth/login/' \
--header 'Cookie: __cfduid=d3f1b570e5615b223cb24cced6f10d2a61614372014'\'' \; __cfduid=d727d4fbddc828884f2a793143332d5aa1613231485; csrftoken=G9vL4K1oYT9G1bQCjtoUr8FniIHizLX2a7vzWaBZXRXraJC9PziJikYET6Ss8btz; sessionid=7jo9ktkv2tbzytl8ao7w6b3qdqd4133h' \
--form 'username="your_username"' \
--form 'password="your_password"' \
--form 'remember="yes"' \
--form 'captcha="api"' \
--form 'X-TOTP="123456"'
```
در ضمن توجه داشته باشید که از آی پی ایران درخواست رو بزنید

**Comment by SC-One** [comment]
> سرویس مشکلی نداره و مجددا تست گردید. در صورتی که احراز هویت دو مرحله ای رو فعال کرده باشید و پارامتر
> X-TOTP
> رو هم میفرستید باید به شما جواب بده.
> کد زیر را میتوانید در
> postman import
> کرده و تست کنید
> 
> ```
> curl --location --request POST 'https://api.nobitex.ir/auth/login/' \
> --header 'Cookie: __cfduid=d3f1b570e5615b223cb24cced6f10d2a61614372014'\'' \; __cfduid=d727d4fbddc828884f2a793143332d5aa1613231485; csrftoken=G9vL4K1oYT9G1bQCjtoUr8FniIHizLX2a7vzWaBZXRXraJC9PziJikYET6Ss8btz; sessionid=7jo9ktkv2tbzytl8ao7w6b3qdqd4133h' \
> --form 'username="your_username"' \
> --form 'password="your_password"' \
> --form 'remember="yes"' \
> --form 'captcha="api"' \
> --form 'X-TOTP="123456"'
> ```
> 
> در ضمن توجه داشته باشید که از آی پی ایران درخواست رو بزنید

کوکی چرا با هدر میفرستید :|

**Comment by SC-One** [comment]
> > سرویس مشکلی نداره و مجددا تست گردید. در صورتی که احراز هویت دو مرحله ای رو فعال کرده باشید و پارامتر
> > X-TOTP
> > رو هم میفرستید باید به شما جواب بده.
> > کد زیر را میتوانید در
> > postman import
> > کرده و تست کنید
> > ```
> > curl --location --request POST 'https://api.nobitex.ir/auth/login/' \
> > --header 'Cookie: __cfduid=d3f1b570e5615b223cb24cced6f10d2a61614372014'\'' \; __cfduid=d727d4fbddc828884f2a793143332d5aa1613231485; csrftoken=G9vL4K1oYT9G1bQCjtoUr8FniIHizLX2a7vzWaBZXRXraJC9PziJikYET6Ss8btz; sessionid=7jo9ktkv2tbzytl8ao7w6b3qdqd4133h' \
> > --form 'username="your_username"' \
> > --form 'password="your_password"' \
> > --form 'remember="yes"' \
> > --form 'captcha="api"' \
> > --form 'X-TOTP="123456"'
> > ```
> > 
> > 
> > در ضمن توجه داشته باشید که از آی پی ایران درخواست رو بزنید
> 
> کوکی چرا با هدر میفرستید :|
> 
> {
> "X-TOTP": "code man",
> "password": "ramze man",
> "username": "usere man",
> "captcha": "api"
> }
> این نیست؟
> اینو کامل دادم صد بار صدبارشم میگه:
> {"non_field_errors":["OTP not provided"],"code":"MissingOTP"}

حتی داخل خود سایتم که میگی بهشون کسی براش مهم نیست اخرت ساپورت ×ـ× بسیار عالی

**Comment by SC-One** [comment]
ان شالله کی جواب میدید؟

**Comment by Athleticode** [comment]
این ارور کی میخاد حل بشه؟
'{"non_field_errors":["Missing Captcha"],"code":"MissingCaptcha"}'

**Comment by mheidarian** [comment]
> > سرویس مشکلی نداره و مجددا تست گردید. در صورتی که احراز هویت دو مرحله ای رو فعال کرده باشید و پارامتر
> > X-TOTP
> > رو هم میفرستید باید به شما جواب بده.
> > کد زیر را میتوانید در
> > postman import
> > کرده و تست کنید
> > ```
> > curl --location --request POST 'https://api.nobitex.ir/auth/login/' \
> > --header 'Cookie: __cfduid=d3f1b570e5615b223cb24cced6f10d2a61614372014'\'' \; __cfduid=d727d4fbddc828884f2a793143332d5aa1613231485; csrftoken=G9vL4K1oYT9G1bQCjtoUr8FniIHizLX2a7vzWaBZXRXraJC9PziJikYET6Ss8btz; sessionid=7jo9ktkv2tbzytl8ao7w6b3qdqd4133h' \
> > --form 'username="your_username"' \
> > --form 'password="your_password"' \
> > --form 'remember="yes"' \
> > --form 'captcha="api"' \
> > --form 'X-TOTP="123456"'
> > ```
> > 
> > 
> > در ضمن توجه داشته باشید که از آی پی ایران درخواست رو بزنید
> 
> کوکی چرا با هدر میفرستید :|
> 
> {
> "X-TOTP": "code man",
> "password": "ramze man",
> "username": "usere man",
> "captcha": "api"
> }
> این نیست؟
> اینو کامل دادم صد بار صدبارشم میگه:
> {"non_field_errors":["OTP not provided"],"code":"MissingOTP"}

سلام و عذرخواهی بابت تاخیر. 
اون مورد لازم نیست شما بفرستید

**Comment by mheidarian** [comment]
شما اگه به صورت کد زیر ارسال کنید نباید مشکلی داشته باشید. 
و حتما از آی پی های ایران درخواستتون رو بزنید.
برای امتحان از شبکه ی دیگری هم درخواست رو ارسال کنید مثلا از ایرانسل اگه با ثابت هستید.

```
curl --location --request POST 'https://api.nobitex.ir/auth/login/' \
--form 'username="username"' \
--form 'password="password"' \
--form 'remember="yes"' \
--form 'captcha="api"' \
--form 'X-TOTP="123456"'
```
