### ISSUE TITLE
CORS policy problem

### ISSUE THREAD

**Issue by masoudelahi** [nobitex/docs-api#46]
Hi,
When i try to get token by this:
```
axios({
    method: 'POST',
    url: 'https://api.nobitex.ir/auth/login/',
    data: {
      username: 'masoud1993st@gmail.com',
      password: 'fsV3YKKOw8C2',
    },
})
.then((response) => {
    console.log(response.data);
});
```
Iget this: error:
_### Access to XMLHttpRequest at 'https://api.nobitex.ir/auth/login/' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'https://nobitex.ir' that is not equal to the supplied origin._

**Comment by z-amini** [comment]
با سلام و عرض ادب

استفاده از API های نوبیتکس تنها در بکند سرویس شما امکان پذیر است.

اقدام به فراخوانی endpoint ها از طریق مرورگر منجر به خطای CORS خواهد شد.

در صورتی که سوالتان بر طرف نشده، به ما اعلام نمایید.

با تشکر.

**Comment by masoudelahi** [comment]
سلام
امکانش نیست که شما تو هدر هاتون Access-Control-Allow-Origin رو برابر  '*' ست کنید؟ اینطوری مرورگر دیگه خطای CORS نمیده

**Comment by z-amini** [comment]
با سلام و احترام.

از آنجا که بسیاری از API های نوبیتکس به توکن احتیاج دارند و توکن کاربران نمی‌تواند در اختیار دیگران قرار بگیرد (با استفاده از توکن توسعه‌دهنده به تمام اطلاعات حساب کاربر توسعه دهنده می توان دست یافت و حتی قابلیت معامله و برداشت هم وجود خواهد داشت)، در نتیجه قرار دادن بخش فراخوانی در فرانت سرویس کار صحیحی نیست و مسئله امنیتی ایجاد می‌کند.

فراخوانی API ها بناست از سمت بکند سامانه شما انجام گیرد.

با آرزوی کامیلبی

**Comment by mnwato** [comment]
اگه میشه برای endpoint هایی مثل stats که پابلیک هست اینکار رو بکنید.
