### ISSUE TITLE
ohlc

### ISSUE THREAD

**Issue by kasrakazemi** [nobitex/docs-api#52]
سلام 
برای گرفتن اطلاعات کندل های بازار تا جایی که متوجه شدم اطلاعات 501 کندل در هر تایم فریم برگردونده میشه راهی وجود داره که این محدودیت برداشته بشه یا پارامتری تغیر کنه؟

**Comment by mheidarian** [comment]
سلام و احترام
بله فعلا این محدودیت را بر روی این سرویس خواهیم داشت. شما می توانید با تغییر پارامترهای "از" و "تا" بازه‌های قدیمی‌تر رو هم دریافت کنید. ولی امکان تغییر این عدد به صورت پارامتریک موجود نیست.
