### ISSUE TITLE
نمایش پیام خطای Missing Captcha

### ISSUE THREAD

**Issue by nik1352** [nobitex/docs-api#53]
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
    CURLOPT_URL            => "https://api.nobitex.ir/auth/login/",
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING       => "",
    CURLOPT_MAXREDIRS      => 10,
    CURLOPT_TIMEOUT        => 0,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
    CURLOPT_CUSTOMREQUEST  => "POST",
    CURLOPT_POSTFIELDS     => array('username' => 'email@gmail.com', 'password' => '123456', 'remember' => 'yes'),
));

$response = curl_exec($curl);

curl_close($curl);
echo $response;

**Comment by mheidarian** [comment]
سلام 
پارامتر کپچا را نیز به همراه مابقی پارامترها به شکل زیر ارسال نمائید
captcha=api
