### ISSUE TITLE
تفاوت توکن ها

### ISSUE THREAD

**Issue by kasrakazemi** [nobitex/docs-api#54]
سلام 
چرا توکنی که با لاگین گرفته میشه با توکنی که داخل پروفایل هست متفاوته ؟و بقیه دستورات با توکن لاگین کار نمیکنن و فقط با توکن پروفایل عمل میکنن

**Comment by mheidarian** [comment]
سلام @kasrakazemi عزیز
توکن ها از نظر عملکرد هیچ تفاوتی با یکدیگر ندارند و شما میتوانید از هر کدام از این روش ها برای دریافت توکن عمل کرده و در سرویس هایی که نیاز به توکن دارند از آنها استفاده نمائید.

کد زیر نمونه فراخوانی سرویس دریافت لیست کیف پول های کاربر است که در هدر درخواست، توکن به شکل زیر قرار داده شده است
**Token b369eeb34414e67549b44a2bbea71760cd02bc1e**


```curl
curl --location --request POST 'https://api.nobitex.ir/v2/wallets' \
--header 'Authorization: Token b369eeb34414e67549b44a2bbea71760cd02bc1e' \
--header 'Content-Type: application/json' \
--header 'Cookie: __cfduid=d727d4fbddc828884f2a793143332d5aa1613231485; csrftoken=Xqjj8AyjhRuNG8oHMHw8tKYi9CXiyAK0OKXdbsgHw7ijbOfFvXhoL9cornqppJQi' \
--data-raw '{"currencies":"rls,btc"}'
```

**Comment by kasrakazemi** [comment]
مشکل اینجاست که فقط توکن پروفایل کار میکنه و توکنی که کد برمیگردونه اشتباهه

**Comment by mheidarian** [comment]
لطفا درخواست و پاسخی که با توکن دریافتی از سرویس لاگین گرفتید، اینجا بگذارید تا بررسی گردد.

**Comment by kasrakazemi** [comment]
url = "https://api.nobitex.ir/users/profile"



# payload = {

#   'AUTHORIZATION':'Token c4a13377a2dccc287201941abd9b000d9f96f7c9',

# }

#files=[]



headers = {

  'Authorization': 'Token 57cff605175cf8812fb5b31d37983cba6d67859c'

}



response = requests.request("GET", url, headers=headers)



print(response.json())

**Comment by Saeid-mp** [comment]
سلام
  کامنت شما پاک کردم. لطفا اطلاعات مثل توکن رو دردسترس کسی قرار ندهید و درصورت نیاز به تعامل با همکار ما به ایمیل شرکت ایمیل 
 ارسال کنید که در دسترس افراد دیگه قرار نگیره.
support@nobitex.ir
عنوان ایمیل api support
@kasrakazemi

**Comment by kasrakazemi** [comment]
اون توکن از عمد اشتباه بود ضمنا همکار شما نباید از این طریق درخواست توکن
میکرد
