### ISSUE TITLE
اطلاعات برای اعتبارسنجی ارسال نشده است

### ISSUE THREAD

**Issue by saman1996** [nobitex/docs-api#56]
سلام موقع دریافت موجودی و اردر گذاشتن این ارور رو میده درحالیکه من تایید دو مرحله ای غیر فعال کردم قبلا بازم تغییر نکرد اینم نمونه کد 
Headers ={"Authorization" : Token }
Data_Balance = {"currencies" : "rls" }
Data_Balance = json.dumps(Data_balance )
response=req.post(Balance_Url ,Headers  , Data_Balance)
response.json()

{'detail': 'اطلاعات برای اعتبارسنجی ارسال نشده است.'}

**Comment by mheidarian** [comment]
سلام . احتمالا مقدار توکن با فرمت درست ارسال نمیشه. 
مقدار توکن باید به این شکل باشه:
"Token d4568cffere126a7c56b7ee9a157e73903693757"
