### ISSUE TITLE
OHLC Problem

### ISSUE THREAD

**Issue by rezazohdi** [nobitex/docs-api#58]
OHLC آمار

در یک بازه تاریخ ، در تایم فریمهای  سه ساعته و شش ساعته و دوازده ساعته ، تعداد کندل مشابه یکساعته برمی گرداند
همچنین تایم فریم دو و سه روزه نیز تعداد کندل معادل یکروزه بر می گرداند.

**Comment by mheidarian** [comment]
سلام . مورد اعلام شده در حال بررسی است . به محض اصلاح و دریافت پاسخ اطلاع رسانی خواهد شد

**Comment by z-amini** [comment]
سلام.

مشکل اطلاع داده شده بررسی و تایید شد.
به علت تغییراتی که به زودی در نمودارهای نوبیتکس خواهیم داشت، رفع این مشکل در برنامه بهار ۱۴۰۱ قرار گرفته.
تغییرات صورت گرفته در نمودار OHLC در کنار انتشار درصفحه مستندات، ذیل همین مورد هم به شما اطلاع رسانی خواهد شد.

با تشکر از صبر و شکیبایی شما.

**Comment by z-amini** [comment]
سلام.
نسخه جدید نمودار OHCL نوبیتکس با پشتیبانی از کندل‌های دقیقه‌ای و رفع خطاهای گزارش شده مدتی‌ست که منتشر شده و در اختیار کاربران قرار گرفته.
می‌تونید رفع شدن موارد گزارش شده تون رو شخصا بررسی بفرمایید.

با تشکر

**Comment by Ashkian** [comment]
درود
close price USDT-IRT
را با استفاده از
API
در تایم فریم یک دقیقه
روی کندل
2023-10-22T21:00:00+03:30
درخواست دادم به صورت زیر
https://api.nobitex.ir/market/udf/history?symbol=USDTIRT&resolution=1&countback=1&to=1697988600
```
2023-10-22T21:00:00+03:30
=
2023-10-22T17:30:00+00:00
=
1697988600
```
### پاسخ درخواست :
```
array(7) {
  ["s"]=>
  string(2) "ok"
  ["t"]=>
  array(1) {
    [0]=>
    int(1697988600)
  }
  ["o"]=>
  array(1) {
    [0]=>
    float(50703)
  }
  ["h"]=>
  array(1) {
    [0]=>
    float(50710)
  }
  ["l"]=>
  array(1) {
    [0]=>
    float(50701)
  }
  ["c"]=>
  array(1) {
    [0]=>
    float(50710)
  }
  ["v"]=>
  array(1) {
    [0]=>
    float(801.4792337135)
  }
}
```
### مشکل : مغایرت قیمت بسته شدن در پاسخه با آنچه روی چارت هست:
https://nobitex.ir/panel/exchange/usdt-irr/
```
close price on chart:50699
close price on API response:50710
2023-10-22T21:00:00+03:30 on chart
=
2023-10-22T17:30:00+00:00 on API request = 1697988600
```
علت مغایرت؟
قبل طرح در اینجا، مشکل با پشتیبانی نوبیتکس مطرح شد، نتیجه طرح مشکل با پشتیبانی جهت رفع:
کیمیا:لینک اینجا را داد که اینجا طرح شود و سپس پاس داد به سامان برای رفع مشکل.
سامان: پس از چند دقیقه زمان که برای مطالعه گفتگوی انجام شده با کیمیا خواست، اسکرین شات تاریخچه معاملات را خواست! یعنی نه تنها مشکل حل نشد، فکر کنم حتی پرسش را هم نفهمید چه برسد به پاسخ دهی در جهت رفع مشکل
این بود که مشکل جهت رفع اینجا مطرح شد...

**Comment by z-amini** [comment]
سلام.
وقت شما بخیر.

نمودار Trading View یه کتابخونه خیلی رایج و پرامکاناته که نوبیتکس مثل خیلی صرافی های دیگه ازش استفاده می‌کنه.
این کتاب خونه این طور نوشته شده که هر ۱۰ ثانیه یکبار آخرین کندل‌ها رو به روز کنه.
شما با inspect کردن درخواست‌های صفحه مورد نظرتون می‌تونین اطمینان حاصل کنین که مرجع خوندن داده چارت همین API نوبیتکس هست که به طور عمومی در اختیار سایر کاربران قرار داده شده و شما دارید ازش استفاده می‌کنید. دلیل تفاوت مقدار فقط می‌تونه تفاوت زمان درخواست شما با سایت باشه.
احتمالا درخواست شما برای همون دقیقه آخر بوده، چون الان که کندل بسته شده، قیمت بسته شدن تتر روی لینک شما ۵۰۷۰۱ هست. که خب قیمت آخرین کندل توی نوبیتکس هم با فواصل ۱۰ ثانیه‌ای به روز میشه.

اگر مشکل شما درست دریافت نشده، توضیحات بیشتری برامون بفرستید.

**Comment by Ashkian** [comment]
مجدداً چک کردم
50701
در پاسخ شما مربوط به زمان
1697988540
هست نه
1697988600
الان با درخواست زیر
https://api.nobitex.ir/market/udf/history?symbol=USDTIRT&resolution=1&countback=1&to=1697988660
پاسخ مربوط به زمان
1697988600
را دریافت می کنید و می بینید عیناً همان پاسخ قبلی است و مغایرت زیر وجود دارد:
```
close price on chart:50699
close price on API response:50710
2023-10-22T21:00:00+03:30 on chart
=
2023-10-22T17:30:00+00:00 on API request = 1697988600
```
علت مغایرت؟

**Comment by Ashkian** [comment]
اگر
close price USDT-IRT
در تایم فریم یک دقیقه روی کندل
2023-10-22T21:00:00+03:30
را با استفاده از
API
بخوایم چه درخواستی باید داده شود تا پاسخ آن با قیمت بسته شده روی چارت در این زمان در فریم یک دقیقه یعنی
50699
مطابقت داشته باشد؟

**Comment by z-amini** [comment]
متوجه مسئله شما شدم. 
زمان
 2023-10-22T21:00:00+03:30 
 در یونیکس برابر با 1697995800 هست. فیلتر to به صورت exclusive عمل می‌کنه و زمان‌های قبل اون بازه رو مدنظر قرار می‌ده. اگر شما برای خود همین زمان رو می‌خواین، به این عدد حداقل ۱ ثانیه اضافه کنید و به شکل زیر درخواست بزنید:
https://api.nobitex.ir/market/udf/history?symbol=USDTIRT&resolution=1&countback=1&to=1697995801

زمان یونیکس 1697988600 برابر با
2023-10-22T19:00:00+03:30
هست که طبق نمودار هم درست هست مقادیر.
برای تبدیل زمان‌ها می‌تونید از این سایت برخط کمک بگیرید: https://www.timestamp-converter.com/
همه زبان‌های برنامه‌نویسی هم کتابخونه‌هایی دارن که تبدیل یونیکس رو پشتیبانی می‌کنن.

**Comment by Ashkian** [comment]
تبدیل زمان :
<?php
strtotime('2023-10-22 17:30:00')//output:1697988600
date("Y-m-d\TH:i:s",1697988600)//output:2023-10-22T17:30:00

**Comment by z-amini** [comment]
با توجه به سایت تبدیلی که ارسال کردم، مشکل توی بخش تبدیل شماست که ممکنه به دلایل متفاوتی باشه.
مثلا ساعت سیستم شما عقب باشه یا timezone درستی براش ست نشده باشه یا ...
من توی [سایت‌های اجرای برخط](https://www.w3schools.com/php/phptryit.asp?filename=tryphp_func_strtotime) هم که کد شما رو اجرا می‌کنم، مقدار 1697995800 رو خروجی می‌گیرم.
```php
<?php
echo(strtotime("2023-10-22 17:30:00") . "<br>"); // outputs: 1697995800
echo(strtotime("2023-10-22T21:00:00+03:30"));    // outputs: 1697995800
?>
```

**Comment by Ashkian** [comment]
با سپاس از پاسخ گویی خانم زینب امینی
### علت مغایرت
timestamp
خروجی تابع
strtotime
بود که در محاسبه چون منطقه زمانی در ورودی تعیین نشده بود از منطقه زمانی پیش فرض که در محیط اجرایی سرور برلین تعیین شده بود استفاده کرده بود.


### یک راه حل ساده رفع مغایرت ، تعیین منطقه زمانی در ورودی تابع است یعنی به جای
```
<?php
$time=strtotime('2023-10-22 17:30:00')//default time zone is Europe/Berlin => time:1697988600

```
نوشته شود
```
<?php
$time=strtotime('2023-10-22 21:00:00+03:30')//time:1697995800

```
با توجه به توضیح خانم امینی که

> فیلتر to به صورت exclusive عمل می‌کنه...

پس مقدار to را یک کندل بعد از کندل موردنظر تعیین می کنیم یعنی
`https://api.nobitex.ir/market/udf/history?symbol=USDTIRT&resolution=1&countback=1&to='.$time+60`

### API response:
```
array(7) {
  ["s"]=>
  string(2) "ok"
  ["t"]=>
  array(1) {
    [0]=>
    int(1697995800)
  }
  ["o"]=>
  array(1) {
    [0]=>
    float(50672)
  }
  ["h"]=>
  array(1) {
    [0]=>
    float(50699)
  }
  ["l"]=>
  array(1) {
    [0]=>
    float(50650)
  }
  ["c"]=>
  array(1) {
    [0]=>
    float(50699)
  }
  ["v"]=>
  array(1) {
    [0]=>
    float(3400.78738)
  }
}
```
حالا داریم
```
close price on chart=50699=close price on API response
2023-10-22T21:00:00+03:30 on chart
=
1697995800 on API response
```
