### ISSUE TITLE
Question: Is Nobitex a standalone exchange or it is using the API from Binance or other exchanges?

### ISSUE THREAD

**Issue by sa8ab** [nobitex/docs-api#61]

**Comment by mheidarian** [comment]
Hello. No it isn't. Nobitex is a completely independent marketplace and does not use any other exchange.

**Comment by sa8ab** [comment]
@mheidarian So you mean it is running the nodes of different blockchains it needs? (BTC, ETH, XRP, DOGE, ...)

**Comment by mheidarian** [comment]
Yes, exactly!
