### ISSUE TITLE
How can I have a long-term or permanent token?

### ISSUE THREAD

**Issue by agn-7** [nobitex/docs-api#62]
I want to have a long-term or permanent token, but when I get my token from my settings section, it's changed after a while and will no longer be valid.
Also, I saw this API `POST /auth/login/` in your API docs with the `remember=yes` parameter to get a long-term (30 days) token. However, the problem is I don't have a username and password to fill in other parameters for using that API. Actually, I'm using google auth for authentication.

Thanks in advance for your response.

**Comment by mheidarian** [comment]
Hello, you're right, but you can use 'forget password' option to get your password with your email that you have signed up at Nobitex.

**Comment by agn-7** [comment]
Hello, thanks for your response.

So you mean is I have to use Nobitex user pass instead of google authentication?

**Comment by mheidarian** [comment]
It's nothing! Glad to help.
Just for calling api, Yes. but at Nobitex website you still can login with google authentication.

**Comment by agn-7** [comment]
Actually, I didn't want to send any passwords to Nobitex servers.

**Comment by mheidarian** [comment]
You can't do it without sending password right now!

**Comment by agn-7** [comment]
It would be great if you could develop it as soon as possible.
