### ISSUE TITLE
راهنمائی

### ISSUE THREAD

**Issue by jarehan1** [nobitex/docs-api#65]
من کد زیر را در سی شارپ برای آزمایش وارد کردم ولی سب شارپ به این مطالب خطا می گیره و اون ها رو نمی شناسه. ممنون میشم راهنمائی کنید
![1111](https://user-images.githubusercontent.com/84096233/118021187-34e40580-b370-11eb-8a9d-c7437fdaf033.PNG)

**Comment by jarehan1** [comment]
البته اون مشکل بالا رو حل کردم. اگر ممکن هست یهک برنامه خیلی کوچک اتصال به حساب کاربری با سی شارپ را برای بنده داشته باشید. با احترام

**Comment by mheidarian** [comment]
سلام و احترام. 
مبنای ارتباطی ما با توسعه دهنده های گرامی جهت رفع خطاهای پیش آمده در وب سرویس های موجود، به منظور داشتن یک استاندارد مشخص، یا زبان ارتباطی مشترک، سینتکس مورد استفاده در postman و یا curl است.

لذا از بررسی خطا یا ایرادات موجود بر روی زبان های برنامه نویسی مختلف یا تهیه نمونه کد معذوریم. 

به این منظور می توانید از [این آدرس](https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest) به مجموعه از پیش آماده شده، برای تمام سرویس های موجود دسترسی پیدا کنید
