### ISSUE TITLE
راهنمایی

### ISSUE THREAD

**Issue by aminnazem2020** [nobitex/docs-api#69]
با سلام
می خواستم از api 
استفاده کنم لطف می کنید یک راهنمایی بفرمایید یا یک فیلم آموزشی برایم ارسال کنید

**Comment by sadrabayay** [comment]
سلام میشه یک راهنمایی ویدیویی قرار بدین

**Comment by mheidarian** [comment]
سلام و احترام
برای استفاده از سرویس ها می توانید به آدرس زیر مراجعه نمائید.
https://apidocs.nobitex.ir/
راهنمایی ها و توضیحات مربوط به هر کدام از سرویس ها در این آدرس موجود است.
همچنین بسته از پیش آماده کلیه سرویس ها برای استفاده در نرم افزار 
postman
نیز موجود است :‌
https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest
