### ISSUE TITLE
محدودیت فراخوانی

### ISSUE THREAD

**Issue by milad86** [nobitex/docs-api#71]
با سلام.
به علت ماهیت کاری، سرور من ممکن است گاها بیشتر از حد مجاز درخواست ارسال نماید. در حال حاضر آی پی سرور من بلاک شده است.

1) چطور نسبت به افزایش حد مجاز فراخوانی اقدام کنم ؟
2) چطور آی پی را را از بلاک بودن خارج کنیم ؟

**Comment by amofogh** [comment]
اگر دوتا اک مختلف همزمان استفاده بشن محدودیت اندازه
 ip حساب میشه یا api ?

**Comment by mheidarian** [comment]
@milad86 
باسلام و احترام
با هماهنگی پشتیبانی موارد برطرف گردید.

**Comment by mheidarian** [comment]
@amofogh  عزیز
اگر کاربر لاگین باشه که اکثر «ای پی آی»های نوبیتکس همینطور هستند، محدودیت روی کاربر حساب میشه و نه آی پی 
ولی در صورتی که کاربر احراز نشده باشه و از «ای پی آی»های عمومی استفاده کنه روی آی پی حساب میشه.
