### ISSUE TITLE
مشکل لاگین با استفاده از گوگل

### ISSUE THREAD

**Issue by mrk24251** [nobitex/docs-api#72]
حساب کاربری که در نوبیتکس ورود کرده ام با استفاده از ورود گوگل می باشد.
حال برای گرفتن توکن با استفاده از ای پی آی لاگین بعد از ورود یوزر و پسورد حساب گوگل ارور نامعتبر بودن یوزر و پسورد به من می دهد.
برای گرفتن توکن حساب های ورودی توسط لاگین گوگل چه کار باید انجام داد؟

**Comment by mheidarian** [comment]
سلام . برای اینکار کافیست با همان ایمیلی که ثبت نام کرده اید از فراموشی رمز عبور استفاده کنید تا در نوبیتکس برای شما رمز عبور اختصاص یابد. 
رمز عبور ایمیل شما صرفا مربوط به حساب گوگل شماست و نه سامانه های دیگر
