### ISSUE TITLE
مشکل MissingCaptcha

### ISSUE THREAD

**Issue by skasiri** [nobitex/docs-api#73]
هنگام احراز هویت خطای MissingCaptcha برگردانده میشود
لطفا راهنمایی بفرمایید

**Comment by skasiri** [comment]
خطای بازگشتی:

{
    "non_field_errors": [
        "Missing Captcha"
    ],
    "code": "MissingCaptcha"
}

**Comment by SSEsmaeeli** [comment]
این پارامتر با مقدارش رو همراه با نام کاربری و رمز عبور ارسال کنید 

'captcha' => 'api'

**Comment by Javadprogrammer10** [comment]
ببخشید
مقدار کپچا چی بایید باشه هیچ کجا توضیح ندادید
من کپچا رو پیاده سازی کردم و رسپانس توکن دریافتی از کپچا رو ست کردم ولی بازم خظا داد!

**Comment by SSEsmaeeli** [comment]
شما برای دریافت توکن یه سری پارامتر میفرستید، که همراه اونا باید یه پارامتر به نام 
captcha
با مقدار
api
ارسال کنید.

captch=api
