### ISSUE TITLE
مدت اعتبار توکن دریافتی از پنل وبسایت

### ISSUE THREAD

**Issue by Javadprogrammer10** [nobitex/docs-api#74]
با سلام
ببخشید مدت اعتبار توکنی که از تنظیمات پروفایل در پنل دریافت میکنیم چقدره؟

**Comment by mheidarian** [comment]
سلام. اعتبار توکن مدنظر ۴ ساعت است.
اگر توکن با مدت زمان بیشتری لازم دارید و از 
api 
استفاده میکنید میتوانید از این [لینک](https://apidocs.nobitex.ir/#34fc385948) توکن با مدت ۳۰ روز دریافت کنید.
