### ISSUE TITLE
مشکل متد پست در ایجکس

### ISSUE THREAD

**Issue by farhad5048** [nobitex/docs-api#76]
باسلام
من با ایجکس کد نوشتم
در متد get هیچ ایرادی نیست 
ولی وقتی از متد پست میخام استفاده کنم استاتوس رو برام صفر برمیگردونه و از طرف سرور هیچ پاسخی دریافت نمیکنم
لطف میکنید راهنماییم کنید
این هم کدی هست که نوشتم

var data1={"username":"farhad5048@gmail.com", "password":"....", "captcha":"api"};
var jdata1=JSON.stringify(data1);

let button = document.getElementById('button');
let pre = document.getElementById('dataa');
button.addEventListener('click' , function(){
	let xhr = new XMLHttpRequest();
	xhr.withCredentials = true; 
	xhr.open('POST', 'https://api.nobitex.ir/auth/login/');	xhr.addEventListener('readystatechange',function(){if(xhr.readyState == 4){if((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304){pre.innerHTML = xhr.responseText;}else{alert(xhr.readyState);
		pre.innerHTML = 'An error occurred';			
			}		
		}		
}); 
xhr.setRequestHeader('Content-Type' , 'application/json');
alert(xhr.readyState);
xhr.send(jdata1);
 });

این کد با متد گت به درستی کار میکنه، ولی با متد پست کار نمیکنه!
باتشکر

**Comment by mheidarian** [comment]
سلام و احترام
با توجه به اینکه این مشکل مربوط به
Access-Control-Allow-Origin
می باشد لذا ضروری است شما 
APIها
را در سمت بک اند سایت خود پیاده سازی و از آنجا فراخوانی سمت نوبیتکس را انجام دهید.

**Comment by farhad5048** [comment]
خیلی لطف میکنید اگه بیشتر راهنمایی کنید
یعنی با php باید ارسال کنم؟

**Comment by mheidarian** [comment]
بله همینطوره. شما باید در سمت بک اند سایت خود که گویا با پی اچ پی می باشد، سرویس های مورد نظر خود را پیاده سازی کنید و در این سرویس ها
apiهای
نوبیتکس را صدا بزنید. 
در نهایت شما می توانید سرویس های پیاده سازی شده خود را با ایجکس بدون هیچگونه مشکلی فراخوانی کنید.

**Comment by farhad5048** [comment]
لطف میکنید اگه امکانش براتون هست یک نمونه کد 
PHP
برام بفرستید

**Comment by mheidarian** [comment]
نمونه کد اکثر زبان های برنامه نویسی در قسمت پکیج آماده «پست من» موجود می باشد. از این آدرس می توانید به آنها دسترسی داشته باشید:‌
https://documenter.getpostman.com/view/5722122/Szmcayjw?version=latest
