### ISSUE TITLE
قیمت تومان

### ISSUE THREAD

**Issue by shahrokhvahabi** [nobitex/docs-api#77]
با درود و خسته نباشید. من راهنمایی شما رو مطالعه کردم اما در استفاده، قیمت تومان رو مشاهده نمی کنم. ممنون میشم راهنمایی بفرمایید

**Comment by mheidarian** [comment]
سلام و درود
منظور از قیمت تومان چیست؟لطفا کمی با جزئیات مشکل خودتون رو بیان کنید. و در حال استفاده از کدام سرویس هستید؟
ممنون

**Comment by shahrokhvahabi** [comment]
با سلام. من مي خوام توي برنامم قيمت ارزها رو چك كنم مثلا تتر چند تومان هستش.

**Comment by mheidarian** [comment]
میتوانید از سرویس «آمار وضعیت بازار نوبیتکس» استفاده کنید
مستندات این سرویس :‌https://apidocs.nobitex.ir/#6ae2dae4a2
آدرس این سرویس :‌ https://api.nobitex.ir/market/stats
