### ISSUE TITLE
کسی اینجا پاسخگو هست؟

### ISSUE THREAD

**Issue by farhad5048** [nobitex/docs-api#80]

**Comment by mheidarian** [comment]
سلام و احترام
با عرض پوزش از تاخیر پیش آمده. سوال شما مشاهده شد. در حال بررسی هستیم و به زودی پاسخ خواهیم داد.

**Comment by farhad5048** [comment]
باتشکر
منتظرهستم
ممنون اگر زودتر جواب دهید
