### ISSUE TITLE
نمایش جمع کل دارایی ها به تومان یا تتر

### ISSUE THREAD

**Issue by sirousjj** [nobitex/docs-api#81]
سلام.
من نیاز دارم که جمع کل دارایی هایی کاربر رو به تومان یا تتر داشته باشم.
به عبارتی اگه مثلا یک کاربر 2 اتریوم و 100تتر و 0.1بیت کوین داخل کیف پول خودش داره،
این مقادیر رو در قیمت لحظه ای آخرین معامله ی خرید یا فروش  اون ارز ضرب کنه و همه رو با هم جمع کنه 
و یه جمع کل از دارایی کاربر نمایش بده.
این کار با کد نویسی برای من امکان پذیر هست.

ولی سوالم اینه که آیا شما میتونید داخل مستنداتتون یه آیتم با عنوان
 TOTAL_BALANCE
قرار بدین که فقط توکن کاربر رو بگیره و یه عدد به عنوان جمع کل دارایی ها رو نمایش بده؟

**Comment by mheidarian** [comment]
سلام و احترام
ای پی آی به صورت مستقل برای رفع نیاز شما موجود نیست ولی شما میتوانید با استفاده از دو ای پی آی «موجودی» و «وضعیت بازار» این عدد را بدست بیاورید. 

Balance API:
https://apidocs.nobitex.ir/#55645b2c6d

Stats API:
https://apidocs.nobitex.ir/#6ae2dae4a2


اگر سوالی در این رابطه داشتید مجددا «موضوع» را باز کنید

**Comment by sirousjj** [comment]
باتوجه به اینکه زمان زیادی از پاسخگویی شما میگذره،
مشکل ام رو حل کردم و نیازم برطرف شما.
بنده حاضرم برای توسعه ای پی آی شما این مورد رو براتون آماده کنم و به عنوان آپدیت برای ای پی آی خودتون دراختیارتون بزارم.
اگه مایل به همکاری بودین از طریق ایمیل بهم اطلاع بدین، تا بررسی کنم
as.moini@gmail.com

**Comment by mheidarian** [comment]
بابت تاخیر پیش آمده عذرخواهی میکنیم و در رابطه با پیشنهاد سخاوتمندانه شما بسیار سپاسگذاریم. 
موضوع مورد نظر مورد بررسی قرار گرفت و در آینده پیاده سازی خواهد گردید.
پیروز باشید
