### ISSUE TITLE
stats method 

### ISSUE THREAD

**Issue by amofogh** [nobitex/docs-api#82]
سلام در stats method 
وقتی btc و rls 
رو فراخوانی میکنی به جای اون دوتا قیمت همرو به دلار میده 
`    def stats(self):

        # '''python stats method
        url = "https://api.nobitex.ir/market/stats"

        payload='srcCurrency=usdt&dstCurrency=rls'

        response = requests.request("POST", url, data=payload) 
        with open('data.json' , 'w') as j :
            json.dump(response.json(),j , indent=4)`
فایل دیتای گرفته شده
[data.zip](https://github.com/nobitex/docs-api/files/7002977/data.zip)

**Comment by mheidarian** [comment]
سلام واحترام
کد درست است و نتیجه هم صرفا نقص دارد.
اطلاعاتی که در 
global
لیست میشوند به طور کلی باید به دلار باشند و این درست است. 
ولی اطلاعات ریالی که شما درخواست داده اید می بایست در 
stats 
لیست شوند. 
به این شکل : 
"stats": {
        "usdt-rls": {
            "isClosed": false,
            "bestSell": "272000",
            "bestBuy": "271980",
            "volumeSrc": "1313140.79413288812",
            "volumeDst": "358021197596.39787435218",
            "latest": "271980.0000000000",
            "dayLow": "270130.0000000000",
            "dayHigh": "274350.0000000000",
            "dayOpen": "273030.0000000000",
            "dayClose": "271980.0000000000",
            "dayChange": "-0.38"
        }
    },

لطفا مجددا درخواست خود را تکرار کنید و در صورت عدم دریافت پاسخ صحیح مجددا همینجا عنوان کنید تا پیگیری گردد.

**Comment by mheidarian** [comment]
اگر سوال یا مشکلی داشتید مجددا «موضوع» را باز کنید
