### ISSUE TITLE
عدم انتقال و یا دریافت کوین از صرافی دیگر توسط api

### ISSUE THREAD

**Issue by aminalizade74** [nobitex/docs-api#83]
سلام
من مستندات 
api
را مطالعه کردم منتهی بخشی که در ان باهاش بشه یک کوین را به صرافی دیگری انتقال داد پیدا نکردم
امکانش هست راهنمایی بفرمایین

**Comment by mheidarian** [comment]
سلام و احترام
با توجه به مسائل امنیتی و الزام به تایید در سایت فعلا امکان پذیر نمی باشد
این موضوع در حال بررسی بوده و در آینده پیاده سازی خواهد گردید.
