### ISSUE TITLE
تغییر در خروجی OHLC

### ISSUE THREAD

**Issue by sahraee** [nobitex/docs-api#84]
با سلام
آیا امکان دارد در پارامتر ارسالی برای دریافت اطلاعات کندلهای متد آمار OHLC بازار نوبیتکس، تایم فریم 30 دقیقه یا کمتر هم اضافه گردد؟
با تشکر

**Comment by mheidarian** [comment]
سلام و احترام
با تشکر از ارائه پیشنهاد
این موضوع در دست بررسی بوده و امید است در آینده محقق گردد. در صورت پیاده سازی به صورت عمومی اطلاع رسانی خواهد گردید.
