### ISSUE TITLE
درخواست افزونه برای edd

### ISSUE THREAD

**Issue by sepidvisa** [nobitex/docs-api#85]
سلام، من میخوام افزونه وردپرسی درگاه پرداخت نوبیتکس رو برای ایزی دیجیتال دانلود هم داشته باشم
برای  ووکامرس بود ولی برای ایزی دیجیتال دانلود نیست. ممنون میشم ایجادش کنید

**Comment by mheidarian** [comment]
سلام و احترام
امکان «درگاه پرداخت نوبیتکس»  غیرفعال شده است و این خدمت در نوبیتکس ارائه نمی شود.
