### ISSUE TITLE
مشکل در خروجی وب سرویس

### ISSUE THREAD

**Issue by mehriabbasi71** [nobitex/docs-api#90]
با سلام
 
هنگام فراخوانی وب سرویس /market/stats خروجی زیر دریافت می شود.
 مشکل داردlatest که بعضی فیلدها مانند 

`[2021-10-21 02:30:17] production.DEBUG: Nobitex Response: {"status":"ok","stats":{"usdt-rls":{"isClosed":false,"bestSell":"271500","bestBuy":"270770","volumeSrc":"1926053.39087248712","volumeDst":"523669722187.85817034714","latest":"0E-10","dayLow":"269500.0000000000","dayHigh":"274900.0000000000","dayOpen":"274450.0000000000","dayClose":"0E-10","dayChange":"-100.00"}},"global":{"binance":{"btc":64686.0,"eth":4185.15,"bch":643.5,"xrp":1.1395,"eos":4.822,"ltc":206.54,"trx":0.1024,"etc":55.844,"link":27.395,"xlm":0.38991,"ada":2.2188,"xmr":261.7,"dash":201.51,"zec":149.42,"xtz":6.963,"bnb":497.17,"atom":35.616,"ont":0.9731,"iota":1.2851,"bat":0.7132,"vet":0.12375,"neo":45.073,"qtum":13.41,"iost":0.05151,"usdt":1,"theta":6.177,"algo":1.7784,"zil":0.0965,"knc":1.672,"zrx":1.0057,"comp":324.97,"omg":15.0793,"doge":0.25173,"sxp":2.3763,"lend":0.51431,"kava":5.6964,"band":8.721,"rlc":4.421,"waves":29.231,"mkr":2610.1,"snx":9.925,"dot":44.077,"defi":2616.4,"yfi":35854.0,"bal":23.225,"crv":2.96,"trb":57.86,"yfii":4082.8,"sushi":11.508,"rune":8.022,"srm":7.625,"bzrx":0.328,"egld":240.76,"sol":184.28,"icx":2.0923,"storj":1.2792,"blz":0.26051,"uni":27.043,"avax":61.313,"ftm":2.36389,"hnt":22.516,"enj":1.8227,"flm":0.5197,"tomo":2.5009,"ren":1.09332,"ksm":378.16,"near":8.7149,"fil":66.431,"aave":319.24,"rsr":0.0355,"lrc":0.43655,"matic":1.5425,"ocean":0.87242,"cvc":0.47893,"bel":2.3437,"ctk":2.021,"axs":126.93,"alpha":1.0618,"zen":85.297,"bcc":448.7,"gas":1.48685,"hsr":7.69017,"mco":2.744,"wtc":0.8357,"yoyo":0.00873,"strat":0.4904,"sngls":0.00613,"bqx":0.14972,"fun":0.01812,"snm":0.01003,"xvg":0.01936,"salt":0.78945,"mda":0.49912,"mtl":3.2452,"sub":0.08489,"snt":0.04012,"mth":0.00762,"eng":1.15167,"dnt":0.1435,"bnt":3.403,"ast":0.08359,"oax":0.06631,"icn":1.06659,"btg":50.6,"evx":0.26544,"req":0.1795,"vib":0.01542,"powr":0.09585,"ark":0.38674,"mod":0.79502,"ven":0.0001,"kmd":0.8814,"rcn":0.03975,"nuls":0.4284,"rdn":0.17554,"dlt":0.03102,"amb":0.01356,"bcpt":0.0195,"arn":0.14136,"gvt":1.26126,"cdt":0.00632,"gxs":0.5141,"poe":0.00093,"qsp":0.02786,"bts":0.05125,"xzc":4.446,"lsk":2.745,"tnt":0.04848,"fuel":0.00483,"mana":0.811,"bcd":0.52772,"dgd":73.01943,"adx":0.27566,"ppt":0.27008,"cmt":0.00836,"cnd":0.00873,"wabi":0.08006,"tnb":0.00223,"gto":0.03361,"ost":0.01059,"elf":0.5833,"aion":0.1418,"nebl":0.39751,"brd":0.06724,"edo":1.04189,"wings":0.2216,"nav":0.10941,"lun":1.58076,"trig":0.36779,"appc":0.03102,"vibe":0.01635,"ins":0.1148,"pivx":0.37373,"chat":0.03622,"steem":0.17015,"nano":4.386,"via":0.20897,"ae":0.1252,"rpx":0.04161,"ncash":0.00093,"poa":0.01969,"storm":0.0034,"xem":0.1759,"wan":0.7413,"wpr":0.00892,"qlc":0.0169,"sys":0.289,"grs":0.20154,"cloak":2.88846,"gnt":0.11257,"loom":0.02526,"bcn":0.00409,"rep":18.93,"tusd":0.9999,"sky":0.52011,"iotx":0.06972,"qkc":0.0052,"agi":0.05145,"nxs":0.19448,"data":0.11659,"sc":0.01898,"npxs":0.00703,"key":0.00742,"nas":0.29906,"mft":0.00922,"dent":0.00608,"ardr":0.2573,"hot":0.00964,"dock":0.08268,"poly":0.5305,"phx":0.03344,"hc":0.8423,"go":0.00724,"pax":0.9996,"rvn":0.11175,"dcr":99.5,"mith":0.0406,"bchabc":220.08,"bchsv":58.9,"usdc":0.9999,"btt":0.00375,"usds":0.9968,"ong":1.0392,"fet":0.7198,"celr":0.1386,"phb":0.00297,"tfuel":0.2601,"one":0.24875,"btcb":18575.28,"usdsb":0.9997,"erd":0.01971,"dusk":0.1355,"ankr":0.09646,"win":0.0004,"cos":0.01698,"cocos":0.5422,"perl":0.07913,"chz":0.32704,"busd":0.9999,"beam":0.5302,"hbar":0.39404,"nkn":0.46558,"stx":1.168,"arpa":0.16268,"ctxc":0.1873,"troy":0.01309,"vite":0.07667,"ftt":50.89,"eur":1.162,"ogn":0.8644,"drep":0.5312,"bull":1370.28,"bear":11.16,"ethbull":79.18,"ethbear":12.2,"tct":0.02491,"wrx":1.028,"lto":0.251,"eosbull":3.85,"eosbear":30.21,"xrpbull":8.74,"xrpbear":548.55,"mbl":0.00706,"coti":0.50363,"bnbbull":57.21,"bnbbear":58.61,"stpt":0.04642,"ctsi":0.5708,"hive":0.5212,"chr":0.3585,"btcup":61.865,"btcdown":0.02442,"mdt":0.03555,"stmx":0.03172,"pnt":0.8969,"dgb":0.05025,"bkrw":0.00085,"ethup":49.719,"ethdown":1.915,"adaup":120.798,"adadown":0.00349,"linkup":1.2431,"linkdown":0.03781,"vtho":0.00827,"gbp":1.332,"iris":0.1087,"dai":1.0004,"fio":0.1609,"bnbup":227.5,"bnbdown":0.5101,"xtzup":0.0625,"xtzdown":4.71,"ava":2.744,"aud":0.7245,"jst":0.06054,"ant":4.291,"sand":0.7663,"nmr":41.31,"luna":42.275,"idex":0.33289,"paxg":1748.0,"wnxm":54.15,"wbtc":18540.91573,"dia":1.492,"uma":8.9,"eosup":0.4855,"eosdown":0.00065,"trxup":0.2563,"trxdown":15.45,"xrpup":3.7683,"xrpdown":0.00234,"dotup":5.786,"dotdown":0.00045,"wing":15.35,"ltcup":2.374,"ltcdown":3.947,"nbs":0.0118,"oxt":0.2988,"sun":0.02514,"scrt":0.36983,"uniup":3.614,"unidown":2.846,"orn":7.762,"utk":0.3464,"xvs":21.35,"vidt":0.7738,"sxpup":0.20714,"sxpdown":0.2145,"filup":0.9306,"fildown":0.001,"yfiup":0.1725,"yfidown":1.2413,"inj":9.758,"aergo":0.04087,"audio":2.0305,"bchup":0.2125,"bchdown":0.4271,"bot":454.5371,"akro":0.03297,"hard":0.8845,"renbtc":18572.30796,"strax":1.708,"for":0.07576,"unfi":11.384,"rose":0.1546,"aaveup":0.6288,"aavedown":0.01079,"skl":0.35024,"susd":1.004,"sushiup":0.04741,"sushidown":47.626,"xlmup":0.05217,"xlmdown":12.283,"glm":0.13234,"grt":0.85059,"juv":12.26,"psg":25.34,"1inch":4.493,"doteco":2267.3,"lit":4.501,"dodo":1.53,"reef":0.03128,"sfp":1.8538,"btcst":14.61,"alice":12.201,"lina":0.05686,"1000shib":0.02841,"icp":46.91,"bake":2.1062,"og":7.52,"atm":13.88,"asr":7.313,"celo":6.515,"rif":0.203,"tru":0.4226,"ckb":0.0118,"twt":0.97,"firo":5.209,"fxs":2.50045,"front":1.33263,"easy":10.30114,"cake":18.74,"acm":9.131,"auction":28.79037,"pha":0.6308,"tvk":0.1734,"badger":15.78,"fis":1.4354,"om":0.2159,"pond":0.08092,"dego":6.97,"perp":16.61,"ramp":0.2707,"super":0.5873,"cfx":0.3278,"eps":0.4821,"auto":853.9,"tko":1.665,"pundix":1.171,"tlm":0.1961,"1inchup":0.03031,"1inchdown":0.05765,"mir":2.811,"bar":16.48,"forth":12.91,"ez":5.17698,"burger":3.234,"slp":0.0662,"shib":1.0e-5,"ar":57.432,"pols":1.486,"mdx":1.126,"mask":10.2144,"lpt":16.79,"agix":0.27076,"nu":0.2739,"ata":1.1586,"gtc":10.613,"torn":59.16,"keep":0.7717,"ern":9.396,"klay":1.6472,"bond":26.61,"mln":137.7,"quick":348.4,"dexe":12.02,"c98":3.7371,"clv":1.031,"qnt":293.6,"flow":15.45,"mina":4.19,"ray":10.733,"farm":162.9,"alpaca":0.8933,"mbox":4.298,"vgx":5.40055,"ghst":1.586,"waxp":0.1997,"tribe":0.5919,"gno":239.3,"prom":32.24054,"xec":0.00027,"dydx":20.154,"usdp":0.9998,"gala":0.08691,"ilv":477.5,"ygg":5.923,"df":0.2139,"1000xec":0.1958,"btcdom":1182.8}}} `

**Comment by z-amini** [comment]
با سلام و عرض ادب.

مشکلی که گزارش نموده‌اید، به زودی در سرورهای اصلی رفع خواهد شد.
به خاطر تاخیر در پیگیری از شما پوزش می‌طلبیم و بابت گزارش این مورد از شما تشکر می‌کنیم.

از همراهی شما ممنونیم.

**Comment by z-amini** [comment]
با سلام و عرض ادب.

مورد گزارش شده بر طرف شده است.
در صورت مشاهده مجدد به ما اطلاع دهید.

با تشکر.
