### ISSUE TITLE
مشکل در فراخوانی RealTime

### ISSUE THREAD

**Issue by mrk24251** [nobitex/docs-api#91]
سلام
آیا نوبیتکس قصدی برای اضافه کردن وب سوکت، جهت گرفتن قیمت ها را دارد؟

**Comment by z-amini** [comment]
سلام و وقت بخیر.

افزودن وب سوکت برای دریافت مقادیر realtime در برنامه فعلی نوبیتکس نیست.
اما ممکن است در آینده بسته به نیازها و تقاضاها، تصمیمی برای آن اتخاذ شود.

با احترام

**Comment by Mostafa-Abbasinejad** [comment]
با سلام؛
 یکی از فاکتورهایی که بازارسازان و معامله گران فرکانس بالا بهش نیاز دارند، موضوع دسترسی به اوردربوک آپدیت و به روز پلتفرم هست. که عملاً علاوه بر کاهش حجم دریافتی اطلاعات از سرور (حذف هدرها در هر ریکوئست در REST API)، سرعت آپدیت شدن اوردربوک برای برنامه رو هم افزایش میده و معاملات صحیح تر و سریع تری انجام میشه.
اکثر صرافی های مطرح دنیا امکان دریافت اوردربوک از طریق وب سوکت رو فراهم کردند و بعضی امکان دریافت تغییرات روی اردر ها یا تغییرات بالانس حساب رو هم فراهم کردند. 
متأسفانه صرافی نوبیتکس به عنوان برترین و مطرح ترین صرافی ایران هنوز همچین امکانی رو نداره و به عنوان یک معامله گر HFT، تنها دلیل حضور نداشتنم در نوبیتکس، عدم وجود زیرساخت لازم برای حضور معامله گران فرکانس بالا در صرافی هست. انتظار میره به زودی حداقل امکان اتصال به اوردربوک با استفاده از وب سوکت رو فراهم بفرمائید.
تشکر
