### ISSUE TITLE
12dRugNcdxK39288NjcDv4GX7rMSKCGn6B

### ISSUE THREAD

**Issue by fatemehramezanli** [nobitex/docs-api#93]
سلام من ازچطور باید از سپرده بیت کوین تایید شده در f2poolبرداشت کنم وبه کیف پول دیگر انتقال بدهم.

**Comment by z-amini** [comment]
با سلام و عرض ادب.

ما در این قسمت به سوال‌های توسعه دهندگان درباره API عمومی نوبیتکس پاسخ می‌دهیم.
در صورتی که سوال شما در همین حوزه هست، لطفا ضمیمه بفرمایید چه endpoint ای مد نظر شما هست و چه مشکلی در استفاده اش پیدا کردید.
