### ISSUE TITLE
The api request limitiation is anoying!

### ISSUE THREAD

**Issue by moradi2021** [nobitex/docs-api#94]
Hello,
Please at least triple the capacity of API requests for useful trading functions like /market/orders/add , /market/orders/status , /market/orders/update-status . 
With the current limitations, the chance of getting blocked and facing with huge amount of loss in trades is high. I think the current limitations are too strict and pessimistic. Please prioritize resolving this issue. 
Thank you in advance

**Comment by mnwato** [comment]
Hi.

This is also my problem .
The other import thing is data update interval. I mean even if ask for data less than the limit, received data will not be updated for about 7 seconds. This is more of an annoying rate limitation.
This would be helpful to increase liqudity and trading volume if you recheck and set new version of limitation which is more flexible or this will be wonderful if you release a websocket api.

Thanks in advaned

**Comment by mheidarian** [comment]
> Hello, Please at least triple the capacity of API requests for useful trading functions like /market/orders/add , /market/orders/status , /market/orders/update-status . With the current limitations, the chance of getting blocked and facing with huge amount of loss in trades is high. I think the current limitations are too strict and pessimistic. Please prioritize resolving this issue. Thank you in advance

سلام 
پیرو مساله ای که بیان کردید، آپدیت هایی از قبیل :
/market/orders/add:
افزایش از ۱۰۰ درخواست به ۲۰۰ درخواست در دقیقه
/market/orders/update-status:
افزایش از ۴۰ درخواست به ۶۰ درخواست در دقیقه

بر روی سرویس های مورد نظر انجام شد. 



نسبت به میزان تغییرات اعمال شده هم باید عرض کنم که به خاطر پاره ای از مسائل امنیتی در حال حاضر، کاهش این محدودیت ها بیش از این امکان پذیر نیست. با این حال در صورت اعمال تغییرات بیشتر اطلاع رسانی خواهد شد.
موفق باشید

**Comment by mohammadnazarirad** [comment]
سلام
تو لیست api ها api مربوط به سود و زیان روزانه در بازه 30 روزه موجود نیست
از توی سایت میشه برای 7 روز رو دراورد ولی داخل موبایل از 30 روزش استفاده شده

**Comment by mheidarian** [comment]
> سلام تو لیست api ها api مربوط به سود و زیان روزانه در بازه 30 روزه موجود نیست از توی سایت میشه برای 7 روز رو دراورد ولی داخل موبایل از 30 روزش استفاده شده

سلام. وقت بخیر
مستندات به زودی اپدیت خواهند شد و این موارد رو هم اضافه خواهیم کرد.

**Comment by mheidarian** [comment]
> سلام تو لیست api ها api مربوط به سود و زیان روزانه در بازه 30 روزه موجود نیست از توی سایت میشه برای 7 روز رو دراورد ولی داخل موبایل از 30 روزش استفاده شده

خدمت شما
https://apidocs.nobitex.ir/#portfolio

**Comment by tomhub2020** [comment]
> افزایش از ۱۰۰ درخواست به ۲۰۰ درخواست در دقیقه

سلام. عذر میخوام منظورتون در 10 دقیقه هستش؟. چون تو سایت نوشته شده 200 درخواست در 10 دقیقه
البته پیش اومده که بیشتر از 200 هم توسط بات ثبت شده. امکانش هست آخرین تغییرات سقف درخواست رو اینجا بگین؟. تشکر

**Comment by farzinsb** [comment]
سلام آیا امکان اتصال از طریق وب سوکت یا WSS هم وجود دارد؟ یا فقط از طریق HTTP فعلا می توانیم به API متصل شویم که آن محدودیت های تعداد کانکشن را خواهد داشت. ادرس ساب دامین برای چنین اتصالی اگر دارید بفرستید

**Comment by rbabaee** [comment]
> > افزایش از ۱۰۰ درخواست به ۲۰۰ درخواست در دقیقه
> 
> سلام. عذر میخوام منظورتون در 10 دقیقه هستش؟. چون تو سایت نوشته شده 200 درخواست در 10 دقیقه البته پیش اومده که بیشتر از 200 هم توسط بات ثبت شده. امکانش هست آخرین تغییرات سقف درخواست رو اینجا بگین؟. تشکر

سلام. در حال حاضر سیصد تا در ده دقیقه هست.
