### ISSUE TITLE
اروری ثبت نشده هنگام تولید کلید وب سرویس

### ISSUE THREAD

**Issue by powerd3v** [nobitex/docs-api#97]
![image](https://user-images.githubusercontent.com/81742867/142841128-331c5963-d605-42a0-8cad-595cf7be9641.png)

طبق تصویر بالا اطلاعات من درست هستند اما در ریسپانس جیسون زیر رو برای من میاره

`
{
    "non_field_errors": [
        "OTP not provided"
    ],
    "code": "MissingOTP"
}
`

طبق داکیومنت اصلی سایت شما برای احراز هویت و دریافت کلید وبسرویس فقط 4 پارامتر نیاز هست:

Username , Password , remember , Captcha

![image](https://user-images.githubusercontent.com/81742867/142841626-8045fed6-cea2-4731-ac35-1f76c05dfbf2.png)

اما اروری که من دریافت کردم نوشته پارامتری به نام otp وارد نشده
ممکنه سریعا برسی کنید؟
متچکرم

**Comment by z-amini** [comment]
سلام.
وقت شما بخیر.

طبق دو خط آخر توضیحات ورود (دریافت توکن) در صورتی که احراز هویت دو مرحله ای را دریافت کرده باشید، به تنظیمات بیشتری نیاز هست که از لینک داده شده یا «ملاحظات عمومی > اعتبارسنجی دو عاملی» می‌توانید چگونگی آن را فرا بگیرید.

در صورتی که باز هم به مشکلی برخوردید، با ما در میان بگذارید.

**Comment by powerd3v** [comment]
سلام مشکلم برطرف شد متچکرم

در تاریخ سه‌شنبه ۲۳ نوامبر ۲۰۲۱،‏ ۱۲:۲۴ Zeynab Amini <
***@***.***> نوشت:

**Comment by z-amini** [comment]
Duplicate of #89
