### ISSUE TITLE
درگاه پرداخت

### ISSUE THREAD

**Issue by abdkaviani** [nobitex/docs-api#98]
باسلام
من کدهای زیر رو در حال استفاده هستم اما خروجی به من بر نمیگردونه
لطفا راهنمای بفرمایید مشکل من در کجاست
Notice: Trying to get property of non-object in send.php on line 31
باتشکر

`<?php`
`error_reporting(E_ALL);`
`ini_set('display_errors', '1');`

`$apiID          = "DemoApiKey";`
`$amount         = 1000000;`
`$callback    	= "https://mysite.xxx/nobitex/callback-gateway/";`
`$currencies   	= "btc";`
 
`if (!extension_loaded('curl')) {`
 `echo 'Curl Error!';`
`}`

`$data = array("api" => $apiID, "callbackURL" => $callback, "amount" => $amount, "currencies" => $currencies);`
`$header = array("content-type" => "application/json");`

`$ch = curl_init();`
`curl_setopt($ch, CURLOPT_URL, 'https://testnetapi.nobitex.market/pg/send/');`
`curl_setopt($ch, CURLOPT_POST, 1);`
`curl_setopt($ch, CURLOPT_POSTFIELDS, $data);`
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`
`curl_setopt($ch, CURLOPT_HTTPHEADER, $header);`
`curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);`
`$result = curl_exec($ch);`
`curl_close($ch);`
`$result = json_decode($result);`

`if (!empty($result->status) && $result->status == "success") {`
	`header("Location: https://testnet.nobitex.ir/app/paygate/". $result->token);`
`} else {`
  `echo $result->status;`
`}`
`?>`

**Comment by z-amini** [comment]
سلام و عرض ادب.

آدرس پایه تست نت وارد شده درخط ۱۸ صحیح نیست. مطابق [مستندات](https://apidocs.nobitex.ir/gateway?php#97be6d8642) این آدرس باید با پسوند ir باشد.

```
curl_setopt($ch, CURLOPT_URL, 'https://testnetapi.nobitex.ir/pg/send/');
```

در صورت عدم رفع مشکل با اصلاح این آدرس، مقدار پاسخ دریافت شده را ذیل این مسئله ضمیمه فرمایید تا امکان ارائه راهنمایی بهتری به شما داشته باشیم.

با تشکر.

**Comment by abdkaviani** [comment]
متشکرم. البته با لینک فوق هم مشکل پابرجاست
و خطای زیر رو نشون میده

`Notice: Trying to get property 'status' of non-object in /home/.../nobitex/send.php on line 31`

وقتی هم که از var_dump استفاده می کنم

`var_dump($ch);`

خروجی میشه resource(2) of type (curl) 

`var_dump($result);`

خروجی میشه NULL
ممنون میشم بیشتر راهنمایی م کنید

**Comment by z-amini** [comment]
ممکنه بفرمایید 
```
var_dump($result);
```
رو قبل از خط
```
 $result = json_decode($result);
```
استفاده می کنید یا بعدش؟
ترجیحا خروجی مستقیم بعد از فراخوانی api رو لطف بفرمایید.

**Comment by abdkaviani** [comment]
اگر به این صورت کدها رو بنویسم

`$result = curl_exec($ch);`
`var_dump($result);`

خروجی من اینه

`string(77)`
`Not Found`
`The requested resource was not found on this server.`
`Notice: Trying to get property 'status' of non-object in /home/..../public_html/nobitex/send.php on line 31`

_____________________
ضمنا من اول خواستم از متد زیر که در سایت شماست استفاده کنم

`$request = new HttpRequest();`

اما اون هم با خطای زیر مواجه میشم

`Fatal error: Uncaught Error: Class 'HttpRequest' not found`

**Comment by z-amini** [comment]
با سلام و احترام و عرض پوزش

ارائه درگاه پرداخت نوبیتکس شش ماه پیش متوقف شده و برنامه ارائه مجددش در آینده هنوز مشخص نشده.

از این که زودتر اطلاع رسانی ش انجام نشد، از شما عذر میخوام.

اگر نظری در این زمینه داشتید که دوست دارید انتقال داده بشه، با ما در میون بگذارید لطقا. 

بازم بابت تاخیرم عذر میخوام.

**Comment by abdkaviani** [comment]
ممنون
اگر زحمت بکشید در این [لینک ](https://apidocs.nobitex.ir/gateway#api)هم  اطلاع رسانی کنید تا  بازدیدکنندگان مطلع باشند
پیروز باشید

**Comment by z-amini** [comment]
سلام.
به روز رسانی مستندات انجام شد.

با تشکر.
روزتان بخیر.
